- Dockerfile
i accidentally pushed https://github.com/external-secrets/external-secrets/commit/adb4de943d8bda69eee95c2ac354c3ce92d605ed to main; this commit fixes the docker-build.
I enforced the review restrictions for administrators in the repository settings
> fix: update go/dockerfile 1.15

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- apis/externalsecrets/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/external-secrets.io_externalsecrets.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
I'd like to add some minor improvements and tests to ensure `refreshInterval` works as expected.
* add validation pattern to support both use-cases: zero-value and duration. AFAIK OpenAPI does not support golang-style time.Duration
* pass `es.refreshInterval` into ctrl result
* add printer columns for `refresh interval` and `store`
> fix: validate refresh interval, refresh externalsecret

- .github/PAUL.yaml
- README.md
- docs/contributing-coc.md
- hack/api-docs/mkdocs.yml
Just copied example CoC from https://www.contributor-covenant.org/version/2/0/code_of_conduct/
We can use another one or adapt as needed.
> Add CoC and references to it

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/provider/aws/provider.go
- pkg/provider/aws/provider_test.go
- pkg/provider/aws/secretsmanager/fake/fake.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/aws/secretsmanager/secretsmanager_test.go
- pkg/provider/aws/session/session.go
- pkg/provider/aws/session/session_test.go
- pkg/provider/fake/fake.go
- pkg/provider/provider.go
- pkg/provider/register/register.go
- pkg/provider/schema/schema_test.go
see #53
* move current `pkg/provider/aws` to `pkg/provider/aws/session`
* implement aws provider that inspects the `SecretStore.Spec` to return the correct SecretsClient
* add tests for session and aws provider
> feat: refactor provider / secretsclient interface

- .github/workflows/ci.yml
- Makefile
Incorporates fix from https://github.com/external-secrets/external-secrets/pull/70 to also fix missing docker buildx argument. Docker builds were not being persisted locally so they could not be pushed in the later workflow action.
> Fix ci docker

- .github/PAUL.yaml
Fix a typo in the open_message, at PAUL.yaml.
> Fix typo on PAUL.yaml

- .github/workflows/ci.yml
- .gitignore
- Makefile
- e2e/Dockerfile
- e2e/Makefile
- e2e/e2e_test.go
- e2e/entrypoint.sh
- e2e/framework/addon/addon.go
- e2e/framework/addon/chart.go
- e2e/framework/addon/eso.go
- e2e/framework/addon/localstack.go
- e2e/framework/addon/vault.go
- e2e/framework/eso.go
- e2e/framework/framework.go
- e2e/framework/log/log.go
- e2e/framework/util/util.go
- e2e/k8s/eso.values.yaml
- e2e/k8s/localstack.values.yaml
- e2e/kind.yaml
- e2e/run.sh
- e2e/suite/aws/secretsmanager.go
- e2e/suite/aws/util.go
- e2e/suite/import.go
- e2e/suite/vault/vault.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/provider/aws/provider.go
- pkg/provider/aws/provider_test.go
This is for #31 
**What the e2e test does**
I played a little bit around with the test setup and would like to propose to have shared components in the default namespace (ESO, Vault, Localstack) instead of launching the relevant components into a testing-namespace. That speeds up the test runtime and since we don't really need to configure the components differently we can share them for now.
The test process goes like:
* install localstack and vault into the `default` namespace using upstream charts
* install eso in the `default` namespace using the helm chart from `deploy/charts/external-secrets`
* each `It()` block gets its own namespace to run tests: 
* create SecretStore/ExternalSecret
* wait until `Kind=Secret` appears with expected values
I found the [cert-manager e2e …
> feat: e2e tests

- apis/externalsecrets/v1alpha1/secretstore_vault_types.go
- deploy/crds/external-secrets.io_clustersecretstores.yaml
- deploy/crds/external-secrets.io_secretstores.yaml
fixes #117
`vault.version` needs to be declared optional to get correct defaulting behavior
> fix: make vault version optional w/ defaults

- deploy/charts/external-secrets/templates/rbac.yaml
The additional ClusterRoles aggregate to the standard k8s ClusterRoles admin, edit, and view.  This allows for users that already have a binding to one or more of those standard ClusterRole to automatically have the appropriate permissions to the custom resources installed with this operator.
> Add aggregated ClusterRoles for view and edit permissions of custom resources

- deploy/charts/external-secrets/templates/rbac.yaml
The current helm chart does not grant the controller the appropriate "create" permission on leases for leader election to work.
> Update rbac.yaml to give the controller "create" permission on leases

- docs/contributing-process.md
Mention in the contributors guide that in order to create a PR,
branches must be pushed to a forked copy of the repo.
> Update contributors doc to include forking repo

- pkg/provider/aws/secretsmanager/secretsmanager_test.go
For readability and scalability, create a struct with default
test case values, then use anonymous function "tweaks" with only the
changes from default to test on.
> Add tweaks for secretsManager tests

- .github/workflows/helm.yml
- deploy/charts/external-secrets/Chart.yaml
Our Chart uses `appVersion` as image tag. The images we produce have a `v` prefix, this PR aligns that. `appVersion` needn't be semver ([docs](https://helm.sh/docs/topics/charts/)) / cert-manager does that, too.
> fix: appVersion needs prefix

- README.md
- docs/guides-getting-started.md
Got some complains regarding the README.md being outdated and with no quick example of a provider. This PR fixes that. Also removing the 'not ready' notice. I think it is clear since ESO version is 0.1.0. Let me know if you think that we should keep it.
> docs: Update readme instructions

- deploy/charts/external-secrets/Chart.yaml
Fixes https://github.com/external-secrets/external-secrets/issues/142
Tested against EKS cluster with gitVersion of `v1.17.17-eks-c5067d`
> Validate pre-release kubeVersions in helm chart

- deploy/charts/external-secrets/templates/deployment.yaml
By default, this chart added an `arg` field with no values.
Example:
1. Command on README.md
```
$ helm template external-secrets \
external-secrets/external-secrets \
-n external-secrets \
--create-namespace > hoge.yml
```
2. Nothing specified
```
$ helm template external-secrets 
```
It generates this Deployment which is causing errors.
<details><summary>Generated YAML</summary>
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: hoho-external-secrets
labels:
helm.sh/chart: external-secrets-0.1.1
app.kubernetes.io/name: external-secrets
app.kubernetes.io/instance: external-secreats
app.kubernetes.io/version: "v0.1.0"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: external-secrets
app.kubernetes.io/instance: hoho
template: …
```
> Remove arg of external-secrets container when no arg passed

- Makefile
In response to https://github.com/external-secrets/external-secrets/pull/144#issuecomment-843077877
Small CI change to make errors available in CI without needing to check on the issue locally. 
Example output:
```bash
11:39 $ make check-diff
11:39:37 [ OK ] Finished generating deepcopy and crds
11:39:37 [ OK ] Finished generating helm chart files
11:39:38 [ .. ] checking that branch is clean
M go.mod
11:39:38 [FAIL]
make: *** [Makefile:72: check-diff] Error 1
```
> ci: print diff error on failure

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- apis/externalsecrets/v1alpha1/zz_generated.deepcopy.go
- deploy/crds/external-secrets.io_externalsecrets.yaml
- hack/api-docs/Makefile
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/template/template.go
- pkg/template/template_test.go
This fixes #124 and #125.
What was the issue? 
It did not work as documented.
1. `Secret.Metadata` and `Secret.Data` was not updated after the external-secret has been changed: `CreateOrUpdate` does a `.Get()` before `.Update()` and modifies the object at the pointer.
2. #125 Template.Data was basically unusable due to having a `Data: []byte`. users would have to base64 encode the template string :cold_sweat:. This is now a simple `string` like it should have been from the get-go.
3. #124 Data from the secret provider could not be overridden with a template. Now the template takes precedence.
Example:
```yaml
apiVersion: external-secrets.io/v1alpha1
metadata:
name: example
spec:
...
target:
name: secret-to-be-created
template:
data:
firstname: "yadayada {{ .firstname …
```
> fix: template issues

- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/controllers/externalsecret/suite_test.go
- pkg/controllers/secretstore/suite_test.go
refactor controller tests to use ginkgo table-drive tests.
Also adds 1 testcase to test template update mechanics
> chore: refactor es ctrl tests

- .gitignore
- pkg/provider/aws/parameterstore/parameterstore_test.go
- refactor `parameterstore_test.go`, I try to follow the style with `secretsmanager_test.go` to keep it consistent
- ignore vim swp files 😁
> Refactor parameterstore unit test

- design/design-crd-spec.md
- docs/snippets/basic-external-secret.yaml
- docs/snippets/full-external-secret.yaml
Documentation of externalsecret `dataFrom` was just copy and paste from `data`. This PR updates the examples to reflect the expected structure.
> docs: Fix documentation for externalsecret dataFrom

- README.md
Adding some info to Readme regarding stability, who to look for when we need to figure out things about specific providers, and the support level that we can offer. I added Azure KV as community maintained, let me know if this does not make sense to you. It is one of the big Cloud providers, and of course we will also fix stuff and improve it, but I think it would be cool to let original devs take a bit of ownership, and be on the list of contacts.
@ahmedmus219 @ahmedmus-1A @asnowfix @ncourbet-1A @1A-mj you folks should of course have a say here :D
Basing this idea on https://github.com/kubernetes-sigs/external-dns
> Stability of providers and support notice

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/ok-to-test.yml
I created a github app with dummy values that asks access to content and metadata in the repo. Admins can see the gh-app here: https://github.com/organizations/external-secrets/settings/apps.
I then use this app just to make the ci impersonate it to trigger the other repository_dispatch triggered workflow. 
So a /ok-to-test sha=[commit to test] comment in a pr, will trigger the ok-to-test workflow, that will use this app's token to send a event to trigger the e2e workflow. Only people with write access to the upstream repo can send this comment on the PR.
Will need to merge this to actually test it, I think.
Reference: https://github.com/imjohnbo/ok-to-test
> feat: add ok-to-test workflow

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- deploy/crds/external-secrets.io_externalsecrets.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
This fixes #169.
Adds a `SyncedResourceVersion` to the Status field: it keeps track of the last synced external secret.
It's a string and has the schema `{generation}-{meta-hash}`. We can not rely solely on the metadata.generation, because it is not updated when object-meta changes. The hash is generated only from the `labels` and `annotations` fields.
We need this to: 
A) prevent the controller from reconciling an already synced secret (within the refresh interval)
B) do not reconcile if only the status field was changed (to prevent controller recon loops on status updates)
Example:
```
Status:
Conditions:
Last Transition Time:   2021-06-09T17:28:53Z
Message:                Secret was synced
Reason:                 SecretSynced
Status:                 True
Type:                   Ready …
```
> add synced resource version status

- README.md
We need to add `https://` in front of some links so github does not think it is a file under the repo. Not sure what to do with the email, leaving it not linked for now.
> chore(docs): Fix some broken links

- docs/provider-aws-secrets-manager.md
- docs/snippets/aws-sm-external-secret.yaml
- docs/snippets/aws-sm-store.yaml
Changed some stuff on the AWS SM example to enable people that want to get this quickly up to test and not think that much about the specification.
- Made it clear that role is a optional field, if they want to omit it for test purposes.
- Made the ExternalSecret example there be the complete file since people would want to just copy and paste and apply it right away :smile: 
The reasoning is that awssm is the most popular provider and this will probably be the doc page with most accesses with people trying out the project.
> chore(docs): AWSSM quick example changes

- .github/workflows/e2e.yml
- e2e/run.sh
Increasing kind timeout when waiting for a ready cluster. This needs to be on main to be able to test with ok-to-test on the other PRs
> fix: increase kind timeout

- pkg/provider/aws/secretsmanager/secretsmanager_test.go
- pkg/provider/gcp/secretmanager/secretsmanager_test.go
fixing test comparison, only comparing outputs if they don't have an error.
> fix: test comparison

- docs/artifacthub-repo.yml
This should make the chart appear as verifeid ( ![image](https://user-images.githubusercontent.com/326929/124471834-a43d0b00-dd9d-11eb-980a-c36ffbe9f880.png) ) on artifacthub 😄 
Not sure if this is the best place to put it, but eh. it should live next to index.yaml (the repo index) and putting it here should land it in the right place when deployed, to my understanding anyway.
> chore: add artifacthub repository ID to appear as verified

- deploy/charts/external-secrets/templates/rbac.yaml
The controller needs access to ConfigMaps in order to use `templateFrom` feature.
https://github.com/external-secrets/external-secrets/issues/179
> Add configmap rules for templateFrom

- docs/provider-aws-parameter-store.md
> fix(docs): correct parameter store policy typo

- docs/api-externalsecret.md
- docs/guides-templating.md
- docs/snippets/template-from-secret.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/template/template.go
- pkg/template/template_test.go
fixes #255 
fixes #232
This PR adds an example for using `templateFrom` to the docs. 
This PR also fixes an bug: templates from `templateFrom` weren't executed. Tests cover that now.
> fix(template): fix templateFrom tpl execution

- .github/FUNDING.yml
fixes #256 
As per docs: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository
This PR adds a funding button to this repo.
> feat: add open-collective funding button

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- deploy/crds/external-secrets.io_externalsecrets.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/controllers/externalsecret/suite_test.go
closes #229 
This PR adds the `creatonPolicy=Merge|None|Owner`. The CRD now defaults to `Owner`.
Existing ExternalSecrets with an empty creationPolicy may exist. 
After an upgrade they should be properly synced due to the `default:` case in the controller.
Im not sure what to do with `creationPolicy=None`. There is no real use-case for as far as i can see. In this implementation it is a no-op.
> feat(ctrl): implement creationPolicy=Merge/None

- docs/snippets/gcpsm-tls-externalsecret.yaml
> fix(docs): typo in secret name

- pkg/provider/aws/secretsmanager/secretsmanager_test.go
- pkg/provider/gcp/secretmanager/fake/fake.go
- pkg/provider/gcp/secretmanager/secretsmanager.go
- pkg/provider/gcp/secretmanager/secretsmanager_test.go
Add error condition in the secrets manager tests
Add check to see if the interface is nil in the GCP provider
> Nil interface check - Comparison test changes

- deploy/charts/external-secrets/templates/rbac.yaml
- pkg/provider/vault/vault.go
Fixes #277.
Updates the helm chart ClusterRole to allow updating and patching the `externalsecrets/finalizers` resource.
Changes the vault.go ServiceAccount logic to attempt every Secret listed in the ServiceAccount before returning an error indicating that no secret with a `token` key was found.
> Fix Openshift 4.7 issues

- e2e/suite/common/common.go
- e2e/suite/gcp/gcp.go
- go.mod
- go.sum
Created a p12 cert example. I think that for azure and aws would make sense to have tests for specific certificate types of secrets, or maybe using pem values directly. Trying to call their clients with p12 encoded data makes the call fail (even though it can maybe work if the secret is already created in the console, and then we check  the rest of the sync).
> tests: p12cert for gcp

- e2e/suite/azure/azure.go
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_test.go
Change Azure GetSecretMap to be similar to GCP implementation. Unit tests are not working for GetSecretMap - to be fixed in a future pull request. Closes #263
> fix azure GetSecretMap

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .gitignore
- Dockerfile
- Makefile
- e2e/Makefile
fixes #181 
This PR adds arm build in the ci pipeline. I would like to propose to use a "fat manifest" (aka [image-index](https://github.com/opencontainers/image-spec/blob/main/image-index.md)) that allows us to reference two platforms with a single tag. So a user does not need to specify a different tag when using the `arm64` platform.
**Notes for the reviewer:**
We can not use `docker buildx` with `--load` when using multiple platforms, see: https://github.com/docker/buildx/issues/59. I removed the build phase and do a build+push instead using `--push --platform linux/amd64,linux/arm64`.
The promotion process seems a bit hacky, but that's afaik the only way to re-use the existing, already pushed images.
I tested the promotion process during a test run, see here: …
> add arm build

- deploy/charts/external-secrets/templates/rbac.yaml
Getting this error with 0.3.1 Helm package.
Looks like it needed `patch` capability for `secrets` resource with this new version.
``` json
{
"level": "error",
"ts": 1627504654.6024714,
"logger": "controllers.ExternalSecret",
"msg": "could not reconcile ExternalSecret",
"ExternalSecret": "cattle-monitoring-system/containerservices-alertmanager",
"SecretStore": "/containerservices",
"error": "unable to patch secret containerservices-alertmanager: secrets \"containerservices-alertmanager\" is forbidden: User \"system:serviceaccount:vault-infra:external-secrets-kubernetes-external-secrets\" cannot patch resource \"secrets\" in API group \"\" in the namespace \"cattle-monitoring-system\"",
"stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/h …
```
> unable to patch secret. is forbidden

- .github/workflows/release.yml
Previously the "last tag" was promoted  (e.g. `v0.3.1-5-gbc62415`). This tag can point to a container image that doesn't exist. This is the case if a PR skipped the container image creation.
> fix: promote main on release

- .github/workflows/e2e.yml
#285 introduced a new schema for the e2e test trigger. The e2e integration-fork action would skip bc the sha doesn't match.
This PR tries to fix this issue.
> fix: ok-to-test trigger

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- pkg/controllers/externalsecret/externalsecret_controller.go
When a metrics is deleted metrics are still shown ready and condition true.
In practice this gives the wrong monitoring as the external secret in practice
is deleted.
Issue: #231
> Set the metric when is deleted to condition deleted and false

- docs/provider-ibm-secrets-manager.md
- docs/snippets/ibm-es-types.yaml
- docs/snippets/ibm-secret-store.yaml
- docs/spec.md
Fixes: #301 
This PR adds documentation around secret types for the IBM Secrets Manager that were introduced in #271.
Co-Authored-By: Tymofii Polekhin <tpolekhin@users.noreply.github.com>
> docs: add ibm secret types docs

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- deploy/crds/external-secrets.io_externalsecrets.yaml
> feat: add status printcolumn to ES CRD

- docs/snippets/vault-approle-store.yaml
minor  change for docs page https://external-secrets.io/provider-hashicorp-vault/ to avoid confusing example - secret accepts AppRole SecretId, not a 'vault-token'
[VaultAppRole](https://github.com/external-secrets/external-secrets/blob/e65658d543a759b1d71f2774951f0d473d6201e2/apis/externalsecrets/v1alpha1/secretstore_vault_types.go#L110-L114)
> docs: fix appRole example

- pkg/controllers/externalsecret/externalsecret_controller.go
Now if the target Secret name is not specified it should use the ExternalSecret name.
fix #321 
I still need to work on the tests.
> fix: use external secret name if target secret is not specified

- pkg/controllers/externalsecret/externalsecret_controller.go
The issue is that the `dataMap` from the provider returns only the remaining data
and we were updating partially the current `secretMap` only for the keys included
in the new value.
Ticket: #315
> Fix the issue for non deleting one/more key-value pair

- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/serviceaccount.yaml
pr for issue: #326 
Added namespace to the deployment and Service account chart templates so `helm template --include-crds --output-dir ./output_dir deploy/charts/external-secrets` will generate k8s resources with the supplied namespace. If no namespace is provide the helm will default the namespace to `default` preserving the current functionality.
> add namespace to deployment and service account templates

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/values.yaml
- e2e/e2e_test.go
- e2e/framework/addon/eso.go
- e2e/k8s/eso.scoped.values.yaml
- main.go
By default ESO reconciles `Kind=ExternalSecret` across every namespace
in a k8s cluster. With the new flag `--nameespace` we can scope the
reconciling only to the provided namespace.
Ticket: #289
> Add the ability of ESO to reconcile only in scoped namespace

- apis/externalsecrets/v1alpha1/secretstore_gcpsm_types.go
- apis/meta/v1/types.go
- deploy/crds/external-secrets.io_clustersecretstores.yaml
- deploy/crds/external-secrets.io_externalsecrets.yaml
- deploy/crds/external-secrets.io_secretstores.yaml
- pkg/provider/gcp/secretmanager/secretsmanager.go
If the name of the service account secret is kept
empty, this means we want to use Google Cloud Identity
to authenticate against the GCP project
> Add support for Google Cloud Identity

- docs/provider-aws-parameter-store.md
- docs/snippets/provider-aws-access.md
Fixes https://github.com/external-secrets/external-secrets/issues/342
There were several places in docs where region was missing.
> chore: add missing region key to aws provider in docs

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/utils/utils.go
fixes #362
This PR adds a test for the issue described in #362: allow using template.metadata without specifying anything via `template.data` or `templateFrom`. 
I also moved the template related functionality into a dedicated file (kinda similar like [flux/kustomize-controller](https://github.com/fluxcd/kustomize-controller/tree/main/controllers) does it).
> fix: allow using tpl metadata

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- e2e/framework/eso.go
- e2e/suite/aws/provider.go
- e2e/suite/aws/secretsmanager.go
- main.go
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- tools.go
Addresses https://github.com/external-secrets/external-secrets/issues/344
Long story short: when a child with correct ownerref is deleted, reconcile loop is triggered as it should be, however, then we hit https://github.com/external-secrets/external-secrets/blob/8026bb87bbbcb7330c20a861ff482ec2572a35e9/pkg/controllers/externalsecret/externalsecret_controller.go#L165
By this point, we are still unaware if kind=secret exists or not, and if condition for refresh is not met, we simply get out of the loop thus not creating the child. 
Imho there are 2 ways to address this: 
1) we force the sync in case of missing child (not too big of an issue, just another API hit for external store). 
2) we use the "stale" data and proceed with recreation of the secret only. 
@moolen  / @knelasevero do you …
> fix: dependent kind=secret are not recreated in case of deletion. 

- .github/workflows/ci.yml
- sonar-project.properties
Added sonar-prpoject.properties file which is used by SonarQube to determine what the project/organization is and it also includes where the coverage file is.
I also updated ci.yaml to delete CodeCov step and added SonarQube analysis instead of that. This way Sonar analysis will run in a push manner instead of its default.
Before this PR is approved, the steps I mentioned in the issue must be taken. #168
> Add Sonar analysis to CI and push coverage to it #168

- .github/workflows/ci.yml
We only added sonar manual step to have coverage, but in the end it will be better to just have sonar for code quality and any other coverage tool for coverage.
> chore: remove sonar manual step

- pkg/provider/vault/fake/vault.go
- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
Fixes #376
The Vault client now revokes it's token on `Close` if one exists and it was obtained via any auth method except for `TokenSecretRef`
> Revoke Vault token on Close

- e2e/suite/alibaba/alibaba.go
- e2e/suite/azure/azure.go
- e2e/suite/gcp/gcp.go
- e2e/suite/gitlab/gitlab.go
Remove cred dependency if you wanna run less tests, so we don't have to export all creds if we want to run tests for only one of the providers
> Remove cred dependency if you wanna run less tests

- pkg/controllers/externalsecret/externalsecret_controller_test.go
Fixing the following code smells found in SonarCloud:
at pkg/controllers/externalsecret/externalsecret_controller_test.go:
- Define a constant instead of duplicating this literal "test-secret" 3 times.
- Define a constant instead of duplicating this literal "fake.manager" 4 times.
- Define a constant instead of duplicating this literal "SOMEVALUE was templated" 3 times.
- Define a constant instead of duplicating this literal "{{ .targetProperty | toString | upper }} was templated" 3 times.
- Define a constant instead of duplicating this literal "map-foo-value" 6 times.
- Define a constant instead of duplicating this literal "map-bar-value" 5 times.
> Fixing some codeSmells

- .github/workflows/ci.yml
- .golangci.yaml
- Makefile
- e2e/framework/addon/vault.go
- pkg/provider/register/register.go
- Update golangci-lint to 1.42.1
- Fix install make target with new shell script URL
- Replace deprecated lints with suggested alternatives
- Mute one new lint on an e2e test function
Closes #453
> golangci-lint install and version update

- pkg/controllers/externalsecret/externalsecret_controller.go
This commit implements logging for first successful reconciliation after an error or externalSecret creation.
Fixes #444
> Added log for first secret reconciliation after errors

- e2e/Dockerfile
- e2e/Makefile
- e2e/entrypoint.sh
- e2e/run.sh
- go.mod
- go.sum
- tools.go
Mostly TLC for the e2e tests that I pulled out of a separate change I was working on.
> Bump e2e kind & tools versions, remove dep on ginkgo on path

- README.md
Vault is the most used provider right now, with people reporting that they are using it with hundreds of secrets and no problems. Also, Vault is the only one that enabled us to write extensive e2e testing since we can just spin vault up in CI. I want to promote it to stable to ease people's minds :smile: but let me know if you think beta would be more appropriate.
> Update README.md - promote vault

- e2e/framework/addon/vault.go
- go.mod
- go.sum
Also fixes CVE-2020-26160 (even though this is used only for e2e tests)
> Bump jwt module

- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/495
> fix: checking nil values when reading secret in vault provider

- pkg/utils/utils.go
- pkg/utils/utils_test.go
Fixes #501 
`IsNil()` fails when given a struct value. That caused the oracle provider to fail. Other providers are not affected, they all use pointers :)
> fix: IsNil fails on struct value

- README.md
Promote aws and gcp to beta :) 
When we have e2e tests for all auth methods in these providers, a good amount of runs, and we get consensus on a community meeting, we can also upgrade them to stable, as we did for vault.
> Promote aws and gcp to beta

- Dockerfile
- e2e/Dockerfile
Bumping alpine of the e2e tests, and replacing main base image with distroless.
We get quite a few CVEs raised almost every week because of alpine packages, we can lower our maintenance considerably by just not having packages in our provided image.
We can use ephemeral containers to debug stuff, and we now have ways to get logs into aggregators and all that.
When we finish the reporter this will also get even easier.
Anyways I think we could already move to distroless, since this project is kinda sensitive when we think about security.
> chore: replace alpine by distroless

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/values.yaml
Allow adding annotations to Deployment via Helm values.
This enable using some third-party tools which rely on adding annotations on `Deployment`,`Statefulset`,`Daemonset`. For example, adding annotations to external-secrets Deployment allow [stakater-reloader](https://github.com/stakater/Reloader) to restart(and reload) deployment upon `ConfigMap` or `Secret` modifications.
> Add annotation to Deployment

- pkg/provider/gcp/secretmanager/secretsmanager.go
- pkg/provider/gcp/secretmanager/secretsmanager_test.go
Common idiom for GCP SM is like:
```json
{
"name": {
"client_id": "<client_id>",
"client_secret": "<client_secret>",
}
}
```
Using DataFrom, the current GCP SM will fail to unmarshal cause it's expecting
```json
{
"name": "{\"client_id\": \"<client_id>\", \"client_secret\": \"<client_secret>\"}",
}
```
which is much more annoying to work with.  By tweaking the implementation to
try to decode to a string, but if that fails, use the raw `[]byte` of the value
we get the best of both worlds.
> Support common idiom for GCP SM

- RELEASE.md
- docs/guides-getting-started.md
- docs/index.md
- docs/spec.md
This is just the **user documentation** part. Most work was done on the installer operator.
The maintainer/how-to-release documentation can be found [here](https://github.com/external-secrets/external-secrets-helm-operator/blob/main/docs/release.md#operatorhubio).
I forked the operator-sdk (helm) based installer-operator from [3scale-ops/external-secrets-operator](https://github.com/3scale-ops/external-secrets-operator), it's now available here: https://github.com/external-secrets/external-secrets-helm-operator.
What had to be done:
* let OLM manage the lifecycle of CRDs
* migrate images to `ghcr.io`
* update csv: docs, links, crd examples etc.
* push bundles for `0.3.8`, `0.3.9`, `0.3.10` to operatorhub [external-secrets-operator](https://operatorhub.io/operator/external-secrets-operator) …
> docs: add OLM docs

- docs/snippets/full-cluster-secret-store.yaml
There is no example for AWS IRSA in ClusterSecretStore doc.
https://external-secrets.io/api-clustersecretstore/
SecretStore IRSA setting doesn't need `namespace`, but ClusterSecretStore require it. It may become a pitfall.
https://github.com/external-secrets/external-secrets/blob/05a8f1739673a7ddade89cdefcd52ec70db2aa25/pkg/provider/aws/auth/auth.go#L163-L165
> add ClusterSecretStore AWS IRSA example setting docs

- docs/guides-all-keys-one-secret.md
This PR fixes minor typo in kubectl commands.
> fix(docs): typo in kubectl commands

- apis/externalsecrets/v1alpha1/secretstore_vault_types.go
- deploy/crds/external-secrets.io_clustersecretstores.yaml
- deploy/crds/external-secrets.io_secretstores.yaml
- docs/provider-hashicorp-vault.md
- docs/snippets/vault-jwt-store.yaml
- docs/snippets/vault-ldap-store.yaml
- e2e/framework/addon/vault.go
- e2e/k8s/vault-config/configure-vault.sh
- e2e/suite/vault/provider.go
- pkg/provider/vault/vault.go
Proposes a fix for issue #540 
The code is based on the same workflow as https://external-secrets.io/provider-hashicorp-vault/#approle-authentication-example
It extends the ask to also include the same fix for the JWT/OIDC authentication method.
Further details on how Hashicorp Vault uses this path can be found on the issue referenced above.
> Add Path Parameter to LDAP and JWT/OIDC Hashicorp Vault Auth

- docs/provider-hashicorp-vault.md
The basic ExternalSecret example is referencing a ClusterSecretStore
while all of the examples of configuring a provider are a /SecretStore/.
This means that a new user try to cut'n'paste the examples will be
unable to create a working demo without reading the API reference.
> change ExternalSecret example to use SecretStore

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
fixes #583 
It seems like there is an issue when mixing operation=Update and operation=Apply; It's best described here: https://github.com/kubernetes/kubernetes/issues/80916#issuecomment-525049458 - it looks like we can't do server-side apply with client-side applied resources.
IMO we should force ownership of the fields we care about.
[docs](https://kubernetes.io/docs/reference/using-api/server-side-apply/#using-server-side-apply-in-a-controller) say:
> It is strongly recommended for controllers to always "force" conflicts, since they might not be able to resolve or act on these conflicts.
> fix: force ownership when merging secrets

- .github/workflows/docs.yml
deploy docs job fails on main, it seems to use a old go version 1.15.x
> fix: gen-docs version update

- pkg/provider/oracle/fake/fake.go
- pkg/provider/oracle/oracle.go
- pkg/provider/oracle/oracle_test.go
Proposes a fix for issue #504.
Replaces the OCI `vaults` package for `secrets` to retrieve the secrets using `secrets.GetSecretBundle()`.
I couldn't create an OCI account so I was unable to test and check the payload.
> Replace vaults with secrets package to retrieve secrets

- apis/externalsecrets/v1alpha1/secretstore_oracle_types.go
- deploy/crds/external-secrets.io_clustersecretstores.yaml
- deploy/crds/external-secrets.io_secretstores.yaml
- docs/provider-oracle-vault.md
- docs/snippets/oracle-external-secret.yaml
- docs/snippets/oracle-secret-store.yaml
- pkg/provider/oracle/fake/fake.go
- pkg/provider/oracle/oracle.go
- pkg/provider/oracle/oracle_test.go
Following to https://github.com/external-secrets/external-secrets/issues/587
add Vault ID field to the SecretStore, then use the ExternalSecret's key as a secret name in the provided Vault.
> OCI Vault: Get secret by name from a specific Vault

- README.md
- design/000-template.md
- design/design-crd-spec.md
- docs/contributing-process.md
- docs/index.md
- docs/spec.md
As discussed in the community meeting i added docs for:
1. proposal process + template
2. bi-weekly development meeting
3. a note about PR-close 
PTAL and add things to the proposal template if something is missing. The template is a stripped version of the KEP template.
> feat(docs): add proposal process, add bi-weekly meeting

- pkg/provider/webhook/webhook_test.go
webhook unit tests fail sometimes with
```
webhook_test.go:307: error timeout: unexpected error: 
'failed to call endpoint: Get "http://127.0.0.1:43551/api/getsecret?id=testkey&version=1": 
dial tcp 127.0.0.1:43551: i/o timeout 
(Client.Timeout exceeded while awaiting headers)' (expected 'context deadline exceeded')
```
This can be reproduced like this:
```
go test -race -failfast -count=2000 -v ./pkg/provider/webhook
```
This PR fixes this issue by using a context *with* timeout (seems weird, but [this](https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/net/http/client.go;l=354;drc=refs%2Ftags%2Fgo1.17.6) is the reason).
> fix: webhook test race

- pkg/controllers/externalsecret/metrics.go
ref: #471
This is an initial attempt at tackling #417, I've kept the logic fairly simple in
metrics.go.
It might be better off being implemented elsewhere. (in `SetExternalSecretCondition`
perhaps?)
> fix(metrics): ensure status_condition metrics reflect the status

- .github/codecov.yml
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
Fixes #315 
When using `spec.Target.Template` with an empty `spec.Target.Template.Data` the secret. That was caused by this particular code path:
https://github.com/external-secrets/external-secrets/blob/0b9c142a22b98c0845bc15dcfb5992d1ddc2aaa1/pkg/controllers/externalsecret/externalsecret_controller_template.go#L64-L71
This PR fixes it and adds test cases for it.
> fix: ensure that data is being deleted when using tpl

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- e2e/Makefile
- pkg/controllers/externalsecret/suite_test.go
* use setup-envtest
* kubebuilder/envtest: use v1.23.3
* fix envtest issue `timeout waiting for process kube-apiserver to stop` for 1.21+
> chore: update k8s / envtest

- docs/provider-google-secrets-manager.md
I was facing SecretsSyncedError due to namespace being not set in case of a ClusterSecretStore.
Where should i add the NOTE ?
> Fix documentation for namespace in ClusterSecretStore

- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/service.yaml
based on #673 but also removes the `targetPort` from the `service.yaml` and adds the port name to the `deployment.yaml`
> fix: add port name to deployment and service

- hack/api-docs/mkdocs.yml
Both pages had the same name and it was messing up the analytics of the website.
> fix: gcp service name in singular

- .github/workflows/e2e-managed.yml
- .github/workflows/e2e.yml
The version bump introduced in d6602b56 broke the e2e and e2e-managed workflows. this is an attempt to fix the github-script.
> fix: update github-script actions

- pkg/provider/gcp/secretmanager/secretsmanager.go
- pkg/provider/gcp/secretmanager/secretsmanager_workload_identity.go
- pkg/provider/gcp/secretmanager/secretsmanager_workload_identity_test.go
#290 is a great fix!
However, the GCP's IAM client has an internal gRPC connection, so if the fetch secret fails, the goroutine created by the gRPC connection will leak.
Therefore, close the IAM client when the creation of the GCPSM client fails.
I intentionally caused a Permission denied error on a GKE cluster with workload identity and measured the number of goroutines before and after applying this patch.
> Fix the leak in GCPSM when the secret operator cannot find the secret.

- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
Fixes #725 
For backwards compatibility: A key defined in `ref.Property` should first lookup the key from the vault json response and then try to interpret the `ref.Property` as gjson expression.
> fix: vault keys should take precedence over gjson

- main.go
- pkg/controllers/externalsecret/externalsecret_controller.go
Fixes #721 
Details are in https://github.com/external-secrets/external-secrets/issues/721#issuecomment-1041515014.
I'm wondering if we should hide that feature behind a feature flag or if it should be enabled by default.
I did some testing with a lot secrets: ~2k `Kind=Secret` with 512k each:
* mem consumption without this patch is ~1GB
* mem consumption with this patch is < 100 MB
> feat: avoid caching secrets/configmaps

- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_test.go
This PR does a little bit of cleanup to make it easier to implement more authentication methods in the future (#611).
Changes: 
* hoisting the error messages to the top of the file
* store the `AzureKVProvider` in the `Azure` struct
* use const for `cert` and `key` object-types
* some variable renaming
> chore: cleanup az/keyvault provider

- apis/externalsecrets/v1alpha1/secretstore_types.go
- deploy/crds/external-secrets.io_clustersecretstores.yaml
Our reporter show status for SecretStores:
```
kubectl get secretstores
NAME            AGE   STATUS
azure-backend   13s   InvalidProviderConfig
```
But not for ClusterSecretStores:
```
kubectl get clustersecretstores                     
NAME            AGE
azure-backend   5m
```
This PR fixes this issue by adding appropriate kubebuilder tags to `ClusterSecretStore` object.
> Adding status information to kubectl get css

- docs/snippets/provider-aws-access.md
Fixes #739 
related: #651 
Initially this was an internal-use-only feature to support e2e tests with localstack. Because some users already use this it makes sense to properly document it.
> docs(aws): describe how to use custom endpoints

- pkg/controllers/externalsecret/externalsecret_controller_template.go
The External Secrets documentation has the following example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: grafana-config-tpl
data:
config.yaml: |
datasources:
- name: Graphite
type: graphite
access: proxy
url: http://localhost:8080
password: "{{ .password }}"
user: "{{ .user }}"
---
apiVersion: external-secrets.io/v1alpha1
metadata:
name: my-template-example
spec:
target:
name: secret-to-be-created
template:
engineVersion: v2
templateFrom:
- configMap:
name: grafana-config-tpl
items:
- key: config.yaml
data:
- secretKey: user
remoteRef:
key: /grafana/user
- secretKey: password
remoteRef:
key: /grafana/password
```
This configuration currently triggers some fallback logic and would result in a non-templated secret with just the key value data because …
> Fix template fallback logic to handle TemplateFrom syntax

- docs/provider-google-secrets-manager.md
Some minor things I noticed, while I was following the guide to use ESO with Google Secrets Manager
- Fixes some typos
- Clarify where the `external-secrets` KSA comes from and how it interacts with the helm chart
Apart from that, the docs were pretty easy to follow, and I made it work without much hassle. Great job! 👏
> Improve GCP docs

- docs/snippets/provider-aws-access.md
This snippet is too generic and it may confuse users of Parameter Store backend in provided examples .
> Added note about ParameterStore

- apis/externalsecrets/v1alpha1/secretstore_gcpsm_types.go
- apis/externalsecrets/v1beta1/secretstore_gcpsm_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/snippets/gcpsm-wi-secret-store.yaml
- pkg/provider/gcp/secretmanager/secretsmanager_workload_identity.go
- pkg/provider/gcp/secretmanager/secretsmanager_workload_identity_test.go
Fixes #772 
Initial proposal of begin able to have your GKE cluster in a different project that where the GCPSM is. I did not yet update any docs or tests. Input / help is welcome
Intend for now is to be backward compatible so this feature can be released without any blockers
> GCP: allow cluster to be in different project

- e2e/suite/gitlab/provider.go
- go.mod
- go.sum
- pkg/provider/gitlab/fake/fake.go
- pkg/provider/gitlab/gitlab.go
Updated code accordingly to allow bumping.
> Chore: bumping gitlab-go to 0.58.0

- docs/snippets/ibm-external-secret.yaml
this template is used mostly as is, and the previous `refreshInterval` of `1m` is to high and produces only too much pressure on the API endpoints
> Minor change - IBM Cloud SM example - refreshInterval 60m

- design/001-secretsink.md
This is a Draft proposal for the CRD change for #347.
Note: after typing the original idea of a separate CRD, it really feels awkward to have so many duplicate fields to add the capability to sync back the secret. Taking that into account, this proposal has small 'surgical' changes to our current CRDs to allow this feature. Although most of them are optional, some of them cause breaking changes.
This is not even close from the final draft, as we Might need to think more on the specifics of it all.
> Added draft proposal for Secret Sink

- apis/externalsecrets/v1alpha1/secretstore_azurekv_types.go
- apis/externalsecrets/v1alpha1/zz_generated.deepcopy.go
- apis/externalsecrets/v1beta1/secretstore_azurekv_types.go
- apis/externalsecrets/v1beta1/zz_generated.deepcopy.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/provider-azure-key-vault.md
- docs/snippets/azkv-workload-identity-mounted.yaml
- docs/snippets/azkv-workload-identity.yaml
- docs/spec.md
- go.mod
- go.sum
- pkg/provider/aws/auth/fake/token_fetcher.go
- pkg/provider/aws/auth/token_fetcher_test.go
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_auth_test.go
- pkg/provider/azure/keyvault/keyvault_test.go
Fixes #611 
There was one minor change from the initial proposal:
Instead of specifying the `client-id` and `tenant-id` via SecretStore we can simply infer them from the Service Account.
I noticed that the azure keyvault provider does only support Azure Public Cloud. USGov/German/China clouds are not supported (#428).
Sanitized example manifests:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: workload-identity-sa
namespace: default
annotations:
azure.workload.identity/client-id: 7d8cdf74-xxxx-xxxx-xxxx-274d963d358b
azure.workload.identity/tenant-id: 5a02a20e-xxxx-xxxx-xxxx-0ad5b634c5d8
---
apiVersion: external-secrets.io/v1alpha1
metadata:
name: example-secret-store
spec:
provider:
azurekv:
vaultUrl: "https://xx-xxxx-xx.vault.azure.net"
authType: …
```
> feat(azure): implement workload identity

- pkg/provider/fake/fake.go
- pkg/provider/fake/fake_test.go
- pkg/provider/ibm/provider.go
- pkg/provider/ibm/provider_test.go
- pkg/utils/utils.go
This PR adds ValidateStore calls for the following providers.
It was also added a change to `utils.ValidateSecretSelector` in order to make sure `Name` and `Key` values are never empty.
* Fake
* IBM
Fixes #860 
Fixes #858
> Adds ValidateStore for some providers

- cmd/root.go
- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/rbac.yaml
- deploy/charts/external-secrets/values.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
First of all thanks for this amazing project!
I created this PR first and am looking for some helps on this PR before I go too far off so any assistance is greatly appreciated.
I have an issue building using the `main` branch as it is very different from the `v0.4.4` tag.
This PR is built on top of v0.4.4 and modified based on the changes in the `main` branch.
**Summary**
This PR is a follow-up on the [scopedNamesapce](https://github.com/external-secrets/external-secrets/pull/320) and is addressing the [comment](https://github.com/external-secrets/external-secrets/pull/320#issuecomment-904420147) for scoped RBAC roles.
The current implementation of `scopedNamespace` is using Cluster roles to access Kube API.
There are two major security concerns:
1. The operator can access ExternalSecret …
> Add the ability to support scoped RBAC with a scoped namespace

- Makefile
- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/values.yaml
In our use case, we strictly disallow external secrets to be created in the cluster scope.
Add flags to each of the CRDs so that we can skip the creation of all cluster-scoped CRDs during the deployment.
Example:
```helm
{{- if and (.Values.installCRDs) (.Values.crds.createClusterExternalSecret) }}
(...content omitted)
{{- end }}
```
> add create flags to each CRDs resources for a more fine-grained control

- docs/guides-getallsecrets.md
- docs/snippets/getallsecrets-find-by-name.yaml
- docs/snippets/getallsecrets-find-by-tags.yaml
- hack/api-docs/mkdocs.yml
Adds documentation around using `dataFrom.find`, regardless of the provider.
> Chore: GetAllSecrets documentation

- pkg/controllers/externalsecret/externalsecret_controller.go
I didn't see a sufficient reason to put a fixed re-queue on error.
Controller Runtime can manage internally exponential retry, so we should let the controller manage that by itself.
I haven't checked the whole method but I'm pretty sure that `return ctrl.Result{RequeueAfter: requeueAfter}, nil` on error is an anti-pattern. Maybe I should also apply this fix on the following lines:
- https://github.com/external-secrets/external-secrets/blob/c00afc9ff7575b37b4e332e214c270fc25bb09ae/pkg/controllers/externalsecret/externalsecret_controller.go#L120
- https://github.com/external-secrets/external-secrets/blob/c00afc9ff7575b37b4e332e214c270fc25bb09ae/pkg/controllers/externalsecret/externalsecret_controller.go#L135
- https://github.com/external-secrets/external-secrets/blob/c00afc9ff7575b37b4e332e2 …
> fix: use controller-runtime internal backoff retry

- pkg/provider/gcp/secretmanager/secretsmanager.go
- pkg/provider/gcp/secretmanager/secretsmanager_test.go
> GCP: Adds checks to see if a key name exists before trying to load a nested value

- deploy/charts/external-secrets/templates/cert-controller-rbac.yaml
Previously both `certController.create` and `certController.rbac.create` needed to be set to `false` in order to prevent the cert-controller RBAC resources from being created.
> fix: only create cert-controller RBAC resources if cert-controller creation itself is enabled

- pkg/provider/vault/vault.go
The error message for an invalid SecretRef was used before mistakenly.
> fix: error message for Vault store validation of `Auth.Jwt.KubernetesServiceAccountToken`

- pkg/provider/vault/vault.go
By default Vault client config is configured to retry twice... we prefer to rely on the reconcile loop.
Can move the vault fix to another PR if you want.
> Delegate retry to the controller

- docs/provider-kubernetes.md
Simplify the In-cluster secrets example to work out-of-the-box and ease on-boarding.
> Simplify the In-cluster secrets example

- e2e/suite/gcp/gcp.go
- e2e/suite/gcp/provider.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/gcp/secretmanager/fake/fake.go
- pkg/provider/gcp/secretmanager/secretsmanager.go
GetAllSecrets implementation for gcp provider.
TODO:
> feat: gcp getall implementaion

- pkg/provider/akeyless/akeyless.go
- pkg/provider/alibaba/kms.go
- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/provider.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/gcp/secretmanager/secretsmanager.go
- pkg/provider/gitlab/gitlab.go
- pkg/provider/ibm/provider.go
- pkg/provider/kubernetes/kubernetes.go
- pkg/provider/oracle/oracle.go
- pkg/provider/vault/vault.go
- pkg/provider/webhook/webhook.go
- pkg/provider/yandex/lockbox/lockbox.go
Closes #644
Forces interface validation even if we didn't call it yet. For already implemented (or sufficiently implemented) providers this would not make much of a difference, but it helps a lot when you are developing a new provider, and did not reach the parts where structs are actually being assigned to comply with interfaces. With that said it makes sense to have this at the top of every provider so people implementing new ones can look and know that this is a thing
> chore: force interface validation

- pkg/provider/gitlab/fake/fake.go
- pkg/provider/gitlab/gitlab.go
- pkg/provider/gitlab/gitlab_test.go
This is my attempt at #889 .  I ended up using the ListVariable call on the project so a key wasn't necessary.  It ignores the results and checks the resp and err to make sure it worked.  Doing tests in KinD showed it working as I would expect (bad token = shows the GET with a 401) but works with a valid token.  Attempted to follow the pattern with the fake, but feedback always appreciated.
Biggest questions I have are:
Are you comfortable using list to validate our permissions?
WIthout knowing the ins/outs of the gitlab API, I may have been heavy handed with my if's to validate.  Would love thoughts/opinions on those lines.
> Implement validate for gitlab provider

- Makefile
- docs/contributing-devguide.md
- docs/contributing-process.md
- docs/spec.md
- e2e/suite/akeyless/provider.go
- hack/api-docs/generate.sh
- pkg/provider/azure/keyvault/keyvault_auth_test.go
This doesn't have it's own issue, but these bugs were run across while working on https://github.com/external-secrets/external-secrets/issues/36 / https://github.com/external-secrets/external-secrets/pull/1006. I thought a separate PR made sense.
It seems like a mistake that the docs still point to the v1alpha1 API, this fixes that. Also fixes to make `make lint`/`make fmt` pass.
> Update docs from v1alpha to v1beta1, fix typos

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/webhook-secret.yaml
- deploy/charts/external-secrets/values.yaml
Implements https://github.com/external-secrets/external-secrets/issues/1002
This would allow a user to define annotations for the webhook secret in `values.yaml`
> feat: (helm chart) enable annotations for webhook secret

- docs/snippets/gcpsm-docker-config-externalsecret.yaml
Manifest in documentation has a duplicate name entry for the remote reference
> Remove duplicate entry

- docs/snippets/multiline-template-v2-external-secret.yaml
- pkg/template/v2/template_test.go
Hi ! 
This is a simple contribution for the Template docs. 
For database URLs, its common to have small differences in protocol naming, and the "replace" function is helpful in these cases.
A few examples: java applications might expect `postgresql://...` while python expects `db+postgresql://` or even `postgresql+psycopg2://`.
It also adds a test for this case, but it might be unnecessary (and I can remove it so you chose).
> Adds string replacement usage and test in Template

- apis/externalsecrets/v1alpha1/secretstore_types.go
- apis/externalsecrets/v1beta1/secretstore_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
> Fix case in Gitlab description

- docs/provider-kubernetes.md
The indent is incorrect:
```
error: error validating "STDIN": error validating data: [ValidationError(ClusterSecretStore.spec.provider.kubernetes.server): unknown field "auth" in io.external-secrets.v1beta1.ClusterSecretStore.spec.provider.kubernetes.server, ValidationError(ClusterSecretStore.spec.provider.kubernetes): missing required field "auth" in io.external-secrets.v1beta1.ClusterSecretStore.spec.provider.kubernetes]; if you choose to ignore these errors, turn validation off with --validate=false
```
> docs: fix syntax in Kubernetes provider examples

- docs/provider-aws-secrets-manager.md
- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/aws/secretsmanager/secretsmanager_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/1036
When the `version` field is set on the remoteRef for an ExternalSecret which references an AWS SecretsManager secret, it will only set the `VersionStage` field of the GetSecretValue api call. SecretsManager secrets can also be referenced by their `VersionId`, which is an immutable tag that is generated every time the secret is modified. This allows users to set a version for their secrets manager secrets and know that the secret in the cluster will not change even if the external secret is modified.
> Add support for referencing secrets manager secrets by their VersionId

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/cert-controller-poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/webhook-poddisruptionbudget.yaml
- deploy/charts/external-secrets/values.yaml
Add support to PodDisruptionBudget to increase HA of ExternalSecrets deployments.
What is the added value?
Achieve HA for ExternalSecrets deployments
Give us examples of the outcome
Add pdb to certController
Add pdb to webhook
Add pdb to operator
A fix to the issue reported in https://github.com/external-secrets/external-secrets/issues/1162
> Add support for PodDisruptionBudget 

- docs/contributing-devguide.md
- docs/spec.md
- pkg/provider/onepassword/fake/fake.go
Add mocks for the new methods in the upgraded 1Password/connect-sdk-go client. Also sort the mocks in the same order as the client to make this easier in the future.
Add note to docs about need for specific version of golangci-lint.
Note: not sure why `docs/spec.md` got updated when I ran `make docs`, I didn't change anything that I know of that would've caused this.
> Update fakes to implement client for 1Password/connect-sdk-go v1.4.0

- docs/snippets/full-cluster-secret-store.yaml
While testing I have found that the documentation was referencing to wrong key names:
`provider.aws.auth.secretRef.accessKeyIDSecretRef`
`provider.aws.auth.secretRef.secretAccessKeySecretRef`
> Fix keys for secretRef in CRD ClusterSecretStore

- .github/workflows/ci.yml
- .github/workflows/release.yml
cosign release below v1.8.0 will not work anymore with Fulcio (that generates the ephemeral certificates) which is our case here.
Updating to the latest release cosign installer action and default that to the latest release (v1.9.0)
cc @knelasevero
> update cosign installer action

- .github/workflows/e2e-managed.yml
This PR fixes the infracost v2 issue introduced in https://github.com/external-secrets/external-secrets/pull/1203
see managed action failure: https://github.com/external-secrets/external-secrets/runs/6993607301?check_suite_focus=true 
migration guide: https://www.infracost.io/docs/guides/actions_migration/
> fix: infracost v2 migration

- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/webhook-deployment.yaml
- deploy/charts/external-secrets/values.yaml
ESO currently offers no configuration of volumes mounted to the containers. This is a problem for certain secret providers which don't allow configuration of the Certificate Authority (e.g. GitLab https://github.com/external-secrets/external-secrets/issues/1228). In its current form, ESO cannot be used with GitLab in an internet-disconnected environment or in any environment with a custom certificate authority.
This change adds `extraVolumeMounts` and `extraVolumes` to all containers so that users can mount secrets, configMaps or any other volume they may require.
This MR contains no code changes, nor will it cause any breaking changes for existing users.
> Enable mounting of custom volumes to deployments

- pkg/provider/aws/auth/auth.go
- pkg/provider/aws/auth/auth_test.go
- pkg/provider/aws/auth/token_fetcher.go
Fixes #1251
The IRSA `eks.amazonaws.com/audience` annotation should be respected when issuing tokens. There are more like `sts-regional-endpoints` or `token-expiration` that are yet to be implemented.
> fix: respect aud annotation at IRSA

- ADOPTERS.md
Adopters list used to follow alphabetical order. A previous change
violated this convention. This commit restores the previous state
reintroducing the alphabetical order.
> Adopters list reordered to follow alphabetical order

- docs/eso-blogs.md
Updated with desc and link to new AWS Containers blog post highlighting ESO on AWS Fargate with IRSA.
[https://aws.amazon.com/blogs/containers/leverage-aws-secrets-stores-from-eks-fargate-with-external-secrets-operator/ ](https://aws.amazon.com/blogs/containers/leverage-aws-secrets-stores-from-eks-fargate-with-external-secrets-operator/ )
> Update ESO blogs to include new AWS Containers blog post

- docs/snippets/provider-aws-access.md
Just a quick fix to have the correct name in the documentation: ParameterStore
> fix aws ParamaterStore typo

- deploy/charts/external-secrets/templates/webhook-deployment.yaml
When  setting `webhook.extraMounts` or `webhook.extraVolumeMounts` while  deploying the operator or helm chart it would fail with the following message:
```
Error: YAML parse error on external-secrets/templates/webhook-deployment.yaml: error converting YAML to JSON: yaml: line 52: did not find expected key
helm.go:81: [debug] error converting YAML to JSON: yaml: line 52: did not find expected key
```
This change aligns the indentation so setting the options no longer fail.
> fix invalid YAML error when using extraVolumeMounts / extraVolumes

- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/guides-decoding-strategy.md
- docs/snippets/full-external-secret.yaml
- e2e/suites/provider/cases/common/common.go
- e2e/suites/provider/cases/vault/vault.go
- hack/api-docs/mkdocs.yml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
This is a proposed solution to implement DecodingStrategy, with some strategies available for [base64](https://datatracker.ietf.org/doc/html/rfc4648#section-4) and [base64url](https://datatracker.ietf.org/doc/html/rfc4648#section-5) encoding formats.
Current implementation defaults to `None`, in order to preserve current External Secrets behavior, as some secret values might get misconverted to base64 due to their nature (for instance, numbered values).
Fixes #920
> Implements DecodingStrategy. 

- docs/provider-kubernetes.md
- docs/snippets/full-cluster-secret-store.yaml
Solves #850
- Adds kubernetes provider to `ClusterSecretStore` example
- Removes namespace from `SecretStore` example
> docs: Adds k8s provider example to ClusterSecretStore

- docs/snippets/full-secret-store.yaml
- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/provider.go
- pkg/provider/aws/provider_test.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
This change is an adaption of [#387](https://github.com/external-secrets/external-secrets/issues/387) / [#442](https://github.com/external-secrets/external-secrets/pull/442) for AWS provider  
that should address [#491](https://github.com/external-secrets/kubernetes-external-secrets/issues/491) (which, as I get from the context, is AWS-specific)
> retryer implementation to handle throttling exceptions on AWS 

- apis/externalsecrets/v1beta1/clusterexternalsecret_types.go
- apis/externalsecrets/v1beta1/externalsecret_types.go
- apis/externalsecrets/v1beta1/secretstore_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
This should make it easier to debug configuration issues when things haven't initialised correctly.  At the moment `ClusterSecretStore` didn't really have any output displayed. 
To the other types I've added the `status` field from the `Ready` condition, this will aid debugging when there are issues.
> feat: additional columns for kubectl output

- docs/provider-azure-key-vault.md
- docs/snippets/azkv-pkcs12-cert-external-secret.yaml
This PR address the changes discussed in #1358 related to a clear example to sync Azure Key Vault certificates.
> docs: add Azure KV PKCS12 example (#1358)

- apis/externalsecrets/v1beta1/secretstore_types.go
- apis/externalsecrets/v1beta1/secretstore_vault_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
relates to: #850
This PR fixes the comments around the `CAProvider` type.
> fix: clarify CAProvider usage in struct annotations

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-service.yaml
- deploy/charts/external-secrets/templates/service.yaml
- deploy/charts/external-secrets/templates/webhook-service.yaml
- deploy/charts/external-secrets/values.yaml
- docs/guides-metrics.md
- docs/spec.md
Signed-off-by: cebidhem <cebidhem@pm.me>
Fixes https://github.com/external-secrets/external-secrets/issues/1329
This adds new flags to create metrics services for users that don't use Prometheus as a metrics scraper.
Targets are `external-secrets`, `webhook` and `certController`.
Metrics guide has been updated, the docs and the Helm README updated. Looking at the changes, seems like some docs have not been generated in previous commits, hence why they ended up in this :) 
I've run several test scenario using `helm template`.
Let me know if something is missing.
> feat(helm): adds new flags to create metrics services for other scrapers

- deploy/charts/external-secrets/README.md.gotmpl
- hack/api-docs/mkdocs.yml
This will make it so when you click the little pencil on the material site, it will direct you to the right path to edit the file. Also updated the valuesYaml default to point to main, since master doesn't exist anymore.
> :memo: update references to select "main" instead of "master"

- pkg/utils/utils.go
There is an issue when stored version is v1alpha1: the conversion webhook does not set the specified default but instead leaves it a empty string (it's just doing a json.Marshal/Unmarshal).
This is just a hotfix that ensures the correct default behavior is used (instead, it would error out). We probably should investigate if we can use the defaulter in the conversion webhook.
> fix: handle empty conversionStrategy

- docs/spec.md
- hack/api-docs/mkdocs.yml
Working towards: https://github.com/external-secrets/external-secrets/issues/1395
This PR adds the LF footer as per [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md).
> feat: add LF footer copytight

- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- deploy/crds/bundle.yaml
Fixes missing default values for ExternalSecretTarget on CRD definition described on issue #1233
> Fixes #1233

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
Fix `provisionedNamespaces` field in `Status` of `ClusterExternalSecret` keeps getting updated non-stop.
We've noticed this odd behavior in all of our `ClusterExternalSecret` objects that are replicated to hundreds of other namespaces. The `resourceVersion` keeps jumping a few dozen every second and `provisionedNamespaces` keeps getting reordered despite the items are exactly the same.
We've tested this patch in our cluster and successfully stopped the forever updating.
> Fix provisionedNamespaces status field of ClusterExternalSecret keeps getting updated non-stop

- Makefile
Work towards #1395  - this makes sure Dependency License Checks validates no "Unknown" Licenses are valid.
> Removing Unknown License from allowed licenses

- README.md
mentioning Akeyless provider in readme
> fix: re-add provider URL

- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
ConvertKeys is called in the external secrets controller
which takes care of mapping the keys.
Calling it before returning the data is a bug as it
interferes with the new rewrite feature.
Fixes #1447
> fix: remove convertKeys from aws providers

- apis/externalsecrets/v1beta1/secretstore_azurekv_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/provider-azure-key-vault.md
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_auth_test.go
This PR adds the ability to define a `environmentType` (cloud flavour). This is needed to supply slightly different configuration to the Azure sdk based on the environment type which should be used.
In particular ActiveDirectoryEndpoint and AzureKV Resource URL should be changed with each environment.
Fixes #1467
> add support for Azure USGovCloud|GermanCloud|ChinaCloud

- pkg/provider/vault/vault.go
I tried to follow the documentation of [Getting Multiple Secrets with the Vault provider](https://external-secrets.io/v0.5.9/provider-hashicorp-vault/#getting-multiple-secrets). But it was always ending in `provided path /xyz/metadata does not contain any secret`. Even though I created the required "Custom Metadata" of a particular secret as described in the docs.
I finally found out that the used service account of my kubernetes cluster, which was bound to the kubernetes authentication in Vault has a too restrictive policy. I did not cover the `list` capability for the `xyz/metadata/*` path. This is how I solved this in the end:
```diff
path "xyz/data/*" {
capabilities = ["read"]
}
+ path "xyz/metadata/*" {
+      capabilities = ["read", "list"]
+ }
```
**But**, it was pretty hard to …
> Flip order of `err` and nil `secret` variable check in `listSecrets()` function of vault provider

- cmd/root.go
- cmd/webhook.go
During our internal security scan, the webhook for external-secrets was
flagged because it supports protocol vulnerable to Sweet32
(https://sweet32.info/). In order to avoid the webhook from being
flagged, we need to restrict the TLS ciphers on controller runtime.
To do this I needed to update the dependency to 0.12.3 and some other
conflicting dependencies.
> Add webhook tls options

- .github/workflows/stale.yml
This PR adds a stale workflow that marks issues as stale after 90d and closes them after 30d.
> feat: add stale bot to close issues automatically

- e2e/suites/provider/cases/gcp/provider.go
- pkg/provider/aws/auth/auth.go
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_auth_test.go
- pkg/provider/gcp/secretmanager/auth.go
- pkg/provider/gcp/secretmanager/client.go
- pkg/provider/gcp/secretmanager/client_test.go
- pkg/provider/gcp/secretmanager/provider.go
- pkg/provider/gcp/secretmanager/workload_identity.go
- pkg/provider/gcp/secretmanager/workload_identity_test.go
This PR refactors a couple of providers to make them more readable and reusable for the upcoming generator PR.
The general approach is that a provider implementation should be structured following the `type Provider interface` and `type SecretsClient interface`.
> chore: refactor provider

- .github/workflows/ci.yml
- .github/workflows/dlc.yml
- .github/workflows/docs.yml
- .github/workflows/e2e-managed.yml
- .github/workflows/e2e.yml
- .github/workflows/release.yml
- Makefile
- go.mod
- go.sum
Run trivy when building the image in a PR. instead of explicitly defining `go-version` it is inferred from the `go.mod` file ([see docs](https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file)) - this will automatically use the latest patch version of go.
Also fixes `CVE-2022-27664`. Dependency was patched with `go get -u golang.org/x/net`
See run:
* [failing](https://github.com/external-secrets/external-secrets/actions/runs/3055094104/jobs/4927767604) (pre-fix)
* [latest job](https://github.com/external-secrets/external-secrets/actions/runs/3055294629/jobs/4928196555) :heavy_check_mark:
> feat: run scanner on pr

- .github/workflows/ci.yml
PRs from forked repos can not publish images, hence this scan fails.
> fix: run trivy only when authenticated

- cmd/root.go
- go.mod
- pkg/provider/vault/cache.go
- pkg/provider/vault/fake/vault.go
- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
This resolves #1273 by caching Vault clients and re-using existing tokens as long as they're valid. The approach is very similar to #1244, which implements something similar for the AWS provider. As in that PR, this new feature is gated behind a CLI flag: `--experimental-enable-vault-token-cache`. The only significant difference from the AWS implementation is that the cache key uses the SecretStore namespace rather than the secret namespace.
Also note that the token revocation implemented in #381 is disabled when token caching is enabled.I _think_ this is the right thing to do. We're now solving the underlying "lease leak" problem by not creating multiple token leases in the first place, which removes the need to clean them up.
Other minor changes:
* Fixed a couple of mis-named functions …
> Reuse vault client/token when possible

- pkg/provider/aws/auth/auth_test.go
- pkg/provider/aws/auth/resolver_test.go
- pkg/provider/aws/provider_test.go
- pkg/provider/azure/keyvault/keyvault_auth_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
```
> test: use `T.Setenv` to set env vars in tests

- .github/workflows/publish.yml
publish step fails on forks; This PR will skip the publish step on forked repos. It's not needed as we have e2e tests that cover the build.
> fix: skip publish on fork ci due to missing secrets

- docs/snippets/1password-secret-store.yaml
The indentation was incorrect on the website which is ultimately driven by `1password-secret-store.yaml` so this fixes the file to have the correct indentation
Error being thrown before:
```bash
Error from server (BadRequest): error when creating "secret-store.yaml": SecretStore in version "v1beta1" cannot be handled as a SecretStore: strict decoding error: unknown field "spec.provider.onepassword.auth.connectTokenSecretRef"
```
Signed-off-by: Jason Field <jason@avon-lea.co.uk>
> fix(1password): Resolve indentation issue in Store

- .github/workflows/publish.yml
- Makefile
The `main` image isn't built properly, this PR fixes that and ensures that the `docker.promote` works as expected even locally.
> fix: create main image with ubi suffix

- docs/provider/azure-key-vault.md
The wrong snippet is refrenced for managed identity authentication on azure Key Vault. This MR changes the include statement to the correct one.
> Fix snippet for MI authentication (docs)

- deploy/charts/external-secrets/templates/rbac.yaml
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
When using ClusterExternalSecret the controller needs to delete external-secret resources.
Also: never swallow errors.
Fixes #1255
> fix: allow controller to `delete` delete externalsecrets

- docs/contributing/devguide.md
- docs/guides/datafrom-rewrite.md
- pkg/provider/gitlab/gitlab.go
- pkg/provider/gitlab/gitlab_test.go
This PR implements the missing GetAllSecrets call for the gitlab provider.
This pulls in all CI/CD variables of the defined gitlab project. Afterwards the result is filtered via the configurable regex and scope.
This addresses: https://github.com/external-secrets/external-secrets/issues/1615
Signed-off-by: Dominik Zeiger <dominik@zeiger.biz>
> gitlab: getAllSecrets

- .github/workflows/publish.yml
- .github/workflows/rebuild-image.yml
This PR adds a github action that can be manually triggered to rebuild the image for a given (branch|tag|commit).
The intended use is to provide os-level patches for existing releases. We do not provide a patch guarantee for existing versions of external secrets operator - at least not for now. Rebuilds can be requested on demand through the usual channels. For context, this was requested by @IdanAdar initially.
The rebuild action rebuilds the image and creates a new tag with a timestamp suffix, e.g. `v0.6.1-1669145271`.
Succesful GHA Run: https://github.com/moolen/external-secrets/actions/runs/3526770914
Images built in above run:
```
ghcr.io/moolen/external-secrets:v0.6.1-1669148355
ghcr.io/moolen/external-secrets:v0.6.1-ubi-1669148355
```
> feat: add rebuild action

- .github/actions/e2e/action.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- Makefile
- e2e/Makefile
This PR adds a new image to offer a FIPS compliant build of ESO.
More context here: https://kupczynski.info/posts/fips-golang/
It is debatable whether or not we want to rely on `EXPERIMENT_` env vars or not :thinking: 
I exported the container image build from CI and checked if there are `boring*` symbols.
```
$ docker pull ghcr.io/external-secrets/external-secrets:v0.6.1-13.g6d5878b7-ubi-boringssl
$ docker save ghcr.io/external-secrets/external-secrets:v0.6.1-13.g6d5878b7-ubi-boringssl -o ubi-boringssl
$ tar xvf ubi-boringssl
```
> feat: fips compliant build using boringcrypto

- pkg/provider/gitlab/fake/fake.go
- pkg/provider/gitlab/gitlab.go
- pkg/provider/gitlab/gitlab_test.go
Signed-off-by: Dominik Zeiger <dominik@zeiger.biz>
> BUGFIX: gitlab: allow fallback to wildcard variable, when no environment specific value is defined

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
Two small changes:
Adressing #1725 
This improves reconciliation duration when the controller pod is restarted.
Previously, the `status` update is patched every time even if the controller didn't do anything at all.
This PR defers the status update after the controller has examined if an update is needed.
More info in this comment: https://github.com/external-secrets/external-secrets/issues/1725#issuecomment-1326873699
<summary>
loadtest setup snippet
<details>
This script creates 1 CES with 1000 ES pointing to it.
Then restart controller and see how long it takes to reconcile all resources.
```bash
#!/usr/bin/env bash
helm upgrade --install prometheus prometheus-community/kube-prometheus-stack
helm upgrade --install foobar ./deploy/charts/external-secrets/ \
--set …
```
> fix sync calls metrics & defer patch status

- docs/provider/google-secrets-manager.md
I wasted a couple of hours to figure out that this documentation only works with the correct roles attached to the GCP Service account as described here:  https://stackoverflow.com/a/63240340
Adding a hint to the docs could make it more accessible for others.
Signed-off-by: Jakob Kolb <jakob.j.kolb@gmail.com>
> Add note on required Service Account roles.

- .github/workflows/e2e-managed.yml
- .github/workflows/e2e.yml
add `checks:write` permissions to allow updating the status check.
the e2e test permissions are broken, currently. they run but they do not update the GitHub status check in the PR.
> fix: e2e permissions

- .github/PAUL.yaml
With recent changes in the documentation, the URLs have changed and links need to be replaced.
> fix: replace bad URLs

- .github/workflows/dlc.yml
- Makefile
relates to: https://github.com/external-secrets/external-secrets/issues/1820
chore: add fossa check to CI to ensure License compatibility.
Note: we need to investigate MPL compatilibity with CNCF; all `github.com/hashicorp/*` dependencies use MPL-2.0 :sweat: 
Working towards: https://github.com/cncf/toc/issues/882
> feat: add fossa check

- pkg/provider/gitlab/fake/fake.go
- pkg/provider/gitlab/gitlab.go
- pkg/provider/gitlab/gitlab_test.go
Addresses mostly issue(s) raised in https://github.com/external-secrets/external-secrets/issues/1837
Currently when using FindName with an environmentScope on the store, upon retrieving secrets from gitlab those with wildcard will be filtered out. This should fix this.
Also addresses that variables outside gitlab's default response page size were never imported.
Signed-off-by: Dominik Zeiger <dominik@zeiger.biz>
> gitlab: Fallback to wildcard variables and use pagination (bugfix)

- docs/introduction/stability-support.md
- e2e/suites/provider/cases/gcp/gcp.go
- e2e/suites/provider/cases/gcp/provider.go
- pkg/controllers/secretstore/common.go
- pkg/provider/gcp/secretmanager/auth.go
- pkg/provider/gcp/secretmanager/client.go
- pkg/provider/gcp/secretmanager/provider.go
- pkg/provider/gcp/secretmanager/workload_identity.go
- pkg/provider/gcp/secretmanager/workload_identity_test.go
This PR allows using referent auth with the gcp provider. Towards #961 
TODO:
> feat: referent auth for gcp

- .github/actions/e2e-managed/action.yml
- .github/workflows/e2e-managed.yml
fixes CI in this PR: https://github.com/external-secrets/external-secrets/issues/1902
GHA: https://github.com/external-secrets/external-secrets/actions/runs/3900100494/jobs/6660393056
during e2e-managed we encounter an error when trying to access the GKE cluster:
```
./run.sh
Kubernetes cluster:
[...]
"https://34.79.53.178/api?timeout=32s": getting credentials: exec: executable gke-gcloud-auth-plugin not found
It looks like you are trying to use a client-go credential plugin that is not installed.
To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
Install gke-gcloud-auth-plugin for use with kubectl by following …
```
> fix: explicitly use new kubectl gcp auth

- pkg/provider/gcp/secretmanager/auth.go
- pkg/provider/gcp/secretmanager/workload_identity.go
https://github.com/external-secrets/external-secrets/issues/1901
This PR fixes the issue by calling `workloadIdentity.Close` because it seems not to be called from anywhere.
Then, I confirmed that `go_goroutine` did not increase on applying an `ExternalSecret` CR to my GKE cluster.
> fix: prevent goroutine leak on workload identity reconciliation

- docs/provider/aws-parameter-store.md
The policy from the documentation didn't work for me when using AWS Parameter Store as a `ClusterSecretStore`. I'm running ESO (v0.7.2) on EKS, using credentials from IRSA, and I was getting the following error:
```
AccessDeniedException: User: arn:aws:sts::<>:assumed-role/external-secrets-dev/external-secrets-provider-aws is not authorized to perform: ssm:GetParameter on resource ...
```
I fixed it by adding the `ssm:GetParameter` permission on my policy.
- Updated IAM policy for AWS Parameter Store provider
> Update docs for AWS Parameter Store provider

- pkg/provider/azure/keyvault/keyvault_test.go
- pkg/provider/gcp/secretmanager/provider.go
Our organisation requires us to scan all third-party applications that we use for inclusive language, and where possible provide upstream fixes for these.
If you're happy with these changes we can create more for other issues.
> chore: use more inclusive language

- pkg/provider/webhook/webhook.go
- pkg/provider/webhook/webhook_test.go
According the docs, https://external-secrets.io/v0.7.2/provider/webhook/#all-parameters, jsonpath is supposed supporting templating.
But it's not. Here an example of error:
```
{"level":"error","ts":1674265983.2843204,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"TEST/test-ext-secret3","error":"failed to get response path $.data.login.{{ .remoteRef.property }}: parsing error: $.data.login.{{ .remoteRef.property }}\t:1:14 - 1:15 unexpected \"{\" while scanning JSON select expected Ident, \".\" or \"*\"","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/tcohen/perso/gits/github.com/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_co …
```
> Support template for webhook jsonpath

- pkg/provider/webhook/webhook.go
- pkg/provider/webhook/webhook_test.go
Hello, Webhook provider doesn't support jsonpath filter correctly.
When filter is used, jsonpath return a list and not a string.
Example: 
```yaml
result:
jsonPath: "$.data.fields[?@.name==\"{{ .remoteRef.property }}\"].value"
```
With this PR, the webhook provider will try to handle list of string and get the first result of the filter.
> Add jsonpath filter support to webhook

- docs/provider/aws-parameter-store.md
This PR fixes the wrong IAM permissions in the Docs for the AWS Parameter Store.
It seems like the Go functions names were wrongly assumed to be the IAM permissions.
> Fix wrong IAM permissions in docs for the AWS Parameter Store

- .github/workflows/ci.yml
- .github/workflows/rebuild-image.yml
There's no need to use cgo with go 1.19 `GOEXPERIMENT=boringcrypto`, hence this should be a simple fix for #1898.
Container built in this CI run can be run without issues:
```
ghcr.io/external-secrets/external-secrets:v0.7.2-10.g32c75c9e-ubi-boringssl@sha256:7a0d22eb5180ec75cfb00206ec33392ee10792cc68e1de5c104a250506866a1b
```
fixes #1898
> :bug: remove cgo in boringcrypto build

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/webhook-deployment.yaml
- deploy/charts/external-secrets/values.yaml
This enables to turn `ReplicaSet` revisions off completely. 
That's helpful to avoid unnecessary orphaned `ReplicaSet` objects when deploying `ExternalSecrets` operator with GitOps approach. In fact, the revision history is then reflected in the commits of the repository used for the GitOps approach.
> feat: add ability to configure `revisionHistoryLimit` in helm chart

- docs/api/externalsecret.md
The documentation was redirecting to 404 when we hit the Guides section link under https://external-secrets.io/v0.7.2/api/externalsecret/
> Fixed broken link

- docs/api/generator/acr.md
- pkg/generator/acr/acr.go
This PR fixes a bug where the ACR credentials couldn't get generated properly. 
It also adds a example on how to create a proper `.dockerconfigjson` secret.
Fixes #2007
> fix: pass tenantID correctly to acr generator

- docs/snippets/full-pushsecret.yaml
I'm simply fixing a documentation typo to improve the experience for adopters.
No related issue
I solved it by simply patching the manifest.
> fix typo in the full-pushsecret.yaml

- docs/snippets/full-pushsecret.yaml
Fixing docs for the website related to PushSecret
Fixes #...
Correcting the example yaml file according to the CRD installed in v0.7.2
> Fix for the PushSecret example docs

- docs/provider/azure-key-vault.md
Removing redundant pipe
Syntax error, likely a typo of sorts. 
N/A
Remove '|'
> Remove '|' symbol when getting secret

- .github/workflows/stale.yml
This prevents the need to continuously remove `Stale` over time, and there shouldn't be a need to close an issue if the required information is there and there is an intent to act upon it.
WRT: https://github.com/external-secrets/external-secrets/issues/987#issuecomment-1444558657
N/A
Do not mark issues as Stale when they are labeled `kind/feature`.
> feat: exempt `kind/feature` issues from going stale

- docs/api/generator/acr.md
- docs/api/spec.md
- docs/provider/keeper-security.md
- docs/snippets/generator-acr-example.yaml
- docs/snippets/keepersecurity-external-secret.yaml
docs build is broken, this PR fixes an issue: expressions like `{{ .foobar}}`  need to be escaped within a `{% raw %}` block.
> fix: docs build

- apis/externalsecrets/v1beta1/secretstore_keepersecurity_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- docs/snippets/keepersecurity-secret-store.yaml
- pkg/provider/keepersecurity/provider.go
Simplify the keeper configuration as the hostname is part of the auth string 
#2048
> remove hostname from keeper configuration

- docs/snippets/full-secret-store.yaml
The [API docs](https://external-secrets.io/v0.7.2/api/secretstore/) reference `accessKeyID` and `secretAccessKey` but looking at [SecretStore CRD](https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_secretstores.yaml), it seems the correct field names should be `accessKeyIDSecretRef` and `accessKeySecretSecretRef` respectively. 
Faced this validation error when using the example in API docs
```hcl
error: error validating "secretstore.yaml": error validating data: [ValidationError(SecretStore.spec.provider.aws.auth.secretRef): unknown field "accessKeyID" in io.external-secrets.v1beta1.SecretStore.spec.provider.aws.auth.secretRef, ValidationError(SecretStore.spec.provider.aws.auth.secretRef): unknown field "secretAccessKey" in …
```
> docs: fix auth secretRef in API docs

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/values.yaml
Adding sidecar containers to the external secrets operator.
Fixes #2072 
Implementing the value `extraContainers` allows for simply configuring additional / sidecar containers via values.yaml
> Add values for extraContainers in deployment

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/values.yaml
Better control on how pods are scheduled/improved availability.
Fixes #2083
By adding `topologySpreadConstraints` to the `deployment.yaml`
> feat(helm): add topologySpreadConstraints to helm chart

- docs/api/generator/vault.md
- docs/provider/hashicorp-vault.md
- docs/snippets/generator-vault.yaml
- hack/api-docs/mkdocs.yml
Document the Vault dynamic secrets Generator from #2074.
Note: @moolen's testing manifest from https://github.com/external-secrets/external-secrets/pull/2074#issuecomment-1460823982 used as example.
> docs: add HashiCorp Vault Generator documentation

- .github/workflows/helm.yml
- Makefile
- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/tests/__snapshot__/controller_test.yaml.snap
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
- deploy/charts/external-secrets/tests/controller_test.yaml
- deploy/charts/external-secrets/tests/crds_test.yaml
- deploy/charts/external-secrets/values.yaml
- docs/contributing/devguide.md
- docs/contributing/release.md
- hack/helm.generate.sh
Our helm chart doesn't have unit tests. In order to provide a high-quality helm chart and to spot errors and regressions early we need a proper test suite for it.
This PR also adds two small features:
1. allow to specify crd annotations with `crds.annotations` #2112 #1965 
2. allow a user to disable/remove conversion webhook - that way a user is able to install ESO without certController and doesn't need to install the CRDs seperately #1965 #1367 
The idea is to start small with a few tests to get the system going and then add more tests gradually.
See [CI Job](https://github.com/external-secrets/external-secrets/actions/runs/4388109290/jobs/7684215974):
```
make helm.test
PASS  test controller deployment	deploy/charts/external-secrets/tests/controller_test.yaml
PASS  test crds …
```
> feat: add helm unit tests

- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- docs/guides/templating.md
- docs/snippets/merge-template-v2-external-secret.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/provider/vault/vault.go
The Templating Mechanism had several issues regarding updates to the existing external Secret, or generally speaking, the ability of not being able to keep the data source with the template (essentially allowing the templating to also inject fixed values).
Fixes #1721 
Fixes #1429
Fixes #1362
This PR improves significantly the templating mechanism by also creating ManagedFields in the CreationPolicy=Owner method, which allows for a better control of individual keys lifecycle.
It also implements a new field `MergePolicy` which controls rather to keep or not the original `data`.
> Implements template MergePolicy

- docs/snippets/dashboard.json
This PR adds a variable `$datasource` to select the correct data source for the dashboard.
WRT: https://github.com/external-secrets/external-secrets/pull/2024#issuecomment-1477140201
I tested the installation with the upstream grafana helm chart and kube-prometheus:
```
$ helm upgrade --install eso --debug --wait --timeout=1m \
external-secrets/external-secrets \
--set installCRDs=true 
--set serviceMonitor.enabled=true 
--set serviceMonitor.additionalLabels.release=prometheus 
--set webhook.serviceMonitor.enabled=true 
--set webhook.serviceMonitor.additionalLabels.release=prometheus 
--set certController.serviceMonitor.enabled=true 
--set certController.serviceMonitor.additionalLabels.release=prometheus
$ helm install prometheus prometheus-community/kube-prometheus-stack
$ helm upgrade …
```
> fix: dashboard variable

- apis/externalsecrets/v1beta1/secretstore_aws_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- pkg/provider/aws/auth/auth.go
- pkg/provider/aws/auth/auth_test.go
Add support for AWS STS AssumeRole with External ID.
Fixes #[1478](https://github.com/external-secrets/external-secrets/issues/1478)
> Add support for AWS STS AssumeRole with External ID

- docs/eso-blogs.md
As advised on Slack, adding my blog post about integrating GCP Secret manager with on-premises cluster through workload identities.
> Add blog post about GCP with on-prem

- docs/introduction/getting-started.md
Seems like there is a mismatch in the actual helm default `values.yaml` and what is instructed in the Getting Started page. I described it in this issue https://github.com/external-secrets/external-secrets/issues/2209
Fixes: https://github.com/external-secrets/external-secrets/issues/2209
Related to the confusion, but doesn't actually fix: https://github.com/external-secrets/external-secrets/issues/1409
This is just a documentation update. I would like the team to be able to sign off that this is the intended behavior and not the other way around. There may have been some intention writing that in the first place.
> [Documentation] Align getting started documents CRDs with the rest of external-secrets

- pkg/provider/scaleway/provider.go
When scaleway configuration in ClusterSecretStore is validated it is checked if namespace in secret refs is set. But due to bug validation code incorrectly expects missing namespace while it on the opposite must be set.
Fixes #2246
Fix incorrect conditions in validation checks
> Fix scaleway config validation in ClusterSecretStore

- .github/workflows/helm.yml
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
This PR:
1. re-generates helm test fixtures for #2237.
2. runs helm tests when CRDs change
Root cause: The initial PR didn't change the helm chart, hence the helm tests didn't ran and the test fixtures haven't been updated as a result.
> fix: re-generate helm test fixtures

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/webhook-deployment.yaml
- deploy/charts/external-secrets/values.yaml
Currently you can't add topologySpreadConstraints to certController and webhook where as this is already possible for the external-secret app 
Fixes #...
Add optional list configuration for `topologySpreadConstraints` in the same way that's already supported for external-secret
> Add topologySpreadConstraints to certController and webhook

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/tests/__snapshot__/controller_test.yaml.snap
- deploy/charts/external-secrets/tests/controller_test.yaml
- deploy/charts/external-secrets/values.yaml
Better default securityContext for the pods, see https://github.com/external-secrets/external-secrets/issues/2207 for details
Fixes https://github.com/external-secrets/external-secrets/issues/2207
By using strong securityContext as the default values. User can still lessen the provided configuration, should the need arise.
I have been using the provided securityContexts without issue for some time, although I would appreciate someone other than me testing it as well.
> feat(helm): use good securityContext by default

- docs/api/generator/password.md
- docs/snippets/generator-password-external-secret.yaml
- docs/snippets/generator-password.yaml
The yaml provided as example for Password was broken.
I also thought it could be usefull to provide an External Secret that uses the Password from the example
> Password yaml was missing the name

- deploy/charts/external-secrets/templates/cert-controller-rbac.yaml
This PR adds missing RBAC permissions to allow `certController` to run with`--enable-leader-election=true`.
> fix: certController misses leases RBAC to enable leader election

- ADOPTERS.md
ESO is used inside VMware Tanzu, so adding the product to the adopters list.
> chore: adding VMware Tanzu to the adopters list

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/tests/__snapshot__/cert_controller_test.yaml.snap
- deploy/charts/external-secrets/tests/__snapshot__/webhook_test.yaml.snap
- deploy/charts/external-secrets/tests/cert_controller_test.yaml
- deploy/charts/external-secrets/tests/webhook_test.yaml
- deploy/charts/external-secrets/values.yaml
- hack/helm.generate.sh
This PR adds a `hostNetwork` option for the controller and certController pods. This is useful when eso must run before the CNI is available.
This PR also expands the helm unit test scope for certController and webhook.
> feat: add hostNetwork option for controller/certController in helm chart

- deploy/charts/external-secrets/templates/rbac.yaml
Having default user-facing ClusterRoles be able to CRUD group `generators.external-secrets.io`.
Fixes #2285 
Adding the appropriate rules to the ClusterRoles.
> feat: add RBAC rules for user-facing ClusterRoles

- docs/provider/hashicorp-vault.md
Hashicorp Vault PushSecret docs don't specify to set permissions for both data and metadata updates. Important distinction here.
n/a
Update docs to include mention of both data and metadata permissions
> hashicorp-vault pushsecret doc update

- apis/generators/v1alpha1/generator_vault.go
- config/crds/bases/generators.external-secrets.io_vaultdynamicsecrets.yaml
- deploy/crds/bundle.yaml
- pkg/generator/vault/vault.go
Fixes #2324 
This PR allows users to extract information from the vault response that is not in the `data` node.
In particular the `/auth/token/create` endpoint returns `null` data, but instead all information is under the `auth` node.
Docs: https://developer.hashicorp.com/vault/api-docs/auth/token
Sample vault response from `/auth/token/create`:
```json
{
"request_id": "f00341c1-fad5-f6e6-13fd-235617f858a1",
"lease_id": "",
"renewable": false,
"lease_duration": 0,
"data": null,
"wrap_info": null,
"warnings": [
"Policy \"stage\" does not exist",
"Policy \"web\" does not exist"
],
"auth": {
"client_token": "s.wOrq9dO9kzOcuvB06CMviJhZ",
"accessor": "B6oixijqmeR4bsLOJH88Ska9",
"policies": ["default", "stage", "web"],
"token_policies": ["default", "stage", "web"],
"metadata": {
"user": …
```
> feat: allow to get auth data from vault response

- docs/contributing/release.md
This PR updates the docs from recent changes in https://github.com/external-secrets/external-secrets-operator and https://github.com/external-secrets/external-secrets.
That allows us to drive a smooth release.
> chore: bump release docs

- .github/workflows/release.yml
The release asset `external-secrets.yaml` contains the wrong image and version tags: The version is always the previous version. The release assets of the latest releases `0.7.3` and `0.8.2` have been fixed manually.  
This PR automates the process so that we don't need to manually patch the release assets. Instead, before rendering the  manifests we set the correct `.version` / `.appVersion` in the helm chart.
See [fork release](https://github.com/moolen/external-secrets/releases/tag/v0.8.3) / attached [external-secrets.yaml](https://github.com/moolen/external-secrets/releases/download/v0.8.3/external-secrets.yaml) - it contains the new tag version.
> fix: generate manifests with the correct version

- docs/provider/aws-parameter-store.md
- pkg/constants/constants.go
- pkg/provider/aws/parameterstore/fake/fake.go
- pkg/provider/aws/parameterstore/parameterstore.go
Copied from #1839:
* use `GetParametersByPath` API calls to implement `dataFrom[].find`
* keep current behavior of `dataFrom[].find` as a fallback
* add docs about the different permissions required for using this
Fixes #1839 and #1066
To maintain backward compatibility I moved the original `findByname` function to `fallbackFindByName` and created a new `findByName` function that uses the `GetParametersByPathWithContext` API call.
In function `findByName`, if we receive an `AccessDeniedException` when calling GetParametersByPathWithContext `return pm.fallbackFindByName(ctx, ref)`.
This seemed like the simplest approach. 
I found while working on this that if _both_  `name` and `tags` are set in the `dataFrom` block that the tags are completely ignored. 
In this example all parameters in …
> Aws ssm parameterstore issue 1839

- e2e/suites/provider/cases/aws/parameterstore/parameterstore.go
- e2e/suites/provider/cases/aws/parameterstore/provider.go
- e2e/suites/provider/cases/aws/parameterstore/version_secret.go
- pkg/provider/aws/parameterstore/parameterstore.go
Working towards: https://github.com/external-secrets/external-secrets/issues/2330
This PR implements `remoteRef.version` for the `aws/parameterstore` provider. e2e test coverage has been added to verify we're able to pull the parameters by version.
Fixes #2330
> fix: implement parameterstore versions

- docs/introduction/stability-support.md
GCP Secret Manager compatibility with MetadataPolicy is not reflected in the Stability support page.
Simple update on docs
> 📚  Update stability-support.md

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/provider/vault/fake/vault.go
- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
Increases Test Coverage for Hashicorp Vault provider
Relates to #2320 
Currently it is not possible to generate compatible secrets in Hashicorp vault directly from Kubernetes secrets.
Adding support to Property allows this, even if it is on a  key-by-key approach.
> Adds PushSecret property compatibility with Hashicorp vault Provider

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/_helpers.tpl
- deploy/charts/external-secrets/templates/validatingwebhook.yaml
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
- deploy/charts/external-secrets/values.yaml
It is not currently possible to define a common set of labels that will be added to all objects created with the helm chart.
Fixes #2378
This PR add a new value `commonLabels` in the helm chart which allows to add the set of labels defined on it to all objects.
> feat: allow to set a common set of labels in the helm chart

- .golangci.yaml
- cmd/root.go
- pkg/controllers/pushsecret/psmetrics/psmetrics.go
- pkg/controllers/pushsecret/pushsecret_controller.go
- pkg/controllers/pushsecret/pushsecret_controller_test.go
- pkg/controllers/secretstore/clustersecretstore_controller.go
- pkg/controllers/secretstore/cssmetrics/cssmetrics.go
- pkg/controllers/secretstore/secretstore_controller.go
- pkg/controllers/secretstore/ssmetrics/ssmetrics.go
- pkg/controllers/secretstore/suite_test.go
Add reconcile_duration metrics for the following three controllers. I'd like to add other metrics as well once this PR has been merged. Thank you for your review!
1. StoreReconciler
2. ClusterStoreReconciler
3. PushSecretReconciler
Relates to https://github.com/external-secrets/external-secrets/issues/2151
Add the metrics to the controllers.
> Add reconcile_duration metrics

- pkg/controllers/clusterexternalsecret/cesmetrics/cesmetrics.go
- pkg/controllers/clusterexternalsecret/cesmetrics/cesmetrics_test.go
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/clusterexternalsecret/util.go
SSIA. I've added a status condition metric similar to the one for the external secret controller. Thanks for your review!
Relates to https://github.com/external-secrets/external-secrets/issues/2151
Add a new metric.
> Add status_condition metric for ClusterExternalSecret

- .github/workflows/ci.yml
- Makefile
- pkg/controllers/externalsecret/suite_test.go
I've noticed when I run `make test`, the task filed with the following error message.
```
[FAILED] in [BeforeSuite] - /Users/shuheiktgw/Projects/external-secrets/external-secrets/pkg/controllers/webhookconfig/suite_test.go:69 @ 06/03/23 17:03:53.923
<< Timeline
[FAILED] Unexpected error:
<*fmt.wrapError | 0xc0003f8800>:
unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
{
msg: "unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
err: <*fmt.wrapError | 0xc0003f87e0>{
msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file …
```
> Fix the test Make task

- cmd/webhook.go
I was working on #2394 and was having an issue where the webhook would exit without error. I set the `--check-interval=10s` to make sure I was validating my certs correctly and noticed the program exited without an error and actually said "certs are valid" which was not correct.
```
<Start of Logs>
{"level":"info","ts":"2023-06-06T23:50:35Z","logger":"setup","msg":"validating certs"}
{"level":"info","ts":"2023-06-06T23:50:36Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
...
{"level":"info","ts":"2023-06-06T23:50:45Z","logger":"setup","msg":"validating certs"}
{"level":"info","ts":"2023-06-06T23:50:45Z","logger":"setup","msg":"certs are valid"}
...
{"level":"info","ts":"2023-06-06T23:50:45Z","msg":"Wait completed, proceeding to …
```
> Fix exit with no error when cert violates lookahead

- docs/snippets/dashboard.json
Fixes #2301
This PR adds the SLIs [documented here](https://external-secrets.io/v0.8.3/api/metrics/) to the dashboard.
It shows:
* reconciler error rate per CRD (including SecretStore)
* webhook error rate + latency
* reconciler total error rate and total latency
* table of ExternalSecrets that are in `Ready=false` state
There are no metrics for SecretStore conditions, hence we can not draw a table with the failed SecretStores as requested in #2301. This could be a great enhancement - though out of scope.
> feat: add SLIs to dashboard

- Makefile
Currently, `make fmt` discards errors raised from the golangci-lint, but that makes it really difficult to tell if the command ran successfully or not. In my case, the command actually failed due to https://github.com/golangci/golangci-lint/issues/3338, and the code was not fully formatted,  but I haven't noticed it a while since the command does not show the error messages. I'm not too sure why they need to be suppressed in the first place, but I believe it is more developer-friendly to show the messages.
None
Show the error messages.
> Stop discarding golangci-lint errors

- apis/externalsecrets/v1beta1/secretstore_doppler_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
- deploy/crds/bundle.yaml
- docs/provider/doppler.md
Adding support for a new `lower-kebab` name transformer to the Doppler provider.
> Add lower-kebab name transformer to Doppler provider

- e2e/Dockerfile
- e2e/Makefile
Fixes #2409. Not sure if this is a direction you want to go, but those changes allow me to run E2E tests locally (using an Apple M1 machine).
> Fix E2E test setup on non-linux machines

- hack/api-docs/Makefile
- hack/api-docs/requirements.txt
When we run `make reviewable`, it runs `make docs` and fails with the following error message.
```
error: error getting config 'user.name'
```
It seems [mike](https://github.com/jimporter/mike) needs to access the git configurations, but since we don't usually set the configs project-wise, it fails. People typically use the global git configurations which reside in ~/.gitconfig, so I'd like to mount it when we run mike to improve DX. Thanks for your review!
N/A
Mount  ~/.gitconfig when we run `make docs`
> Mount ~/.gitconfig when running make docs

- docs/guides/security-best-practices.md
SSIA. Thanks for your review!
N/A
When I ran `make reviewable`, I received the following warning message, so I fixed it.
```
WARNING  -  Documentation file 'guides/security-best-practices.md' contains a link to '../introduction/stability-support.md' which is not found in the documentation files.
```
> Fix a broken link in docs/guides/security-best-practices.md

- pkg/controllers/secretstore/clustersecretstore_controller.go
- pkg/controllers/secretstore/common.go
- pkg/controllers/secretstore/cssmetrics/cssmetrics.go
- pkg/controllers/secretstore/metrics/metrics.go
- pkg/controllers/secretstore/metrics/metrics_test.go
- pkg/controllers/secretstore/secretstore_controller.go
- pkg/controllers/secretstore/ssmetrics/ssmetrics.go
- pkg/controllers/secretstore/util.go
SSIA. I've added the status condition metrics to the secret/cluster secret controller. Thank you for your review!
Closes https://github.com/external-secrets/external-secrets/issues/2151
Add new metrics to the controllers.
> Add status_condition metrics for the secret store controllers

- .github/workflows/release.yml
The changelog and release process isn't correct: when invoked from a branch `release-0.8` it places the git tag on the `main` branch and the changelog is generated from `main` as well..
This PR attempts to fix this.
> fix: gen changelog and tags from the right branch

- .github/workflows/helm.yml
helm release isn't triggered on `release-*` branches. This PR fixes that.
tested here: https://github.com/external-secrets/external-secrets/actions/runs/5350381790/jobs/9702906525
as a result we have a release: https://github.com/external-secrets/external-secrets/releases/tag/helm-chart-0.8.4
> fix: run helm release on release branch as well

- apis/externalsecrets/v1beta1/clusterexternalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- deploy/crds/bundle.yaml
SSIA. It seems some of the JSON paths were incorrect, and `kubectl get clusterexternalsecret.external-secrets.io/xxx` does not show anything for the `Store`, `Refresh Interval`, and `Status` columns. Thank you for your review!
N/A
Fix the JSON paths.
> Fix ClusterExternalSecret printcolumns

- .github/PAUL.yaml
I'm delighted to welcome @shuheiktgw as a maintainer to the project :tada: 
As per [GOVERNANCE.md](https://github.com/external-secrets/external-secrets/blob/main/GOVERNANCE.md#maintainers):
> New maintainers must be nominated by an existing maintainer(e.g. via https://github.com/external-secrets/external-secrets/pull/1591) and must be elected by a supermajority of existing maintainers
The math has spoken: we'll need 4 approvals on this one :pray: :rocket: 
@gusfcarvalho @knelasevero @IdanAdar @moolen @sebagomez
> feat: add @shuheiktgw as maintainer :tada:

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/values.yaml
- docs/api/metrics.md
The `values.yaml` of the helm-chart contains values, which are no longer used.
Fixes #2466 
This PR removes obsolete values from the helm-chart since the corresponding templates have been deleted in [!2136.](https://github.com/external-secrets/external-secrets/pull/2136).
```
$ grep -R "webhook.serviceMonitor" .
./docs/api/metrics.md:The External Secrets Operator exposes its Prometheus metrics in the `/metrics` path. To enable it, set the `serviceMonitor.enabled` Helm flag to `true`. In addition you can also set `webhook.serviceMonitor.enabled=true` and `certController.serviceMonitor.enabled=true` to create `ServiceMonitor` resources for the other components.
./deploy/charts/external-secrets/README.md:| webhook.serviceMonitor.additionalLabels | object | `{}` | Additional labels | …
```
> Remove unused values from helm chart

- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
Vault provider has a code path where it returns `nil, nil`. This results in empty secret values, which shouldn't be the case.
This behaviour currently isn't covered by tests, and AFAIK it isn't triggered by a code path with "regular" kv engine usage.
This bug surfaced, when using SecretStore `spec.provider.vault.version=v1` when vault kv actually runs with `v2`.
Repro case:
```sh
helm install vault hashicorp/vault \
--set "server.dev.enabled=true" --set injector.enabled=false
vault secrets enable -version=1 kv
vault kv put kv/my-secret my-value=s3cr3t
```
Sync secret with ESO. This should work.
```yaml
metadata:
name: vault-backend
spec:
provider:
vault:
server: "http://localhost:8200"
path: "kv"
version: "v1" # <-- 
auth: …
```
> fix: vault deletionPolicy

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/values.yaml
Unlike `ClusterExternalSecret` and `ClusterStore` that have both CRD installation toggles and processing toggles in the helm chart, `PushSecret` has only the CRD installation toggle. 
Fixes #2471
Add the processing toggle, same as the one for the cluster resources to the helm chart.
> Add processPushSecret key

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
- pkg/controllers/clusterexternalsecret/suite_test.go
- pkg/controllers/clusterexternalsecret/util.go
While working on https://github.com/external-secrets/external-secrets/pull/2490, I noticed the tests for ClusterExternalSecretController were too complicated and thin. So before updating the controller, I've decided to refactor the tests first. Here are some of the problems I've addressed.
- There were too many "knobs" in a test case. For example, for setting up test cases, it had three similar functions, `setup`, `preTest`, and `beforeCheck`, and we needed to read all of them to understand what the test case was trying to achieve.
- Each test case had its own check functions, `checkCondition`, `checkClusterExternalSecret`, and `checkExternalSecret`, but they often are repetitive and checked only part of the resources.
IMHO, there are only two types of information we need for testing: …
> Refactor ClusterExternalSecretController tests

- docs/provider/delinea.md
Just a small addition to the docs which I overlooked in PR #2415.
> Highlight that `property` field must be set for DSV secret

- pkg/controllers/externalsecret/externalsecret_controller.go
ExternalSecrets Controller has the same problem with https://github.com/external-secrets/external-secrets/pull/2504. but in this case, we cannot replace `v1.Secret` with `metav1. PartialObjectMetadata` since [the controller needs to access a non-metadata field to compute a hash](https://github.com/external-secrets/external-secrets/blob/0bfc31addcb95a4aa8e1023cd4f74a546c54d483/pkg/controllers/externalsecret/externalsecret_controller.go#L544). Therefore, I just deleted the `builder.OnlyMetadata` option to remove the unnecessary metadata cache 🙂 
N/A
Deleted the unnecessary `builder.OnlyMetadata` option.
> Remove builder.OnlyMetadata

- hack/api-docs/Dockerfile
- hack/api-docs/Makefile
- hack/api-docs/requirements.txt
Latest cython 3.0 breaks pyyaml 6.0. Installation fails with: `AttributeError: cython_sources`
Cython 3.0 is in beta at the moment and this needs to be fixed upstream.
See upstream issue: https://github.com/yaml/pyyaml/issues/601
Latest jobs failing on main:
https://github.com/external-secrets/external-secrets/actions/runs/5578892196/jobs/10193698145
https://github.com/external-secrets/external-secrets/actions/runs/5578892208/jobs/10193703882
Note: 5.3.1 is susceptible to [CVE-2020-14343](https://www.cvedetails.com/cve/CVE-2020-14343/), however this is not relevant as we have a completely static site, which doesn't render any code dynamically. 
Unfortunately we can not bump to `5.4+`, because the same error surfaces as described above.
> fix: downgrade pyyaml <6.0

- .github/workflows/ci.yml
- Makefile
Right now, developers need to install tools such as setup-envtest, or golangci-lint explicitly before running some commands, but it would improve the developer experience if we could handle the installation more implicitly. To achieve that, I've updated the Makefile to install the tools automatically if necessary 🙂 
N/A
Install the tools automatically
> Install tools implicitly

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
- pkg/controllers/clusterexternalsecret/util.go
I've spotted a few more problems with Cluster External Secrets Controller, so I fixed them.
1. Stop ignoring an error from `r.Get(ctx, req.NamespacedName, &clusterExternalSecret`
2. Set an appropriate `mutateFunc` for `ctrl.CreateOrUpdate(ctx, r.Client, externalSecret, mutateFunc)`
I'll follow them up by the comments 🙂 
N/A
Fix them up!
> Fix CES problems

- deploy/charts/external-secrets/templates/webhook-poddisruptionbudget.yaml
Unneeded whitespace is tripping yaml linter
> Fixed potential linting issue on webhook pdb manifest

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/tests/__snapshot__/cert_controller_test.yaml.snap
- deploy/charts/external-secrets/tests/cert_controller_test.yaml
- deploy/charts/external-secrets/values.yaml
* when defining certController.prometheus.service.port the port is not automatically set on certController args, we need an extra step by using certController.extraArgs. This simplify the change of the port for metrics.
* The readiness probe of certController should be configurable
N/A
I have made some change in helm to support both.
> helm: Add certController readiness port configuration and link prometheus.service.port to args

- docs/provider/ibm-secrets-manager.md
- docs/snippets/ibm-external-secret-with-metadata.yaml
* Move examples added in 3ab04767a59d811be2f35603b88ddefcbf665989 to a snippet so they do not conflict with the mkdocs-macros plugin
The [IBM Secrets Manager provider](https://external-secrets.io/main/provider/ibm-secrets-manager/) documentation page fails to render on `main` due to curly braces in the file being parsed by mkdocs.
Fixes [#2563](https://github.com/external-secrets/external-secrets/issues/2563)
Move examples added in 3ab04767a59d811be2f35603b88ddefcbf665989 to a snippet so they do not conflict with the mkdocs-macros plugin
> IBM Provider: Fix documentation templating errors

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
I've refactored CES tests in https://github.com/external-secrets/external-secrets/pull/2499, but [one of them seems to have been flaky as a result](https://github.com/external-secrets/external-secrets/actions/runs/5635494885/job/15266559989?pr=2527), so I fixed it 🙇 
The problem was that we used to create an external secret in the before-check section. However, depending on the reconciliation loop, a cluster external secret generates a child external secret with the same name before we create it in the before check. To fix the problem, I changed the test to prepare an external secret before creating a cluster external secret.
N/A
Fix the resource creation order
> Fix flaky ClusterExternalSecret test

- hack/api-docs/Dockerfile
- hack/api-docs/Makefile
Since [we updated the base alpine image](https://github.com/external-secrets/external-secrets/commit/c76477550876bf466bbe5cd54bdbbe748b1dcea6), I started receiving the following error when I ran `make reviewable`.
```
I0730 10:13:05.825442   30896 main.go:167] written to /Users/shuheiktgw/Projects/external-secrets/external-secrets/hack/api-docs/../..//docs/api/spec.md
mkdir -p /Users/shuheiktgw/Projects/external-secrets/external-secrets/hack/api-docs/../..//site
docker run \
--mount type=bind,source=/Users/shuheiktgw/Projects/external-secrets/external-secrets/hack/api-docs/../../,target=/repo \
--sig-proxy=true \
--rm \
--user 502:20 \
--env "GIT_COMMITTER_NAME=xxx" \
--env "GIT_COMMITTER_EMAIL=xxx" \
github.com/external-secrets-mkdocs:latest \
/bin/bash -c "cd /repo && mike deploy …
```
> Disable Git top-level directory owner check

- pkg/provider/ibm/provider.go
Fix nil pointer exceptions when fetching a property not available in the secret.
Way of accessing the properties has changed in the latest Secrets Manager provider sdk v2, and ESO has been updated accordingly: https://github.com/external-secrets/external-secrets/pull/2254.
However, customer reported nil pointer exceptions and ESO crashing when accessing properties not available in the secret.
This PR converts the fetched secret to a map and then handles accessing the properties. This is similar to that of how it was accessed prior to the sdk update (https://github.com/external-secrets/external-secrets/blob/1cf7c3a6e31d699c78d0034810a5db21a871e249/pkg/provider/ibm/provider.go#L214-L217)
Based on the current changes in PR, when a non-existing `private_key` property is provided in the …
> IBM Provider: convert the fetched secret to map to access the properties

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
Orphaned secrest logic currently causes merge policy to be in a race condition. See https://github.com/external-secrets/external-secrets/pull/1389#issuecomment-1668276423
> Fix orphaned secrets logic with CreationPolicy=Merge

- docs/snippets/dashboard.json
This PR adds a variable $datasource to select the correct data source for the dashboard.
This issue was reintroduced in https://github.com/external-secrets/external-secrets/pull/2360
after first being fixed in https://github.com/external-secrets/external-secrets/pull/2153
Update the dashboard to contain the correct variable
> Fix grafana dashboard $datasource

- pkg/controllers/externalsecret/externalsecret_controller.go
In https://github.com/external-secrets/external-secrets/pull/2505, I removed the builder.OnlyMetadata, but as a result the operator started consuming much more memory. What I didn't understand was
1. [Owns](https://github.com/external-secrets/external-secrets/blob/aea53bc40723ec77ee6b11c92c88ec3b93575496/pkg/controllers/externalsecret/externalsecret_controller.go#L607) caches all the resources regardless of owner reference.
2. The operator [disables Secret cache](https://github.com/external-secrets/external-secrets/blob/e5fd5a90a9129194d97a566918f1b3cd328e3616/cmd/root.go#L112).
I found [a related PR](https://github.com/external-secrets/external-secrets/pull/729). Currently, we cannot disable cache for the `Owns`, so specifying the builder.OnlyMetadata makes sense since we don't really …
> Set builder.OnlyMetadata back for Secrets

- docs/provider/google-secrets-manager.md
https://external-secrets.io/v0.9.3/provider/google-secrets-manager/#creating-external-secret
`kubectl get secret secret-to-be-created -n <namespace> | -o jsonpath='{.data.dev-secret-test}' | base64 -d`
This command does not work. The first '|' in the command is unnecessary.
N/A
I skipped creating an issue since it was just a typo correction.
I removed the unnecessary '|' from the command to make it work properly.
I believe we can skip running tests since it's just a typo correction in the documentation.
> Fix a command in Google Cloud Secret Manager document

- docs/examples/bitwarden.md
- docs/snippets/bitwarden-secret-store.yaml
- docs/snippets/bitwarden-secret.yaml
Example on how to use a Bitwarden note entry as a multiline secret in Kubernetes.
none
Example on how to use a Bitwarden note entry as a multiline secret in Kubernetes.
> Using Bitwarden notes for multiline secrets

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
In https://github.com/external-secrets/external-secrets/pull/2504, I switched to using PartialObjectMetadata to get an ExternalSecret.  However, the operator already cached every ExternalSecret, and using builder.OnlyMetadata for ExternalSecrets builds another cache, which is wasteful. So I simply removed the option and changed it to get an ExternalSecret. Thank you for your review 🙇 
N/A
Stop using the builder.OnlyMetadata option for ExternalSecrets.
> Stop using builder.OnlyMetadata for ExternalSecrets

- pkg/controllers/externalsecret/externalsecret_controller.go
While reading the source code, I noticed the External Secret Controller mistakenly ignored an error, so I fixed it to return the received error to retry reconciliation! Thank you for your review 🙂 
N/A
Stop ignoring an error.
> Stop ignoring ExternalSecret reconciliation error

- pkg/controllers/clusterexternalsecret/cesmetrics/cesmetrics.go
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/secretstore/clustersecretstore_controller.go
- pkg/controllers/secretstore/cssmetrics/cssmetrics.go
- pkg/controllers/secretstore/secretstore_controller.go
- pkg/controllers/secretstore/ssmetrics/ssmetrics.go
The details are described in [the issue](https://github.com/external-secrets/external-secrets/issues/2542), but it would be great if we remove metrics when a parent metric has been deleted, or the Operator keeps reporting stale values. Also, it helps reduce the number of metrics users receive.
ExternalSecret Controller takes a different approach and sets the condition deleted instead of deleting the metrics themselves. The benefit of the approach is that metric collectors are more likely to be able to pull metrics before they get deleted (even though it keeps reporting the same gauge metrics until the Operator restarts or the leader changes, which I think is wasteful). I'm not too sure which approach we should take here, so I'd like to know what others think 🙂 
Thank you for your review! …
> Remove metrics when a resouce is deleted

- apis/externalsecrets/v1beta1/clusterexternalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
The ClusterExternalSecret controller has a bug that when ExternalSecretName has changed, it creates a new ExternalSecret and leaves the old resource as is. We should delete the old one when the name has changed.
N/A
Clean up the old ExternalSecrets when the name has changed.
> Delete old ClusterExternalSecrets when name changed

- Makefile
- docs/contributing/devguide.md
- docs/snippets/full-secret-store.yaml
- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
Hashicorp vault sdk supports retry attempts/interval, but those are not bound to the `{Cluster,}SecretStore` ones, bind them.
More about the actual use case, I have many secrets set at a 1m interval, and I see rare failures in syncing due to vault internal errors.
Those failures are transmitted to Argocd via the ES status and then to humans via email, I want to see if setting the retry amount to 1 or 2 (up from effectively 0) solves it.
I opened no issue, tell me if I need to.
Make it so the `SecretStoreSpec.retrySettings` are actually passed to the vault provider implementation.
Also update the documentation.
It's my first time writing anything in go, it was not easy to set everything up and get this done, please advise if the code has issues.
I've tested the image in a real cluster for …
> Introduce RetrySettings support for Hashicorp Vault

- .github/workflows/ci.yml
- Makefile
- docs/introduction/stability-support.md
This PR bumps the Kubernetes version used in CI and documents it in the "supported versions" docs.
> bump Kubernetes support version

- terraform/aws/modules/cluster/main.tf
This PR bumps the EKS version to 1.27 in our `e2e-managed` tests to match the Kubebuilder tests in the CI pipeline and the e2e tests. 
Note: GKE version will be set to the most recent official release (1.27 at this point in time)
During e2e-managed tests i checked the version of the spun up cluster:
> chore: bump EKS e2e test version

- pkg/provider/scaleway/client.go
- pkg/provider/scaleway/fake_secret_api_test.go
- pkg/provider/scaleway/secret_api.go
Scaleway will soon refacto its Secret Manager API and deprecate the endpoints `GetSecretByName` and `GetSecretVersionByName`. The goal is to use the `ListSecrets` endpoint instead and to filter by name.
No issue related.
As stated in the problem section, I replaced the calls to use `ListSecrets` inatead.
> Refacto scaleway provider

- docs/provider/hashicorp-vault.md
- docs/snippets/vault-pushsecret.yaml
The utilization of the parameter `property` for the `PushSecret` in the Hashicorp Vault provider was not properly documented.
Related to #2320
Improve specific documentation for Hashicorp Vaut providers.
⚠️ Don't document the parameter in the API section as it is not supported in all providers.
> Docs: Improve Hashicorp Vault PushSecret documentation

- deploy/charts/external-secrets/templates/servicemonitor.yaml
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
- deploy/charts/external-secrets/tests/service_monitor_test.yaml
When using the `external-charts` with the kube-prometheus-stack, it leads to issues with the missing CRD and throws error message as displayed in the issue.
Fixes #2547 
Adding an additional check which checks that "monitoring.coreos.com/v1" is available when creating the serviceMonitor helm charts
- [ x I ensured my PR is ready for review with `make reviewable`
> feat: Updated check ServiceMontior check to include APIVersions check for  helm charts

- docs/snippets/gitops/deployment.yaml
I was following the [official docs](https://external-secrets.io/latest/examples/gitops-using-fluxcd/) to install External Secrets via Flux, when I ran into the following error.
```
E0919 16:44:23.502828       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ExternalSecret: failed to list *v1alpha1.ExternalSecret: conversion webhook for external-secrets.io/v1beta1, Kind=ExternalSecret failed: the server could not find the requested resource
```
The problem is, the examples in the docs are having you install a very old version of External Secrets. Once upgraded, everything works perfectly. Just bumping the version so future flux users dont run into the same problem I did.
> Update Flux example to  0.9.4

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller.go
If the `DeletionTimestamp` is set on an `ExternalSecret` or `ClusterExternalSecret` the reconciliation should stop and not recreate a deleted `Secret`. For details see issue #2176
Fixes #2176
Check for `DeletionTimestamp` != `nil` in reconciliation loop.
> fix: do not recreate secret if deletion timestamp is set

- pkg/controllers/commontest/common.go
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
The problem is described in the issue but in short, users cannot remove labels/annotations from secrets once they set. This is because right now we just merge all the labels/annotations to the Secret metadata every time the controller reconciles a resource.
- https://github.com/external-secrets/external-secrets/blob/9559c2a124ede009a6d649b36ff3f3ed57cd9fb4/pkg/controllers/externalsecret/externalsecret_controller_template.go#L205-L221
Fixes https://github.com/external-secrets/external-secrets/issues/2682
Currently, the controller merges labels/annotations manually, but we don't have to do that since the server-side apply merges those fields if necessary. So instead of merging them manually, let the Kubernetes API handle it.
> Let ManagedField handle metadata

- docs/snippets/full-cluster-secret-store.yaml
Add namespace to secretRef.privatekey and secretRef.fingerprint in oracle provider example at full-cluster-secret-store.yaml to avoid confusion like in #2727
There is a necessary property that is not included in the example of ClusterSecretStore for oracle provider
Would avoid issues like #2727
Just adding the missing necessary property in the example
> Complement full-cluster-secret-store oracle provider example

- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
`make helm.test` started failing since we merged https://github.com/external-secrets/external-secrets/pull/2591, so I've updated the test to fix the problem
N/A
> Fix helm.test by reflecting recent changes

- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
SSIA
Fixes https://github.com/external-secrets/external-secrets/issues/2713
> Reflect certController.readinessProbe.port to readinessProbe

- docs/provider/google-secrets-manager.md
- docs/snippets/gcpsm-wi-secret-store.yaml
Found that documentation could be more clear with GCP clusterLocation parameter.
#2740
Added some lines just to emphasize the proper use of the parameter because the current example can be confusing.
- [ X ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ X ] All commits are signed with `git commit --signoff`
- [ X ] My changes have reasonable test coverage
- [ X ] All tests pass with `make test`
- [ X ] I ensured my PR is ready for review with `make reviewable`
> doc: add more info for clusterLocation parameter in gcp

- docs/provider/scaleway.md
- pkg/provider/scaleway/client.go
- pkg/provider/scaleway/client_test.go
- pkg/provider/scaleway/fake_secret_api_test.go
The scaleway provider now supports referencing secrets by path.
No related issues.
This PR adds the path support in the Scaleway provider implementation. It is now possible to use `path:` to reference a secret to get or push it.
> Scaleway secret path

- docs/snippets/bitwarden-cli-deployment.yaml
Whilst implementing integration with Vaultwarden I noticed that the local vault was not being updated.
I had to add  "force=true" to the sync api call for it to work as expected.
> add force flag to bitwarden sync in bitwarden cli deployment documentation

- pkg/provider/aws/auth/auth.go
The value `session.SharedConfigDisable` prevented the AWS SDK to use the default provider chain. By removing this value from the getAWSSession function the default SDK provider chain is used. This enables the SDK to use the shared config file:
https://github.com/aws/aws-sdk-go/blob/main/aws/session/env_config.go#L84 as well as the shared credentials file:
https://github.com/aws/aws-sdk-go/blob/main/aws/session/env_config.go#L76
This fixes the code to be correct with the documentation of NewGeneratorSession which notes that it uses the authentication order:
1. service-account token.
2. static credentials.
3. sdk default provider.
See also the AWS documentation:
https://github.com/aws/aws-sdk-go/blob/main/aws/session/session.go#L158
I'm not sure why this was included initially. I've gone …
> fix: enable sharedConfigState in AWS auth provider

- pkg/provider/kubernetes/client.go
- pkg/provider/kubernetes/client_test.go
The problem is well described in the issue, so please look at it for details. In short, the ESO controller encodes secret data twice if it is in binary format.
Fixes https://github.com/external-secrets/external-secrets/issues/2745
The problem was introduced in https://github.com/external-secrets/external-secrets/pull/2681, and it changed the controller to encode binary data before marshaling it. This change is problematic since we must decode it before passing the final data to the k8s server or it will be encoded again when we create a secret.
The current client implementation is clever and it first marshals all the data into JSON and parses it using gson. However, this approach can be a problem if the original data contains unmarshalable characters such as binary. To avoid this problem, …
> Fix the k8s double encoding problem

- docs/provider/hashicorp-vault.md
- hack/api-docs/Makefile
Fixes #619
This PR mentions the `system:auth-delegator` ClusterRole which is needed for the Vault provider when using Kubernetes auth.
> docs: mention auth-delegator role in vault provider

- .golangci.yaml
- Makefile
golangci-lint is outdated and doesn't run.
Further, depguard is set, but without configuration it's almost useless. It throws too many errors.
> fix: update the linter so that it runs latest and disable debguard

- apis/externalsecrets/v1beta1/clusterexternalsecret_types.go
- apis/externalsecrets/v1beta1/zz_generated.deepcopy.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
Replicating ExternalSecrets into namespaces defined by name OR label selector.
Fixes https://github.com/external-secrets/external-secrets/issues/2804
This proposal adds `Namespaces` list to ClusterExternalSecrets similar to what is possible by conditions in ClusterSecretStore.
> feat: add namespace list selector to ClusterExternalSecrets

- pkg/controllers/externalsecret/externalsecret_controller.go
When the backend provider is slow to respond (eg: VaultDynamicSecret calling PKI issue endpoint), the `.status.refreshTime` is skewing which leads to every other refresh being skipped.
Fixes #2812
I went with the simplest solution, instead of setting refreshTime to `time.Now()` at the end of reconciliation, set it to `start`, which is initialized at the beginning of reconciliation.
> Fix skew between refreshInterval and refreshTime that can lead to skipped refresh.

- apis/externalsecrets/v1alpha1/externalsecret_types.go
- apis/externalsecrets/v1alpha1/pushsecret_types.go
- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- config/crds/bases/external-secrets.io_pushsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
I noticed some enum fields do not have validation markers and users could put wrong values accidentally. To improve usability, it would be better if we set validations to those enum fields. Thank you for your review!
None
Put `+kubebuilder:validation:Enum` markers to the enum fields.
> Add validations for the enum values

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
From setup-go@v4, it started to cache go modules and build cache by default, but we still manually cache them using actions/cache.
- https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
N/A
Let setup-go handle the caches
> Let setup-go handle go related caches

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/pushsecret/pushsecret_controller.go
- pkg/controllers/pushsecret/pushsecret_controller_test.go
Cleanup the condition handling and marking object status for external controller.
No related issue. Just a simple refactor.
> ref: cleanup condition handling for objects

- apis/externalsecrets/v1beta1/externalsecret_types.go
- pkg/provider/fake/fake.go
- pkg/provider/fake/fake_test.go
SSIA. I've added the GetAllSecrets method to the fake provider to support `dataFrom.find`.
Closes https://github.com/external-secrets/external-secrets/issues/2835
Add the GetAllSecrets method to the fake provider.
Feel free to use the following manifests to check the behavior locally 🙂 
```
kind: ClusterSecretStore
metadata:
name: fake
spec:
provider:
fake:
data:
- key: "some-key1"
value: "HELLO1V1"
version: "v1"
- key: "some-key2"
value: "HELLO2V1"
version: "v1"
- key: "some-key2"
value: "HELLO2V2"
version: "v2"
- key: "another-key"
value: "Hi"
```
```
metadata:
name: example
spec:
refreshInterval: 1h
secretStoreRef:
name: fake
kind: ClusterSecretStore
target:
name: secret-to-be-created …
```
> Support GetAllSecrets for the fake provider

- cmd/certcontroller.go
- pkg/controllers/crds/crds_controller.go
- pkg/controllers/crds/suite_test.go
- pkg/controllers/webhookconfig/suite_test.go
- pkg/controllers/webhookconfig/webhookconfig.go
In `controller-runtime`, readiness probes are being executed independently from the leader election status. The current implementation depends on leader election (client cache etc.) to run properly. This commit fixes that by short-circuiting the readiness probes when the mgr is not the leader.
This bug surfaces when leader-election=true and cert-controller replicas>=2.
Proof of work:
cert-controller runs with leader-election and multiple replicas:
> feat: fix cert-controller readiness probe

- apis/externalsecrets/v1beta1/externalsecret_validator.go
- apis/externalsecrets/v1beta1/externalsecret_validator_test.go
While working on another PR, I noticed we could create an ExternalSecret resource without the data and the dataFrom field. I believe either of them should be set, so I added validation for it. Also, I'm not a big fan of the "one validation at a time" kind of validation implementation, so I refactored it to aggregate multiple validation errors. Thank you for your review 🙂 
N/A
> Validate data or dataFrom existence

- docs/guides/common-k8s-secret-types.md
I used the original example to try to create a dockerconfigjson type secret in k8s and found that there was an extra space in the templating between the `,` and `auth`.
```
.dockerconfigjson: '{"auths":{"{{ .registryName | lower }}.{{ .registryHost }}":{"username":"{{ .registryName }}","password":"{{ .password }}", "auth":"{{ printf "%s:%s" .registryName .password | b64enc }}"}}}'
```
When the secret was finally rendered in K8s, the extra space caused the last curly brace to be removed so the secret looked something like:
```
{"auths":{"registry.gitlab.com":{"username":"<redacted>","password":"<redacted>", "auth":"<redacted>"}}%
```
instead of:
```
{"auths":{"registry.gitlab.com":{"username":"<redacted>","password":"<redacted>", …
```
> docs: remove additional space in dockercreds example that causes the last curly brace to be removed

- apis/externalsecrets/v1alpha1/pushsecret_types.go
- apis/externalsecrets/v1beta1/pushsecret_interfaces.go
- config/crds/bases/external-secrets.io_pushsecrets.yaml
- deploy/crds/bundle.yaml
- docs/guides/pushsecrets.md
- docs/snippets/full-pushsecret-no-key-no-property.yaml
- docs/snippets/full-pushsecret-no-key-with-property.yaml
- pkg/controllers/pushsecret/pushsecret_controller.go
- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/parameterstore/parameterstore_test.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/gcp/secretmanager/client.go
- pkg/provider/keepersecurity/client.go
- pkg/provider/kubernetes/client.go
- pkg/provider/kubernetes/client_test.go
- pkg/provider/oracle/oracle.go
- pkg/provider/scaleway/client.go
- pkg/utils/utils.go
This will allow pushing the whole secret to the provider which will make templating that much easier.
Related issue also https://github.com/external-secrets/external-secrets/issues/2166.
> feat: allow pushing the whole secret to the provider

- pkg/generator/vault/vault.go
- pkg/provider/delinea/client.go
- pkg/provider/ibm/provider.go
- pkg/provider/vault/vault.go
- pkg/provider/webhook/webhook.go
- pkg/provider/webhook/webhook_test.go
- pkg/utils/utils.go
This PR fixes a couple of bugs in the webhook provider:
1. webhook provider tries to coerce the type to (string) and panics
2. #2898: properly handle escaped json
3. only a small set of response payload types were supported. This PR adds support for a wider variety
4. :broom: centralize the `getTypedKey` as it was copy-pasted across providers
Fixes #2898
> fix: `webhook` support more types when parsing response

- docs/provider/azure-key-vault.md
This removes "should use aad-pod-identity" wording, see
https://github.com/external-secrets/external-secrets/discussions/2901
Mentions AAD Pod Identity is deprecated and updates overview
of supported authentication modes for Azure Key Vault.
------
Additionally, perhaps the "Workload Identity" section should be moved to the top?
> docs: Recommend use of Workload Identity for Azure Key Vault

- docs/snippets/template-v2-from-secret.yaml
I believe there's a typo in the `templateFrom` guide.
Fixes #...
This PR should address the issue.
> fix: Small typo in the 'templateFrom' guide

- docs/api/generator/acr.md
- pkg/generator/acr/acr.go
- pkg/provider/azure/keyvault/keyvault.go
The `scope` parameter used to be the ACR url `foobar.azurecr.io`, but this stopped working. Turns out that you need to use the management endpoint as `scope` in order to authenticate with ACR.
Supersedes #2403.
```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
metadata:
name: acr-gen
spec:
tenantId: xxxxxx
registry: mjeso.azurecr.io
environmentType: "PublicCloud"
auth:
workloadIdentity:
serviceAccountRef:
name: "workload-identity-sa"
---
metadata:
name: azurecr-credentials
spec:
dataFrom:
- sourceRef:
generatorRef:
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
name: acr-gen
refreshInterval: 12h
target:
name: azurecr-credentials
template:
type: …
```
> fix: ACR access token generator with Workload Identity

- docs/provider/hashicorp-vault.md
- pkg/provider/vault/vault.go
- pkg/provider/vault/vault_test.go
PushSecret is currently supported with HashiCorp Vault provider only when KV v2 backend is used. 
This is because the Vault KV v1 backend is not supporting secrets' metadata. Thus, ESO is not able to verify if secrets were originally pushed by him. 
Using PushSecret with Vault KV v1 might expose your infrastructure to a potential risk while granting the operator permissions to override secrets that were not originally created by him.
This risk is acceptable when using external security layer for managing the access permissions like Vault policies where tokens can be restricted for specific paths. 
But, since ESO should guarantee some assurance and confidence in operation with sensitive assets, supporting Vault KV v1 API without metadata validation is not acceptable.
Fixes #2549 
Enabling …
> Feat/Adding support for PushSecret using HashiCorp Vault KV v1

- pkg/provider/scaleway/provider.go
Being able to segregate queries from the Scaleway go SDK and external-secrets operator.
No related issues.
Initialize the Scaleway SDK client with a custom user agent.
> feat: add custom user agent to scaleway provider

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/values.yaml
My problem is that I am not able to set the `spec.hostAliases` field on the Pod through Helm values.
None.
I want to provide a flexible way to add extra fields to helm deployment's pod spec through Helm values.
> Helm pod spec extra

- pkg/provider/ibm/provider.go
- pkg/provider/ibm/provider_test.go
Minor changes to address the [suggested code changes](https://github.com/external-secrets/external-secrets/pull/2950#discussion_r1430154811) and fix the linting errors.
This is an extension of https://github.com/external-secrets/external-secrets/pull/2950
https://github.com/external-secrets/external-secrets/issues/2947
> Minor: extension of PR #2950 Add support for IBM Cloud Service Credentials secret type

- .github/actions/e2e-managed/action.yml
- .github/actions/e2e/action.yml
- .github/actions/sign/action.yml
- .github/workflows/helm.yml
- .github/workflows/publish.yml
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
Fixes #2969 
**AS-IS**
```yaml
echo "::set-output name=changed::true"
```
**TO-BE**
```yaml
echo "changed=true" >> $GITHUB_OUTPUT
```
> chore: replace deprecated command with environment file

- deploy/charts/external-secrets/templates/deployment.yaml
Make it possible to set processPushSecret=false when installing namespaced.
When setting .Values.scopedNamespace and .Values.scopedRBAC we want to prevent that cluster resources get evaluated.  
In this case it also leads to the else after it not beeing evaluated, where the processPushSecret is also placed.  
So currently you can only set processPushSecret=false when not using namespaced based installation. As pushsecrets are a namespaced resource this should be possible.
Fixes #...
Remove processPushSecret from the else part as standalone variable
> fix(chart): setting processPushSecret 

- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/cert-controller-poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/cert-controller-rbac.yaml
- deploy/charts/external-secrets/templates/cert-controller-service.yaml
- deploy/charts/external-secrets/templates/cert-controller-serviceaccount.yaml
Recently support was added for the webhook to use cert-manager instead of the built-in certController deployment. However, when enabling cert-manager the certController deployment must be adjusted to not deploy. 
https://github.com/external-secrets/external-secrets/issues/1965
Specifically addresses the last two comments: https://github.com/external-secrets/external-secrets/issues/1965#issuecomment-1793463232
Adds a conditional check to the certController templates that if cert-manager is enabled to not render/deploy them.
> Disable certController when certManager is enabled by webhook

- .github/workflows/helm.yml
WRT: https://kubernetes.slack.com/archives/C047LA9MUPJ/p1703281915697679
The Helm Release job fails if files in the helm chart are changed and a release already exists.
> fix: do not error if helm chart version already exists

- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
cert-manager integration breaks because of wrong value name
Fixes #...
> Fix value name

- .github/workflows/ci.yml
- codecov.yml
I'd like to try configuring Codecov again so that we can visualize and track test coverage over time.
See [the related Slack thread](https://kubernetes.slack.com/archives/C047LA9MUPJ/p1703655390563569) for the discussion.
N/A
Configure Codecov integration without blocking any PRs.
> Configure codecov

- pkg/provider/akeyless/akeyless.go
- pkg/provider/akeyless/akeyless_api.go
Akeyless Vaultless Platform supports Certificate items which are not yet supported by ESO
Adding support for Certificate items to be pulled from the Akeyless Vaultless Platform - https://docs.akeyless.io/docs/certificate-storage
> Akeyless Provider - Add support for Certificate items

- docs/api/metrics.md
Missing label in Controller Reconcile Error documentation section.
Add the `result="error"` label
> docs: update controller reconcile error rule

- docs/examples/bitwarden.md
i tried to implement this yesterday using the provided image, and it wouldn't allow me to pull it.
[i created my own here](https://github.com/charlesthomas/bitwarden-cli), using a copy/paste from these docs (with a slight modification for the purposes of CI/CD automation)
the updated image is that image, and then since i updated the version in the image, i updated it in the `Dockerfile` example, too
Fixes #...
> doc: update bitwarden-cli image & version

- docs/introduction/getting-started.md
Helm installation order is not fixed, so it may happen that the installation fails because CRDs are referenced before they are installed. The installation page docs did not mention a way to install them outside of helm.
Fixes #3020
I added the command to install the CRDs with kustomize
- [ x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ x ] All commits are signed with `git commit --signoff`
> docs: add command to install CRDs using kustomize

- SECURITY.md
- SECURITY_RESPONSE.md
This PR proposes a security incident response process / guideline just to have it in case.
This is taken from the [CNC/tag-security Project Resources](https://github.com/cncf/tag-security/blob/231b87f371274b2d68def2c6a35a719210836191/project-resources/README.md). Minor adaptations have been made.
> docs: add security response process

- SECURITY_RESPONSE.md
Follow-up of #3037, adding suggestions that were skipped due to auto-merge
> chore: fixup security response suggestions

- pkg/provider/aws/secretsmanager/fake/fake.go
- pkg/provider/aws/secretsmanager/secretsmanager_test.go
This PR adds tests for AWS Secrets Manager - `GetAllSecrets()` and `Validate()`  wasn't covered.
> chore: add tests for AWS/SM

- Dockerfile.ubi
Bump ubi image, see here: https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?image=65ba0f23eafd8883d5f22369&architecture=arm64&container-tabs=overview
> chore: bump ubi image

- .github/workflows/helm.yml
It seems the helm GitHub Actions workflow does not start when deploy/crd/bundle.yaml changes.
For example, it didn't run in https://github.com/external-secrets/external-secrets/pull/2884.
Closes https://github.com/external-secrets/external-secrets/issues/3059
Fix the paths.
> Start the helm workflow when files in deploy/crds change

- .github/workflows/ci.yml
Currently, we don't run the unit tests on the main branch, but this is a little problematic for Codecov since it implicitly relies on the main (default) branch to track the coverage over time. I'd like to run the unit tests and report the coverage to Codecov.
- https://app.codecov.io/gh/external-secrets/external-secrets
N/A
> Run unit tests on the main branch

- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
Fixing failing Helm tests for crds due to missing snaps for Chef and Pulumi.
Fixes #3153 
Adding missing snaps for both crds.
```yaml
➜  external-secrets git:(issue/3153) make helm.test            
./hack/helm.generate.sh deploy/crds deploy/charts/external-secrets
21:34:22 [ OK ] Finished generating helm chart files
PASS  test cert controller deployment  deploy/charts/external-secrets/tests/cert_controller_test.yaml
PASS  test controller deployment       deploy/charts/external-secrets/tests/controller_test.yaml
PASS  test crds        deploy/charts/external-secrets/tests/crds_test.yaml
PASS  test service monitor     deploy/charts/external-secrets/tests/service_monitor_test.yaml
PASS  test webhook deployment  deploy/charts/external-secrets/tests/webhook_test.yaml
Charts:      1 passed, 1 …
```
> issue/3153 - added missing snapshots for Pulumi and Chef crd tests

- .github/workflows/ci.yml
See [the Slack message](https://kubernetes.slack.com/archives/C047LA9MUPJ/p1708300085013439) for the details. I'll merge this PR after setting the CODECOV_TOKEN secret.
Fixes #...
> Set CODECOV_TOKEN to upload results from the upstream branches

- hack/api-docs/mkdocs.yml
Site's copyright was set as `2023`
This PR updates it to be `2024`
Fixes #...
Changing `2023` to `2024` in copyright footer
> [typo] Changing date from `2023` to `2024` in mkdocs site

- e2e/framework/addon/conjur.go
- e2e/framework/util/util.go
- e2e/go.mod
- e2e/go.sum
- e2e/k8s/conjur.values.yaml
- e2e/suites/provider/cases/conjur/conjur.go
- e2e/suites/provider/cases/conjur/provider.go
- e2e/suites/provider/cases/import.go
The CyberArk Conjur provider for ESO does not have E2E tests to verify that it works with Conjur OSS.
Fixes #...
This PR adds basic E2E tests for the GetSecret functionality, specifically with Conjur's API Key authentication (K8s JWT will be a separate PR). To do this, we added an "addon" which handles installing Conjur OSS via Helm and configuring it for the test suite.
> Conjur E2E Tests for API Key Authentication

- apis/externalsecrets/v1beta1/secretstore_conjur_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- e2e/framework/addon/conjur.go
- e2e/k8s/conjur.values.yaml
- e2e/suites/provider/cases/conjur/conjur.go
- e2e/suites/provider/cases/conjur/policy.go
- e2e/suites/provider/cases/conjur/provider.go
- pkg/provider/conjur/auth_jwt.go
- pkg/provider/conjur/conjur_api.go
- pkg/provider/conjur/provider_test.go
1. The Conjur provider for ESO supports both API Key and JWT authentication, but only the API Key authentication is included in the E2E test suite (added in #3120).
2. Conjur users are limited in the way they can integrate with ESO using Conjur's JWT authentication options. Specifically, Conjur allows either a JWT that includes the workload (pod, application) identity in one of the claims (currently supported), as well as by including the identity in the URL used to authenticate with the JWT. This latter option is not yet supported in ESO.
This is a follow up from #3120, which added the E2E tests for API Key authentication with Conjur.
This PR replaces #3185.
1. Add E2E tests to ESO that run against a Conjur OSS instance that's configured to allow JWT authentication using a Kubernetes …
> Conjur E2E Tests for K8s JWT Authentication

- docs/guides/ownership-deletion-policy.md
Supersedes https://github.com/external-secrets/external-secrets/pull/2928
Closes #2416
> docs: adds note to Lifecycle creation policy owner docs

- pkg/provider/scaleway/client.go
- pkg/provider/scaleway/fake_secret_api_test.go
- pkg/provider/scaleway/provider.go
- pkg/provider/scaleway/secret_api.go
Scaleway has published a new version of the Secret Manager API.
No related issue.
Update to the new Secret Manager API version
> Update Scaleway provider to use v1beta1 API version

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/NOTES.txt
- deploy/charts/external-secrets/templates/_helpers.tpl
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/cert-controller-poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/cert-controller-rbac.yaml
- deploy/charts/external-secrets/templates/cert-controller-service.yaml
- deploy/charts/external-secrets/templates/cert-controller-serviceaccount.yaml
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/rbac.yaml
- deploy/charts/external-secrets/templates/service.yaml
- deploy/charts/external-secrets/templates/serviceaccount.yaml
- deploy/charts/external-secrets/templates/servicemonitor.yaml
- deploy/charts/external-secrets/templates/validatingwebhook.yaml
- deploy/charts/external-secrets/templates/webhook-certificate.yaml
- deploy/charts/external-secrets/templates/webhook-deployment.yaml
- deploy/charts/external-secrets/templates/webhook-poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/webhook-secret.yaml
- deploy/charts/external-secrets/templates/webhook-service.yaml
- deploy/charts/external-secrets/templates/webhook-serviceaccount.yaml
- deploy/charts/external-secrets/values.yaml
Adding helm value `namespaceOverride` to allow multi-namespace deployments (for umbrella charts)
Add `namespaceOverride` value to `deploy/charts/external-secrets/values.yaml` and corresponding helper value to allow use self-provided namespace or default
> Add 'namespaceOverride' value for helm chart

- Tiltfile
The wrong location was used when updating `secruityContext` which prevent hot-reloading from working giving the following error:
```
tar: can't remove old file external-secrets: Read-only file system
```
This is now fix by updating the right location, which is the first `container` in the deployment.
It could be something like :
```python
for container in o['spec']['template']['spec']['containers']:
if container['name'] in ['external-secrets', 'webhook', 'cert-controller']
```
But honestly, we'll change the container name first, before we ever introduce a second container, I think. :)
Fixes #...
> fix: location of secruity context when updating deploying using Tilt

- pkg/provider/onepassword/fake/fake.go
- pkg/provider/onepassword/onepassword.go
- pkg/provider/onepassword/onepassword_test.go
This PR adds waits for values to be updated and created from 1Password's side. It's a workaround on the fact that 1Password lags a bit behind when it updates and creates values while the call returns immediately.
Making the next call create the same value again instead of updating an existing value.
Eventually, Bulk operations should be created for PushSecrets but that is a huge chunk of work.
Fixes https://github.com/external-secrets/external-secrets/issues/3130
> feat: add wait for values to be created and updated on 1Password side

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/webhook-deployment.yaml
- deploy/charts/external-secrets/values.yaml
Single place to specify scheduling parameters for all the components
Add global section for chart values and treat it as default if not specified otherwise
> Global scheduling parameters

- pkg/utils/utils.go
- pkg/utils/utils_test.go
Handle `json.RawMessage` as a `[]byte` in `util.GetByteValue`.
This allow Pulimi to extract structured data.
Close: #3307
Pulumi can't extract structured data
Fixes #3307
Pulumi use `json.RawMessage` who is a `[]byte`, but is not considered as is in the GetByteValue method. The proposed change is tested and fix the problem.
> Allow Pulimi to extract structured data.

- .github/workflows/helm.yml
Also publish the helm chart to OCI registry. See already created issue for full background info:
- #3208
Resolves #3208
While here I also updated the very old helm binary (3.4.x) inside the release action (was released on Dec 9, 2020). Time to also update this, as it doesn't support OCI pushing.
Tested it on my fork (already merged on main branch of the fork):
https://github.com/mkilchhofer/external-secrets/actions/runs/8085801631
Also like to mention that this piece of code is already in place on various helm chart publishing pipelines:
- [renovatebot/helm-charts](https://github.com/renovatebot/helm-charts/blob/5457a71d97e5318f3b5c152c332429ddf6a694a7/.github/workflows/release.yaml#L37-L44)
- [nextcloud/helm](https://github.com/nextcloud/helm/blob/9d560de6668ed393f8a8dfa84f5692352cf62ff3/ …
> feat: Also publish helm chart to OCI registry (ghcr.io)

- apis/externalsecrets/v1beta1/clusterexternalsecret_types.go
- apis/externalsecrets/v1beta1/zz_generated.deepcopy.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
Currently, there is no way to OR multiple NamespaceSelectors ([LabelSelector](https://github.com/kubernetes/apimachinery/blob/d82afe1e363acae0e8c0953b1bc230d65fdb50e2/pkg/apis/meta/v1/types.go#L1242-L1252) ANDs labels). 
Closes https://github.com/external-secrets/external-secrets/issues/3257
Add a new field called `NamespaceSelectors` and deprecate `NamespaceSelector` .
I will also add the same field to ClusterSecretStore for consistency.
> Add NamespaceSelectors field to ClusterExternalSecret

- docs/provider/fortanix.md
- pkg/provider/fortanix/fortanix.go
- pkg/provider/fortanix/fortanix_test.go
Adding support for `dataFrom[*].extract` to SDKMS / Fortanix provider
Implements `GetSecretMap()`
> Extract support for SDKMS provider

- .github/workflows/ci.yml
- .github/workflows/dlc.yml
- .github/workflows/docs.yml
- .github/workflows/e2e-managed.yml
- .github/workflows/e2e.yml
- .github/workflows/helm.yml
- .github/workflows/publish.yml
- .github/workflows/rebuild-image.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- .github/workflows/update-deps.yml
Releases have changed how they are presented both in the release link and in docs, and we assume it is because of bumps in actions that were not tested. Reverting those changes for now while we figure out which of those bumps are responsible and what needs to change for us to be able to update those actions
> revert gh-actions bumps while we figure out changes in them

- pkg/provider/yandex/common/sdk.go
`grpc.Dial` is deprecated, so we should use `grpc.NewClient` instead, or the linter keeps failing...
- https://github.com/grpc/grpc-go/blob/a4afd4d995b0e60b9beb7b54923fa74ef97a5098/clientconn.go#L199-L204
N/A
Use `grpc.NewClient` instead
> Use grpc.NewClient instead of grpc.Dial

- pkg/provider/pulumi/pulumi.go
- pkg/provider/pulumi/pulumi_test.go
Add TestGetSecretMap
Fixes #3332
When extracting secret with the pulumi provider, the extracted elements who are strings contains unwanted double quotes at the begining and at the end of the extracted secret. 
Fixes #3332 
This is due to `json.RawMessage` : With `interface{}`, the `GetByteValue` method correctly handle it and return the value without quotes.
> Pulumi: Remove unwanted chars when extract secret

- docs/provider/webhook.md
There is a typo in webhook docs.
Fixes #...
> Fix typo in webhook.md

- docs/snippets/generator-acr-example.yaml
The generator-acr-example.yaml contains extra `,` which is causing issue #3365 
Fixes #3365 
Removed `,`
> Fix Azure Container Registry Generator invalid YAML

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/_helpers.tpl
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/templates/webhook-deployment.yaml
- deploy/charts/external-secrets/values.yaml
Enhanced `securityContext` customizations with specific considerations for OpenShift
Provided new Helm partial that provides enhancements for managing `securityContext` values. Supports removing fields set automatically by OpenShift
> Methods for managing securityContext and OpenShift support

- docs/guides/pushsecrets.md
- hack/api-docs/mkdocs.yml
Some of the links are duplicated and broken which were resulting in 404.
Fixes #3362, #3442
- Most of the links for the providers under `Community` section are broken. The links have been moved under `Provider` section so removed them from `Community` section
- The links for contributing section have been moved to `Community` section. The links for the `Contributing` section are broken so removed them
- The link for the `Deprecation Policy` under `Community` section is broken. The link is moved under `Introduction` section so remove the link from `Community` section
- The docs for the `Password Depot` and `Fortanix` did exists however they were not included in the `Provider` section so included the docs under the `Provider` section
> Fixed docs nav bar and a couple of broken links

- config/crds/bases/kustomization.yaml
- hack/crd.generate.sh
The file `generators.external-secrets.io_githubaccesstokens.yaml` is not included in the `kustomization.yaml` file, so the CRD `GithubAppToken` is not installed through Kustomize.
Fixes https://github.com/external-secrets/external-secrets/issues/3448
- Adding `generators.external-secrets.io_githubaccesstokens.yaml` to `kustomization.yaml` file
> Add githubaccesstoken CRD to kustomization.yaml

- pkg/provider/gcp/secretmanager/client.go
We should use [the maps package](https://tip.golang.org/doc/go1.21) added in 1.21 to compare maps.
> Use maps.Equal to compare maps

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/tests/__snapshot__/controller_test.yaml.snap
- deploy/charts/external-secrets/values.yaml
For now, `dnsPolicy` is not optional for Deployment. This is needed when we want to deploy external-secrets on Fargate.
Fixes #...
This MR makes `dnsPolicy` parameter optional for the Deployment resource.
> fix: add dnsPolicy to Deployment

- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/controllers/externalsecret/suite_test.go
We used to use `Owns(&v1.Secret{}, builder.OnlyMetadata)` in the SetupWithManager method, [but depending on the creation policy, we don't set an owner reference](https://github.com/external-secrets/external-secrets/blob/c73eee267afb8ea707b8b7e11be3adff01282822/pkg/controllers/externalsecret/externalsecret_controller.go#L253). As a result, when users use a creation policy except for Owner, reconciliation does not start even if a secret has changed.
N/A
Use Watches with a custom field indexer to get the secret effectively.
> Start reconciliation when a secret has changed

- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/controllers/externalsecret/suite_test.go
Since we merged https://github.com/external-secrets/external-secrets/pull/3459, [the checkDeletion test case](https://github.com/external-secrets/external-secrets/blob/faac2b95618bf750bd40d7e56320cf2553df3b1a/pkg/controllers/externalsecret/externalsecret_controller_test.go#L1854) has become flaky. ([ref](https://github.com/external-secrets/external-secrets/actions/runs/9047984481/job/24860568776)) I dug into it and realized since we started using the cache client from the controller,  the controller received a deleted secret [here](https://github.com/external-secrets/external-secrets/blob/30f2f902cd76dbc3e74d8fadd688dfbd971a1962/pkg/controllers/externalsecret/externalsecret_controller.go#L172) after reconciliation starts due to the secret deletion. To tackle the problem, I've disabled the …
> Fix flaky ES controller test

- docs/guides/templating-v1.md
- docs/guides/templating.md
- pkg/template/v1/template.go
- pkg/template/v1/template_test.go
- pkg/template/v2/template.go
- pkg/template/v2/template_test.go
While working on the template, I noticed if I specify a non-existent key in the template, the reconciliation succeeds and inserts value `<no value>`. This behavior seems quite error-prone since users could accidentally insert base64 encoded `<no value>` to their secret value.
N/A
Use the `missingkey=error` option for the go template to raise the error.
> Raise error when unknown key specified in template

- .github/workflows/ci.yml
Adding support for ppc64le arch.
Fixes #3499 
Add ppc64le arch to build script.
> Update ci.yml with ppc64le arch support

- docs/snippets/bitwarden-cli-deployment.yaml
The example for the BitWarden integration in the documentation contains a misconfiguration, leading to confusion as per current behavior (see [this issue](https://github.com/bitwarden/clients/issues/8762))
The liveness command perform a vault re-sync which usually takes a few second to perform. This commit replace the current value which is too low and lead to timeout and pod termination.
Fixes bitwarden/clients#8762
Update the probe timeout to a higher value, taking into account the actual time taken by the sync operation (usually, somewhere between 2 to 5 seconds) 
- [-] My changes have reasonable test coverage
- [-] All tests pass with `make test`
- [-] I ensured my PR is ready for review with `make reviewable`
> doc(BitWarden): extends the liveness timeout

- docs/provider/aws-parameter-store.md
- docs/snippets/aws-pm-push-secret-with-metadata.yaml
- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/parameterstore/parameterstore_test.go
Currently, we don't have the option to set which parameter type to use for the AWS parameter store, and as a result, all secrets are stored remotely as plain text `String`. This PR adds the possibility to work with the following types `String`, `SecureString`, and `StringList` through `PushSecret`'s metadata.
Fixes #3422
> feat: add support to set Type for AWS parameter store

- pkg/provider/aws/parameterstore/fake/fake.go
- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/parameterstore/parameterstore_test.go
- pkg/utils/utils.go
Fixes https://github.com/external-secrets/external-secrets/issues/3436
> ref: parameter store should be called only once

- apis/externalsecrets/v1beta1/clusterexternalsecret_types.go
- apis/externalsecrets/v1beta1/externalsecret_types.go
- apis/externalsecrets/v1beta1/secretstore_types.go
- apis/generators/v1alpha1/generator_acr.go
- apis/generators/v1alpha1/generator_ecr.go
- apis/generators/v1alpha1/generator_fake.go
- apis/generators/v1alpha1/generator_gcr.go
- apis/generators/v1alpha1/generator_github.go
- apis/generators/v1alpha1/generator_password.go
- apis/generators/v1alpha1/generator_vault.go
- apis/generators/v1alpha1/generator_webhook.go
- cmd/certcontroller.go
- cmd/root.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- config/crds/bases/generators.external-secrets.io_acraccesstokens.yaml
- config/crds/bases/generators.external-secrets.io_ecrauthorizationtokens.yaml
- config/crds/bases/generators.external-secrets.io_fakes.yaml
- config/crds/bases/generators.external-secrets.io_gcraccesstokens.yaml
- config/crds/bases/generators.external-secrets.io_githubaccesstokens.yaml
- config/crds/bases/generators.external-secrets.io_passwords.yaml
- config/crds/bases/generators.external-secrets.io_vaultdynamicsecrets.yaml
- config/crds/bases/generators.external-secrets.io_webhooks.yaml
- deploy/crds/bundle.yaml
- pkg/constants/constants.go
- pkg/controllers/webhookconfig/webhookconfig.go
- pkg/controllers/webhookconfig/webhookconfig_test.go
The certcontroller watches CRDs and Webhook configurations, and manages CA certificates for conversion webhooks of CRDs and Webhook configurations. Some clusters have a large number of CRDs and Webhook configurations installed. Additionally, some CRDs have large object sizes. Currently, the certcontroller holds all CRDs and Webhook configurations in the Informer cache. Since this includes CRDs not managed by the certcontroller for CA certificates, memory usage tends to be high.
Fixes #...
This PR adds a label to the CRDs and configures the Informer cache to hold only the CRDs and Webhook configurations restricted by the label selector. It assumes that the CRDs have a label. Depending on how the External Secrets Operator is managed, it may be possible to update the External Secrets …
> feat(certcontroller): Allow restricting CRDs and Webhook configs in Informer cache

- .github/ci/ct.yaml
- deploy/charts/external-secrets/ci/main-values.yaml
- deploy/charts/external-secrets/templates/cert-controller-deployment.yaml
- deploy/charts/external-secrets/tests/__snapshot__/cert_controller_test.yaml.snap
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
Follow-up PR of #3588. We want to deliver the fix for reducing certcontroller's memory usage to users as much as possible. See https://github.com/external-secrets/external-secrets/pull/3588#pullrequestreview-2121324360 by @moolen.
Fixes #...
Set `--enable-partial-cache=true` if `installCRDs=true` in the Helm chart.
<details>
<summary><code>helm template external-secrets .  --set installCRDs=true</code></summary>
```yaml
(...)
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: external-secrets-cert-controller
namespace: default
labels:
helm.sh/chart: external-secrets-0.9.19
app.kubernetes.io/name: external-secrets-cert-controller
app.kubernetes.io/instance: external-secrets
app.kubernetes.io/version: "v0.9.19"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
revisionHistoryLimit: …
```
> feat(chart): Enable partial cache for certcontroller when installCRDs=true

- pkg/controllers/pushsecret/pushsecret_controller.go
- pkg/controllers/pushsecret/pushsecret_controller_test.go
Hi, first ever FOSS contribution :)
Adding skip unmanaged store logic to push secret controller. This removes log spam e.g. `could not get secrets client for store test-store: can not reference unmanaged store`
Fixes [#2164](https://github.com/external-secrets/external-secrets/issues/2164)
Used similar logic to external secret controller
- [x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ x] All commits are signed with `git commit --signoff`
- [ x] My changes have reasonable test coverage
- [ x] All tests pass with `make test`
- [ x] I ensured my PR is ready for review with `make reviewable`
I am unsure about the testing part - the external secret controller tests seem to be more advanced than push secret …
> Add skip unmanaged store logic for push secret controller

- pkg/provider/vault/auth.go
- pkg/provider/vault/auth_test.go
In the vault client library, `LookupSelfWithContext` calls `ParseSecret`, which has a few places where it returns `nil, nil` instead of returning a proper error. The most common scenario is when the token expires and the Vault server returns:
```json
{
"errors": [
"permission denied"
]
}
```
This causes the Vault provider to dereference the `nil` response and crash the process. This only happens when the experimental caching feature is enabled.
(None reported)
This commit adds an additional check (with corresponding tests) to ensure that a `nil` response won't be dereferenced in `checkToken()`.
> fix(vault): Fix crash when caching is enabled and a token expires

- pkg/provider/azure/keyvault/keyvault.go
- pkg/template/v1/template.go
- pkg/template/v2/pkcs12.go
- pkg/template/v2/template.go
Remove the use of "golang.org/x/crypto/pkcs12" and switch to software.sslmate.com/src/go-pkcs12 instead.
Fixes https://github.com/external-secrets/external-secrets/issues/3585
Remove the use of "golang.org/x/crypto/pkcs12" and switch to software.sslmate.com/src/go-pkcs12 instead.
> Remove the use of "golang.org/x/crypto/pkcs12"

- deploy/charts/external-secrets/templates/rbac.yaml
- e2e/go.mod
- go.mod
- pkg/controllers/externalsecret/externalsecret_controller.go
Towards https://github.com/external-secrets/external-secrets/issues/3604: 
It appears, that the status subresource is slightly inconsistent. This leads to unexpected behaviour, where a secret is reconciled where it shouldn't. This is problematic in combination with a generator resource and usage of the `immutable` field on the secret.
To reproduce the problem, run the following commands. It is a race condition!:
```
while true; do
k apply -f ./issue-3604.yaml >/dev/null; sleep 1;
k get es;
k delete -f ./issue-3604 > /dev/null
done
```
Once you see `SecretSyncedError` you triggered the bug.
```yaml
metadata:
name: es-5-test
spec:
dataFrom:
- sourceRef:
generatorRef:
apiVersion: generators.external-secrets.io/v1alpha1
kind: …
```
> fix: explicitly fetch status subresource due to inconsistencies

- pkg/controllers/pushsecret/pushsecret_controller.go
- pkg/controllers/pushsecret/pushsecret_controller_test.go
See #3609.
A PushSecret created with `DeletionPolicy==Delete` and later updated with `DeletionPolicy==None` has no codepath to remove its finalizers.
Fixes #3609
Populate `case DeletionPolicyNone:` with an unconditional removal of the finalizer.
> Adds codepath for removing finalizers

- docs/api/generator/acr.md
- docs/snippets/generator-acr-example.yaml
Following the examples for configuring an External Secret to inject credentials to access an Azure Container Registry did not work. This fixes that by updating the docker config json in the external secret.
Fixes #3178
> Fix ACR External Secret example

- docs/snippets/full-external-secret.yaml
The [`ExternalSecret` example](https://external-secrets.io/latest/api/externalsecret/#example) has two incorrect lines under dataFrom.find:
```
rewrite:
- regexp:
source: "exp-(.*?)-ression"
target: "rewriting-${1}-with-groups"
- find:
path: path-to-filter
source: "exp-(.*?)-ression"
target: "rewriting-${1}-with-groups"
name:
regexp: ".*foobar.*"
```
> docs: fix dataFrom.find in ExternalSecret api example

- .github/workflows/e2e.yml
e2e test results generated with /ok-to-test are hard to track, and target only the PR tip.
This PR fixes it
Fixes #3465
> bump e2e pipeline

- pkg/common/webhook/webhook.go
- pkg/provider/webhook/webhook_test.go
The webhook provider incorrectly assumes that the server's returned JSON object has values that are all strings. 
Fixes #3239
Use the conversion functions provided by utils that the other providers use.
> fix(webhook): perform conversion of data

- ADOPTERS.md
- pkg/provider/vault/auth.go
- pkg/provider/vault/auth_test.go
Without this, it's possible to hit a TOCTOU issue where `checkToken()` sees a valid token, but it expires before the actual operation is performed. This condition is only reachable when the experimental caching feature is enabled.
60 seconds was chosen as a sane (but arbitrary) value. It should be more than enough to cover the amount of time between `checkToken()` and the actual operation.
(None reported)
Treat close-to-expiring tokens as if they were expired already.
> fix(vault): Treat tokens expiring in <60s as expired

- pkg/provider/chef/chef_test.go
- pkg/provider/doppler/doppler_test.go
- pkg/provider/fortanix/provider_test.go
- pkg/provider/gitlab/gitlab_test.go
- pkg/provider/ibm/provider_test.go
- pkg/provider/onboardbase/onboardbase_test.go
- pkg/provider/onepassword/onepassword_test.go
- pkg/provider/oracle/oracle_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
As described in the original issue, currently, we do not allow specifying the namespaces fields at all for namespace SecretStore, but it is more intuitive for users to allow them to specify the same namespace with the SecretStore.
Relates to https://github.com/external-secrets/external-secrets/issues/3520
Allow users to specify the same namespace with the SecretStore.
> Allow specifying the same namespace for SecretStores

- design/010-pushsecret-metadata.md
This is a design document to align the approach on how we intend to use and structure PushSecret metadata across providers.
OG PR for PushSecret Metadata: https://github.com/external-secrets/external-secrets/pull/2600
Recent PRs who want to change/extend the PushSecret metadata:
https://github.com/external-secrets/external-secrets/pull/3600
https://github.com/external-secrets/external-secrets/pull/3581
> docs: add proposal for PushSecret metadata

- docs/introduction/stability-support.md
ESO v0.9 supports K8s v1.30 as per [this makefile](https://github.com/external-secrets/external-secrets/blob/v0.9.19/Makefile?rgh-link-date=2024-07-05T14%3A16%3A00Z#L325), however the docs do not reflect this. Currently it reads as no ESO version is compatible with K8s 1.30
I have also tested ESO v0.9.19 with an EKS 1.30 cluster and nothing seemed inoperable.
Closes: https://github.com/external-secrets/external-secrets/issues/3658
Updated the docs
> docs: updated k8s support for ESO v0.9

- docs/provider/hashicorp-vault.md
Misspasted Kubernets manifest in sample code.
Fixes #3661
Commenting misspasted manifest just to example (didatically) which resource will be created after deploy the external secret component.
> Commenting secrets manifest from hashicorp vault integration #3661

- docs/snippets/full-cluster-secret-store.yaml
This fixes a typo on https://external-secrets.io/v0.9.20/api/clustersecretstore/, in which the property is incorrectly called `namespacesRegex`
> docs: Fix `namespaceRegexes` in full-cluster-secret-store.yaml

- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/aws/secretsmanager/secretsmanager_test.go
The AWS Provider's SecretManager has a SecretExists function that currently returns `true` when a secret does not exist. Not sure why this was implemented in such a way. This PR fixes that to return `false` when a secret does not exist and alters the unit tests as well.
Fixes #3682 
Change the `handleSecretError` to return false in case the secret does not exist error pops up, hence returning false in the `SecretExists` function.
> fix: aws secretmanager's SecretExists returns true for non-existent secrets

- docs/api/clusterexternalsecret.md
- docs/snippets/full-cluster-external-secret.yaml
Updating the documentation to reflect the deprecation of `namespaceSelector` in favor of `namespaceSelectors`
n/a
This has the documentation updated to use `namespaceSelectors` instead of `namespaceSelector`
> Update docs for namespaceSelectors usage and namespaceSelector deprecation

- pkg/provider/aws/parameterstore/parameterstore.go
`GetParametersByPathWithContext()` already has all the parameters, decrypted. No need to query the API once more to get the same thing.
Looks like `findByName()` is a copy paste from the implementation for `findByTag()`, but in the latter case a different call is used - `DescribeParametersWithContext()` which requires additional `GetParameterWithContext()` call to get the value.
You can test that call easily by using AWS CLI `aws sim get-parameters-by-path --path 'your/ssm/path' --with-decryption` and see the output actually contains everything.
Haven't open one yet.
The change eliminates a redundant call which in my case is the difference between hitting AWS SSM rate-limits and not.
> remove redundant parameter grab call, we already have the data

- e2e/suites/provider/cases/vault/vault.go
- pkg/controllers/secretstore/common.go
Some who don't have access to the logs, will be unable to identify errors that are from validation.
This addition increases the verbosity of that error.
> feat: increase verbosity of error message during validation

- docs/guides/templating-v1.md
- docs/snippets/gcpsm-tls-externalsecret.yaml
The documents are outdated when it comes to templating an `ExternalSecret` and decoding a .p12/.pfx file.
Fixes #3260 
I'm trying to update the docs such that they don't reference the unused functions `pemCertificate` and `pemPrivateKey`.
> docs: Remove references to pemCertificate and pemPrivateKey functions 

- docs/snippets/full-external-secret.yaml
In the _[API » External Secret » Example](https://external-secrets.io/v0.9.20/api/externalsecret/#example)_ documentation page, the comments for the `.spec.target.creationPolicy` parameter do not mention the `Orphan` option. Additionally, the comments for the `.spec.target.deletionPolicy` parameter lack a description of the available options.
Fixes: https://github.com/external-secrets/external-secrets/issues/3724
Re-write the comments for the `.spec.target.creationPolicy` and `.spec.target.deletionPolicy` parameters to clearly explain their functionality and list the available options using straightforward language.
> docs: Improvements in the ExternalSecret comments in API section

- apis/externalsecrets/v1beta1/secretstore_aws_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- pkg/provider/aws/parameterstore/fake/fake.go
- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/parameterstore/parameterstore_test.go
- pkg/provider/aws/provider.go
Fixes https://github.com/external-secrets/external-secrets/issues/1649
> feat: add prefix definition to all secret keys for aws parameter store

- pkg/common/webhook/webhook.go
- pkg/provider/webhook/webhook.go
BREAKING CHANGE: Webhook secrets now must be labeled for Webhook SecretStore
BREAKING CHANGE: Generator webhook labels changed
Fixes #...
> feat: webhook secrets must be labeled

- docs/provider/aws-parameter-store.md
Add minimal policy required for pushing parameters to SSM.
N/A
Doc changed.
- [ x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ x ] All commits are signed with `git commit --signoff`
> chore: add minimal policy for fetching parameters from ssm

- docs/guides/security-best-practices.md
Currently, users have no easy way to know how to enforce better TLS ciphers on webhook (even though the feature is there).
Adding documentation on security best practices on how to do it.
> chore: update security best practice

- docs/eso-blogs.md
- docs/provider/conjur.md
- pkg/provider/conjur/auth_jwt.go
- pkg/provider/conjur/client.go
- pkg/provider/conjur/conjur_api.go
- pkg/provider/conjur/provider_test.go
ESO makes direct request to Conjur's authn-jwt endpoint. Now that Conjur's [Go API](https://github.com/cyberark/conjur-api-go) has better authn-jwt support, we should use the built-in NewClientFromJwt instead of overriding it.
CyberArk internal issue ID: CNJR-5634, CNJR-5635
> Use Conjur API's built in JWT functions

- pkg/provider/vault/client_get.go
- pkg/provider/vault/client_get_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/3116
> fix: only replace data if it is in the middle of the path

- docs/introduction/stability-support.md
The docs provided confusing information around supported versions of ESO
https://github.com/external-secrets/external-secrets/issues/3863
Updated the supported versions table to show only the latest two releases as supported
> Updated supported versions table for 0.10 release

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/tests/__snapshot__/cert_controller_test.yaml.snap
- deploy/charts/external-secrets/tests/__snapshot__/controller_test.yaml.snap
- deploy/charts/external-secrets/tests/__snapshot__/webhook_test.yaml.snap
- deploy/charts/external-secrets/values.yaml
- e2e/framework/addon/eso.go
Updates Default OCI registry to use scarf
towards #3872 
Changes default value to use our own dns.
> chore: updates default oci

- README.md
- e2e/Makefile
What happens if when the test is running it loads images into the kind cluster. But the flux test is actually using the helm chart which contains a different repository so it failed to find the right image.
I fixed that by overwriting the image that is being used for e2e testing.
Why not just fix the Flux test? 
Because I want to make sure that the proxy repository is working with ALL of the tests, while the original Makefile is still building the ghcr.io repository images.
Fixes #...
> RELEASE BLOCKER: fix: flux and e2e tests not using the right image names for caching on local kind cluster

- pkg/provider/azure/keyvault/fake/fake.go
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/3284
> fix: pin to the right version for azure keyvault

- docs/snippets/gitops/deployment-crds.yaml
- docs/snippets/gitops/deployment-crs.yaml
- docs/snippets/gitops/deployment.yaml
- docs/snippets/gitops/repositories.yaml
Pin CRDs version in FluxCD example docs to line up with helm chart version
Fixes #3885 
> docs: pin CRDs version in FluxCD example, bump api versions

- pkg/provider/azure/keyvault/keyvault_test.go
The intention here should be to initialize a slice with a capacity of  1 rather than initializing the length of this slice.
Fixes #...
> fix: fix slice init length

- pkg/provider/bitwarden/client.go
- pkg/provider/bitwarden/client_test.go
If we use `updatePolicy: IfNotExists` with a `PushSecret`, it will fail. This is due to `findSecretByRef` returning and error on missing secret, and that makes `SecretExists` return an error.
None
I made `findSecretByRef` not returning an error on missing secret, and moved that check to `SecretExists` and `DeleteSecret` instead.
> fix: improve SecretExists in Bitwarden provider

- docs/index.md
Updating the Introduction page with the ESC support to match the README on GitHub
https://github.com/external-secrets/external-secrets/pull/2997
> Adding Pulumi ESC to intro page

- docs/snippets/generator-acr-example.yaml
The old example used a `refreshInterval` value of 12h for the ACR access token. This change reduces that to 3h instead, since that is the expiration time for Service Principal authentication tokens:
https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#service-principal
Service principals are not the only way to authenticate towards ACR. In fact, two other ways (`managedIdentity` and `workloadIdentity`) are also outlined in the docs. I was unable to find any documentation in Azure for the default expiration time for those tokens, so as far as I know it is always 3 hours. Thus I think we should reflect this in our examples.
n/a
I like concrete examples that work out-of-the-box. API details can always be found in the spec for those that …
> Reduce refreshInterval example for ACR

- apis/generators/v1alpha1/generator_vault.go
- apis/generators/v1alpha1/zz_generated.deepcopy.go
- config/crds/bases/generators.external-secrets.io_vaultdynamicsecrets.yaml
- deploy/crds/bundle.yaml
- pkg/generator/vault/vault.go
- pkg/provider/vault/provider.go
I would like to use retry logic in the VaultDynamicSecret generator to ensure that if vault is failing token will be renewed before next retry interval
Fixes #4075
Add RetrySettings to the VaultDynamicSecret spec and pass it to the configuration builder.
> Add ability to use RetrySettings in the VaultDynamicSecret generator

- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
Before this change, it was a bit unclear what type of `ExternalSecret.spec.refreshInterval` was.
Fixes #4079
This change aims to clarify the documentation for `ExternalSecrets.spec.refreshInterval` by adding examples and referring to Go's `Duration` type.
> Update docs for ExternalSecrets's refreshInterval

- .github/workflows/helm.yml
Follow-up of: https://github.com/external-secrets/external-secrets/pull/3128
For a still unknown reason, the gpg signing broke earlier this year. I have re-provisioned the gpg key changed the password, which now works.
Successful release: https://github.com/external-secrets/external-secrets/actions/runs/11879368829/job/33101505602?pr=4109
> fix: re-enable signing helm release

- .github/workflows/helm.yml
- deploy/charts/external-secrets/Chart.yaml
WRT: https://kubernetes.slack.com/archives/C047LA9MUPJ/p1731958028445619
The import-gpg step fails for PRs from forked repos. The key does not exist there and is not needed.
This PR was made from a forked repo.
> fix: do not import gpg key from forked repo

- pkg/provider/gcp/secretmanager/client.go
- pkg/provider/gcp/secretmanager/client_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/4016
> feat: implement SecretExists function for gcp secretsmanager

- .github/workflows/helm.yml
Fixes https://github.com/external-secrets/external-secrets/security/code-scanning/41
> fix: restrict the token permission update to the push chart step

- .github/workflows/helm.yml
Fixes https://github.com/external-secrets/external-secrets/security/code-scanning/43
> fix: further restrict token permissions on helm action steps

- docs/snippets/full-secret-store.yaml
YAML TLS Keys in example are wrong
Fixes #4130
Replaced wrong keys with the right ones
> Change wrong YAML TLS keys in documentation

- pkg/provider/azure/keyvault/keyvault.go
As described in #4135, ESO 0.10.6 tries to call a non-existent OpenID discovery endpoint in `NewTokenProvider` (`https://login.microsoftonline.com/<REDACTED>/oauth2/token/v2.0/.well-known/openid-configuration?`), which causes failure in provider authentication.
Fixes #4135
From I see, instead of `https://login.microsoftonline.com/<REDACTED>/oauth2/token/v2.0/.well-known/openid-configuration?`, the operator should have called `https://login.microsoftonline.com/<REDACTED>/v2.0/.well-known/openid-configuration` as the latter exists and contains all the relevant information about various endpoints.
So, the problem is caused by the `/oauth2/token` suffix passed in `NewTokenProvider`:
```go
cClient, err := confidential.New(fmt.Sprintf("%s%s/oauth2/token", aadEndpoint, tenantID), clientID, cred) …
```
> fix(azure-keyvault): remove incorrect suffix from provider URL to fix OpenID discovery call

- apis/generators/v1alpha1/generator_schema.go
- apis/generators/v1alpha1/generator_types.go
- apis/generators/v1alpha1/register.go
- cmd/root.go
- cmd/webhook.go
- e2e/framework/util/util.go
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_secret.go
- pkg/controllers/pushsecret/pushsecret_controller.go
- pkg/controllers/secretstore/client_manager_test.go
- pkg/utils/resolvers/generator.go
Currently, we are using an unstructured API to get the Generator objects in `getGeneratorDefinition`:
https://github.com/external-secrets/external-secrets/blob/3218a21cb7e7905137e947e3166f52c30f4b7c6d/pkg/utils/resolvers/generator.go#L45-L84
Unstructured API calls don't use the controller-runtime cached client, so are making Kubernetes API requests every time we need to get a Generator. 
The `getGeneratorDefinition` method is used in both `shouldSkipUnmanagedStore` and `getProviderSecretData`, so is run at least twice for each reconcile of an ExternalSecret that uses a Generator.
This PR makes it so we use the structured APIs when getting generator resources, this allows us to use the cache.
I have also improved upon the work from …
> fix: use cache when retrieving generators

- docs/api/generator/acr.md
- docs/snippets/generator-acr-argocd-helm-repo.yaml
- docs/snippets/generator-acr.yaml
- pkg/generator/acr/acr.go
Trying to use ACR generator with kubelet managed identity as described in [docs ](https://external-secrets.io/latest/api/generator/acr)
```yaml
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
metadata:
name: my-azurecr
spec:
tenantId: 11111111-2222-3333-4444-111111111111
registry: example.azurecr.io
environmentType: "PublicCloud"
auth:
managedIdentity:
identityId: "xxxxx" # Supposed to be managed identity client ID as in Azure Key Vault provider
```
Got such in logs
```log
ManagedIdentityCredential authentication failed. the requested identity isn't assigned to this resource\nGET http://169.254.169.254/metadata/identity/oauth2/token
```
Check if the `identityID` contains a "/" and set the `ManagedIdentityCredentialOptions` accordingly, using `ResourceID` or …
> fix: handle managed identity ClientID or ResourceID in acr generator

- apis/externalsecrets/v1beta1/externalsecret_types.go
- docs/guides/templating-v1.md
- docs/snippets/pkcs12-template-v1-external-secret.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_secret.go
- pkg/controllers/externalsecret/externalsecret_controller_template.go
- pkg/template/engine.go
- pkg/template/v1/template.go
- pkg/utils/utils.go
This PR makes the following changes:
1. Fixes an issue that prevented v1 templates from defining metadata/annotations (I think this was present before 0.11):
- https://github.com/external-secrets/external-secrets/issues/4172
- https://github.com/external-secrets/external-secrets/issues/1910
- __NOTE:__ this PR also updates the docs for v1 templating to explain that annotations/labels are not templated in v1
3. We now always check if there are orphaned secrets when `creationPolicy=Owner`:
- Previously, we only checked when we first created a new target secret, but if that failed, we would not retry on the next reconcile.
- Because we are using the partial secret cache to check for orphaned secrets, it should not have a significant performance penalty, and will not make any new API call.
4. …
> fix: v1 templates with metadata + always cleanup orphaned secrets

- pkg/template/engine.go
In https://github.com/external-secrets/external-secrets/pull/4174, we accidentally introduced an issue for users who upgrade from very old versions of External Secrets.
The issue was that the `spec.target.template.engineVersion` can actually be empty. We only added that field with the default "v1" in https://github.com/external-secrets/external-secrets/pull/701 (which was included in external-secrets 0.4.3), so ExternalSecrets created in older versions will not have any `engineVersion` set.
This just means we need to assume that an empty `engineVersion` is "v1".
N/A
> fix: handle empty template engine version

- pkg/provider/pulumi/pulumi.go
There was an error in the order of a function call in the `PushSecret` implementation of the Pulumi ESC provider
Fixes #...
> fix: error in order of function call UpdateEnvironment

- docs/provider/google-secrets-manager.md
The problem is that the template syntax in the `provider/google-secrets-manager.md` file was causing a macro syntax error due to the use of dot notation within the double curly braces.
WARNING -  [macros] - ERROR # _Macro Syntax Error_
_File_: `provider/google-secrets-manager.md`
_Line 143 in Markdown file:_ **unexpected '.'**
```markdown
bestpokemon: "{{ .bestpokemon }}"
```
No Issue opened regarding this small bug
I have fixed the issue by wrapping the template code with `{% raw %} ... {% endraw %}` to prevent the template engine from interpreting the dot notation.
> docs: add raw markdown tags to PushSecret example in Google Secrets Manager documentation

- apis/generators/v1alpha1/types_vault.go
- config/crds/bases/generators.external-secrets.io_clustergenerators.yaml
- config/crds/bases/generators.external-secrets.io_vaultdynamicsecrets.yaml
- deploy/crds/bundle.yaml
- pkg/generator/vault/vault.go
- pkg/generator/vault/vault_test.go
I have a use case to perform a request against vault with no response data.
This PR should allow us to make the custom requests against more vault endpoints.
As there are various endpoints on vault which might return no data, it can be useful for more scenarios in the future.
My use case in detail:
I want to trigger a vault database credential rotation, which has no response. After that get the new credentials.
I cannot perform the operation in a pipeline process beforehand. The goal is to fake a manual rotation with an external secret annotation update, so I can include that in a helm chart deployment.
The use case was successfully tested in a local kubernetes environment.
```yaml
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
name: …
```
> add allowEmptyResponse to vaultdynamicsecrets

- docs/provider/aws-secrets-manager.md
The suggested policy for AWS SM was incorrect, causing errors when pulling the data with the new batch implementation.
https://github.com/external-secrets/external-secrets/issues/4274
Change the current policy to the one suggested by AWS when using the batch method.
https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_iam-policies.html#auth-and-access_examples_batch
The proposed policy has been tested with the `0.12.1` version
> docs: Fix IAM policy AWS SM provider

- docs/examples/bitwarden.md
- docs/provider/bitwarden-secrets-manager.md
There are 2 different documents for two different Bitwarden services.
The services are named similarly and people may get confused.
Add notes to each document explaining the difference.
Ran `make docs.serve` and verified both pages look good.
> docs: differentiate between two different bitwarden guides

- sonar-project.properties
> fix: sonar ignore duplication warning in test files only

- .sonarcloud.properties
- sonar-project.properties
We tried in https://github.com/external-secrets/external-secrets/pull/4320 and https://github.com/external-secrets/external-secrets/pull/4329 to disable the sonar duplicate literal check in tests, but that did not work.
The issue was that we were creating a `sonar-project.properties` file (used for CI-triggered sonar), rather than a `.sonarcloud.propertie` file (for their 'managed' one):
- see: https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-parameters/#setting-configuration-in-a-file
Used the correct file name, and set other recommended parameters based on:
- https://docs.sonarsource.com/sonarqube-server/10.6/analyzing-source-code/languages/go/
- https://github.com/redhat-developer/odo/blob/main/.sonarcloud.properties
- …
> fix: sonar configs

- cmd/controller/certcontroller.go
- cmd/controller/root.go
- go.mod
- pkg/controllers/clusterexternalsecret/suite_test.go
- pkg/controllers/common/common.go
- pkg/controllers/crds/suite_test.go
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/suite_test.go
- pkg/controllers/pushsecret/suite_test.go
- pkg/controllers/secretstore/suite_test.go
- pkg/controllers/webhookconfig/suite_test.go
related: https://github.com/external-secrets/external-secrets/issues/4107
related: https://github.com/external-secrets/external-secrets/issues/2837
This PR adjusts the retry behavior on failed reconciles of ExternalSecrets, SecretStores, PushSecrets, etc.
Currently, we are using the default rate limiter of `controller-runtime` which is way too aggressive for our use-case. It uses an exponential back-off which starts at `5ms` and goes up to `1000s` (~15min), which means you get 8 retry attempts in the first second! 
__CURRENT per-item back-off pattern:__
- 0.005s, 0.01s, 0.02s, 0.04s, 0.08s, 0.16s, 0.32s, 0.64s, 1.28s, 2.56s, 5.12s, 10.24s, 20.48s, 40.96s, 81.92s, 163.84s, 327.68s, 655.36s, 1000s, 1000s, ...
It also creates a new `common` package in `controllers` for the new …
> fix: retry failed reconciles much less aggressively

- pkg/provider/gitlab/gitlab.go
- pkg/provider/gitlab/provider.go
Regression when using group variables
Fixes #4361 
I kind of retroported the slightly different logic in 0.10.7:
https://github.com/external-secrets/external-secrets/blob/dc6be312cf592a294bfe370762856d98de29a64d/pkg/provider/gitlab/gitlab.go#L224-L236
> fix: gitlab group variable regression

- pkg/provider/aws/parameterstore/parameterstore.go
- pkg/provider/aws/parameterstore/parameterstore_test.go
`PushSecret` with AWS parameter store doesn't support `updatePolicy: IfNotExists`
Fixes #...
This PR implements the `SecretExists` function within `ParameterStore` to ensure that external secrets will only create the parameter if it doesn't exist in AWS.
> Implement SecretExists in AWS ParameterStore

- docs/guides/templating.md
Silly typo fix in the templating guide
> docs: fix typo in templating guide

- docs/examples/bitwarden.md
- hack/api-docs/mkdocs.yml
Typo for **BitWarden**, it should be **Bitwarden**, like how it is references elsewhere in the documentation.
Updates the references in the docs from `BitWarden` to `Bitwarden`.
> docs(typo): Update doc references from `BitWarden` to `Bitwarden`.

- apis/generators/v1alpha1/types_cluster.go
- config/crds/bases/generators.external-secrets.io_clustergenerators.yaml
- deploy/crds/bundle.yaml
A ClusterGenerator resource of kind `Password` or `QuayAccessToken` is failing because of the typo. This is a bug introduced in 0814a4a20256b80196dad5d659ef2f6f67367528.
Fix the typo.
> fix: Fix typo that prevents the Password ClusterGenerator from working

- docs/snippets/provider-aws-access.md
> docs: fix typo in the AWS Secrets manager provider docs

- apis/externalsecrets/v1alpha1/pushsecret_types.go
- config/crds/bases/external-secrets.io_pushsecrets.yaml
- deploy/crds/bundle.yaml
Fixes https://github.com/external-secrets/external-secrets/issues/4397
```yaml
Spec:
Data:
Conversion Strategy:  None
Match:
Remote Ref:
Property:    username
Remote Key:  git-sync-secret-copy
Secret Key:    username
Deletion Policy:   None
Refresh Interval:  1h
Secret Store Refs:
Kind:  SecretStore
Name:  secret-store-name
Selector:
Secret:
Name:       git-sync-secret
Update Policy:  Replace
```
With a thing like this:
```yaml
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
name: example-push-secret
spec:
secretStoreRefs:
- name: secret-store-name
selector:
secret:
name: git-sync-secret
data:
- match:
secretKey: username
remoteRef:
remoteKey: git-sync-secret-copy
property: username
```
The purpose is to …
> fix: add push secret refreshInterval defaulting

- pkg/controllers/externalsecret/externalsecret_controller.go
We had an invalid `secretStoreRef` at runtime and got this issue when upgrading from `0.9`. 
```
{"level":"error","ts":1738597140.1073334,"logger":"controllers.ExternalSecret","msg":"unable to determine if store is managed","ExternalSecret":{...},"error":"expected pointer, but got invalid kind","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:201\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).rec …
```
> fix: Improved error message for unsupported secret store kind

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/_helpers.tpl
- deploy/charts/external-secrets/templates/webhook-service.yaml
- deploy/charts/external-secrets/tests/webhook_test.yaml
- deploy/charts/external-secrets/values.schema.json
- deploy/charts/external-secrets/values.yaml
The webhook service type can't be configured and I need it to be `LoadBalancer`.
Fixes #3802
Source #3804 (marked stale)
All credits to @Grendel7, who actually developed this. Just trying to get the code into the main repo.
Their remarks on the changes:
Add a block of values to `webhook.service` to specify the `type` and `loadBalancerIP`, which are not customizable now.
Also, for good measure, extend this block with options to specify custom labels an annotations. Specifying custom labels was impossible without adding the label to everything. Custom annotations were possible, but only through `webhook.metrics.service`, which is confusing and misleading IMO given that the webhook service isn't just for metrics.
> Add more flexibility to webhook service

- docs/provider/kubernetes.md
Creating documentation about how to use kubernetes provider within same cluster without cluster wide access rights.
Resolution of discussion https://github.com/external-secrets/external-secrets/discussions/4394
Add documentation
> kubernetes provider documentation - Added section explaining how to create shared secret without cluster wide access

- docs/guides/security-best-practices.md
The description of options for controlling the reconciliation and CRD installation of cluster-wide resources in the "Security Best Practices" guide is incomplete.
- If the CRD installation is disabled in the Helm chart but the reconcilers are not, the core controller produces errors in its logs because it cannot find the CRDs.
- The docs don't explain how to disable reconciliation in the Helm chart. There's an easy-to-miss naming inconsistency between the Helm chart key for `ClusterSecretStore` CRD installation and reconciliation (the latter following the name of the core controller flag rather than the resource name), which makes listing the options in full especially useful.
- The core controller flags have to be set to `false` to disable reconciliation.
N/A
I've completed the …
> doc: enhance best practices for cluster-wide resources reconciliation

- pkg/controllers/externalsecret/externalsecret_controller_secret.go
- pkg/generator/statemanager/statemanager.go
See #4421. 
(1) The `NoSecretErr` should cause the generator state to commit. This happens in a transition from: having an ExternalSecret with generator state and then applying a change to it using a simple `extract` and dropping the use of the generator. Then this state change (delete generated value) should be committed and not rolled back.
(2) When no generator with state is used, the `Commit()` is a no-op since there is no state.
> fix: ignore NoSecretErr in generator state

- GOVERNANCE.md
Documenting the governance process being public and used correctly to add members to the organization https://github.com/cncf/toc/issues/1486#issuecomment-2668873894.
> docs: add examples of Governance document being applied for members joining

- pkg/controllers/externalsecret/externalsecret_controller_secret.go
- pkg/generator/statemanager/statemanager.go
Towards: #4449
This PR fixes the handling of empty generator state (which caused error logs). Also, it reworks the error handling of the generator state management. Commit errors should be visible to the user (conditions/events). If the commit fails, then the `ExternalSecret` should not become ready. If that would've been the case, our e2e tests would have caught this issue described in  #4449 as we have coverage for ECRAuthorizationToken.
> Make generator state commit err visible to the user / fix handling of empty state

- deploy/charts/external-secrets/templates/webhook-certificate.yaml
Fix implementation of revisionHistoryLimit on certificate
Fixes https://github.com/external-secrets/external-secrets/pull/4292#issuecomment-2666082738 (Thanks to @knechtionscoding for initial change)
Keep provided value as int (as described in the docs - https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec) instead of string
> Fix certificate revisionHistoryLimit invalid quote

- docs/provider/webhook.md
Add correct labels to secrets used for authentication in Webhook Providers
While using the Webhook Provider I kept getting this issue 
```
"error":"error processing spec.data[0] (key: secretPayload), err: secret does not contain needed label 'external-secrets.io/type: webhook'. Update secret label to use it with webhook"
```
After a while I found this https://github.com/external-secrets/external-secrets/blob/adf4da46ac8351adaf48d6aa260ab80519a52923/docs/snippets/generator-webhook.yaml#L23
And i noticed that this wasn't available in the general documentation.
-
-
> Improve documentation for webhook auth secrets

- docs/api/metrics.md
- pkg/controllers/pushsecret/psmetrics/psmetrics.go
- pkg/controllers/pushsecret/pushsecret_controller.go
Added a Status metric to the PushSecrets objects similar to a metric for the ExternalSecret objects. It'll help to monitor statuses of PushSecret objects with Prometheus.
https://github.com/external-secrets/external-secrets/issues/4488
> [feature] added Prometheus Status metric for the PushSecret objects

- cmd/controller/root.go
- pkg/controllers/common/common.go
- pkg/controllers/externalsecret/suite_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/4481
> fix: pass in namespace to managed cache for cluster scope if rbac is restricted

- docs/snippets/azkv-pushsecret-secret.yaml
- pkg/provider/azure/keyvault/keyvault.go
- pkg/provider/azure/keyvault/keyvault_test.go
Azure Key Vault supports setting tags on its entries. We can already pull secrets based on those, but cannot push with tags. This PR adds support for pushing tags.
Fixes #4506
> feat: Allow to specify tags when pushing to Azure Key Vault

- docs/provider/webhook.md
A code block that contain a Go template in #4508 is rendering empty.
No issue filed. It was something I noticed when reviewing the deployed documentation after #4508 was merged. I verified this fix locally by running `make docs.serve` and reviewing the rendered documentation.
Wrap a code block in a raw template so that the template in the block will render as expected.
> fix webhook provider docs

- pkg/provider/webhook/webhook_test.go
I was trying to analyze expected behaviors and improve tests in https://github.com/external-secrets/external-secrets/pull/4508.
This was just a small change I made locally while working on #4508, but didn't want to include it there and mix up a separate concern there.
Use subtests in webhook provider unit tests to make it easier to identify failing tests as well as run them in isolation.
> use subtests in webprovider unit tests

- pkg/template/v2/template.go
- pkg/template/v2/template_test.go
I am tired of issues related to templating conflicts with helm. This addresses that by allowing users to change default templating keys from external-secrets templating engine
Fixes my sanity
Fixes #4544
* controller level flag for templating delimiters (left and right)
* default values to prevent breaking changes
> feat: non standard templating delimiters

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/rbac.yaml
- deploy/charts/external-secrets/values.schema.json
- deploy/charts/external-secrets/values.yaml
> [!WARNING]
> This PR is based on #4570
The current Helm chart assigns resources in the RBAC definition even if they are not used by the controller
Based on the configuration, even if (for example) `processClusterExternalSecret` is set to `false` the controller is assigned permissions to manage ClusterExternalSecret resources. This is highly undesired in clusters with multiple installed ES instances.
> Exclude unused resources from rbac

- docs/api/externalsecret.md
The documentation is very clear about when an ExternalSecret is updated, but it differs from the implementation in case 
`spec.refreshInterval` is set to 0. Somewhat surprisingly (to me at least) even setting the annotation from the FAQ `kubectl annotate es my-es force-sync=$(date +%s) --overwrite` is skipped when `spec.refreshInterval` is `0`
This change was introduced with https://github.com/external-secrets/external-secrets/pull/4086 and confirmed in the discussion here https://github.com/external-secrets/external-secrets/issues/3979
If this behaviour is not considered a bug, then the documentation should to mention it explicitly.
> Clarify the implications of setting refreshInterval to 0

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/values.yaml
* Duplicated `crds.conversion.enabled: false` comment stating that `webhook.create` should be set to `false`.
* This coupling is easy missable when creating an override `values.yaml` file.
It's easy to miss that, when setting `webhook.create: false`, you should also set `crds.conversion.enabled: false` to avoid hammering the kubeapi. We noticed a lot of nuisance logs because we missed this when installing ESO.
Just a minor duplication of an already-existing comment (above `crds.conversion.enabled`) to try and avoid this problem for future users.
> Add `webhook.create: false` warning comment

- go.mod
- pkg/provider/gcp/secretmanager/workload_identity.go
- pkg/provider/gcp/secretmanager/workload_identity_test.go
When defining a SecretStore that uses the gcpsm (Google Secret Manager) provider, and one wants to use use workload identitity, the spec requires the values for `ClusterLocation`, `ClusterName` and `ClusterProjectID` are set. This adds additional configuration to maintain and makes the configuration more complex then required, as these values can be looked up from the metadata server available to all pods inside a GKE cluster.
Fixes #3540
This change solves this issue by looking up the `project-id`, `cluster-location` and `cluster-name` from the metadata server when the values for either `ClusterProjectID`, `ClusterLocation` or `ClusterName` aren't provided.
> Lookup cluster workload identity from instance metadata

- pkg/provider/alibaba/kms.go
The unit of timeout of Aliyun rrsa should be milliseconds instead of seconds.
N/A
30ms and 60ms timeout is too short.
> fix: aliyun timeout is ms not second

- pkg/provider/vault/auth_kubernetes.go
- pkg/provider/vault/provider_test.go
On clusters that still contains Secrets for Service Account Tokens, vault kubernetes auth _prefers_ them. That should not be the case.
Invert evaluation logic so that we prefer calling a `TokenAPI` request.
> feat: make kubernetes auth prefer service account tokens over secrets

- docs/api/generator/quay.md
repeated word `against` typo fix in docs.
n/a
per PR resolve typo.
- [n/a] My changes have reasonable test coverage
- [n/a] All tests pass with `make test`
- [n/a] I ensured my PR is ready for review with `make reviewable`
> docs: typo fix in api/generator/quay.md

- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
removing "5d" from refreshInvterval as is not supported by go's time.Duration parser.
Typo in docs saying giving an example of 5d as an allowed value for refreshInterval. But go's time.Duration parser does not support days.
Fixes #4426 update docs: refreshInterval can not be set to days
Removed "5d", from docs/api/spec.md https://external-secrets.io/latest/api/spec/
> remove days from refreshInterval docs

- pkg/provider/aws/provider.go
- pkg/provider/aws/secretsmanager/secretsmanager.go
- pkg/provider/aws/secretsmanager/secretsmanager_test.go
The `AWSProvider` (https://external-secrets.io/latest/api/spec/) supports a `prefix` field which would adds a prefix to all retrieved values.
However, looking at the code, only the AWS Parameter Store implements this.
No issue yet, but I can retroactively create one if desired.
This PR updates the AWS Secrets Manager provider to follow similar logic to AWS Parameter Store. The files are generally quite similar, so I pattern matched the implementation.
For the tests, I'm open to feedback on the best approach here. I inserted tests to re-use the existing test loops, and made adjustments where needed. Let me know if there is a better way to do it.
The edited tests pass (via `go test -v ./pkg/provider/aws/secretsmanager`).
Locally `make test` fails on …
> feat: Add AWSProvider.prefix to aws secrets manager

- docs/index.md
The current URL resolves to a 404 page.
Fixing URL. New page: https://www.pento.io
> docs: fix pento website url in the docs

- apis/externalsecrets/v1beta1/externalsecret_types.go
- config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml
- config/crds/bases/external-secrets.io_externalsecrets.yaml
- deploy/crds/bundle.yaml
- docs/api/externalsecret.md
- docs/api/spec.md
- docs/introduction/faq.md
- docs/snippets/full-cluster-external-secret.yaml
- docs/snippets/full-external-secret.yaml
- pkg/controllers/externalsecret/externalsecret_controller.go
- pkg/controllers/externalsecret/externalsecret_controller_secret.go
- pkg/controllers/externalsecret/externalsecret_controller_test.go
- pkg/controllers/util/util.go
- tests/__snapshot__/clusterexternalsecret-v1beta1.yaml
- tests/__snapshot__/externalsecret-v1beta1.yaml
The semantics of RefreshInterval is "RefreshInterval is the amount of time before the values ​​are read again from the SecretStore provider".
If RefreshInterval is 0, it means that the value will never be obtained from SecretStore. 
In many scenarios, users do not want to delete the secret unless it is rebuilt, but want to use ExternalSecret to update the value in the corresponding secret. The current implementation does not support this, but I think this field should be interpreted as auto refresh interval, which will improve the user experience. In addition to automatic updates, manual updates are also possible.
This PR implements this function: "Even if the user sets RefreshInterval to 0, he can also use the method of updating labels or Annotations to trigger another update."
How do …
> feat: ​add refreshPolicy field to ExternalSecret for enhanced synchronization control​

- deploy/crds/bundle.yaml
- hack/crd.generate.sh
This should fix some of the issues in #4662  - users that are installing crds with `kubectl apply -f` or `kustomize` are always adding crds with conversion enabled.
> fix: remove crds from bundle

- Makefile
- deploy/crds/bundle.yaml
- hack/crd.generate.sh
when users specify `kubectl apply -f`, they need to have `spec.conversion: {}` explicitly. While, with a `helm upgrade`, they need to have no `conversion` set for helm to upgrade the manifest.
With helm, the error is:
```
Required value && cannot patch "webhooks.generators.external-secrets.io" with kind CustomResourceDefinition: CustomResourceDefinition.apiextensions.k8s.io "webhooks.generators.external-secrets.io" is invalid: spec.conversion.strategy: Required value
```
While with kubectl apply (regardless if server side or client side), the error is:
```
for: "deploy/crds/bundle.yaml": error when patching "deploy/crds/bundle.yaml": CustomResourceDefinition.apiextensions.k8s.io "webhooks.generators.external-secrets.io" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should …
```
> fix: conversion setting on bundle crds

- pkg/utils/utils.go
- pkg/utils/utils_test.go
MD5 is an outdated algorithm that is no longer considered secure due to its vulnerabilities, which can compromise the reliability of data verification. This is specifically relevant in terms of NIST requirements for FIPS but also the industry at large has been moving away from MD5 for years. 
Switching the hashing algorithm to SHA3 provides a modern algorithm that meets current and future industry requirements.
> Update md5 hashing algorithim to sha3

- pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
When checking if an ExternalSecret is owned by a ClusterExternalSecret, the full apiversion is used. When migrating from v1beta1 to v1, the controller behave as is the ExternalSecret is no longer owned and won't update it.
Fixes #4708
Instead of comparing the `apiVersion` field of the owner, we use `GroupKind` like it's done in the `ExternalSecrets`'s controller.
> fix: ClusterExternalSecrets were not able to adopt externalSecret after update to v1

- docs/provider/kubernetes.md
Adds the missing documentation about possibility to set the secret type with the Kubernetes provider on `PushSecret`.
Fixes #...
Docs change.
> chore: document kubernetes provider pushsecret type

- pkg/provider/github/repo_secrets.go
There is a typo on repo declaration for github actions provider. This PR fixes it. 
Fixes #4744
Fix Typo :)
> fix: typo on delete method for repo

- .github/workflows/helm.yml
Helm chart releases are overwriting every time a new commit reaches main.
this fixes it.
Fixes #4760
New Job checking release existence prior to continuing with pipeline.
> fix: not releasing helm charts when its already released

- docs/provider/infisical.md
- docs/snippets/infisical-fetch-all-secrets.yaml
- docs/snippets/infisical-fetch-secret.yaml
- docs/snippets/infisical-generic-secret-store.yaml
- pkg/provider/infisical/client.go
- pkg/provider/infisical/client_test.go
- pkg/provider/infisical/provider.go
- pkg/provider/infisical/provider_test.go
(cc @akhilmhdh)
When attempting to access a secret in a directory, provided `secretsPath: /`, like so:
```yaml
metadata:
name: infisical-managed-secrets
spec:
secretStoreRef:
name: infisical
target:
name: auth-api
data:
- secretKey: API_KEY
remoteRef:
key: "foo/bar"
``` 
This will always result in a 404 API error from Infisical, because the API request is malformed (`/api/v3/secrets/raw/foo/bar`). The correct API request would instead be `/api/v3/secrets/raw/bar?secretPath=/foo`. This either:
- Made it so you simply cannot use secrets in folders with direct references via `data`
- Made it so you have to use a separate secret provider with a distinct `path`, which isn't very usable or very obvious
In combination …
> infisical: support secrets within paths for `data` references

- pkg/provider/vault/auth_test.go
- pkg/provider/vault/client_push.go
- pkg/provider/vault/provider.go
- pkg/provider/vault/provider_test.go
When enabling `--experimental-enable-vault-token-cache` I encountered persisting 403 status errors when connecting to our Vault server. Please read the thread starting at https://github.com/external-secrets/external-secrets/discussions/3132#discussioncomment-12605322 to catch up with the discussion around this issue.
While debugging this, I realized that this issue only appears when using a ClusterSecretStore that references a namespaced auth-token where the namespace is not fixed, like this:
```yaml
auth:
jwt:
path: jwt-kube
role: eso-default
kubernetesServiceAccountToken:
serviceAccountRef:
name: default  # Every namespace has its own default service-account
```
^ Note that the `serviceAccountRef` does not state a fixed `namespace`. The namespace of the `default` service account is …
> Cache separate vault clients for each namespace if necessary

- .github/workflows/helm.yml
Test run of the correct syntax https://github.com/Skarlso/test/actions/runs/15037317909
Fixes https://github.com/external-secrets/external-secrets/issues/4781
> fix: release check output is not a string

- DEPRECATING.md
- docs/introduction/deprecation-policy.md
There's a formatting error in the very fine Deprecation Policy guide:
Thanks for the level of detail in here! I don't know of any better place where Kubernetes Versioning is concisely explained. 🚀
Good luck with your 1.0.0 release!
> docs: Fix formatting in Deprecation Policy notes

- pkg/provider/webhook/webhook.go
- pkg/provider/webhook/webhook_test.go
Webhook provider does not allow `result.JsonPath` to be templated when calls come from `dataFrom` - even though it is stated in the docs it should be possible.
This PR fixes this by, well, templating the jsonPath :)
Fixes #4801
> fix: allows result.jsonpath to be templated on datafrom calls

- docs/snippets/generator-mfa.yaml
> fix: mfa generator length is too much and optional

- pkg/provider/onepassword/onepassword.go
Fixes #4663
Use a mutex on every access operation in the onepassword provider.
I have not (yet) tested these changes manually.
> fix: add mutex for thread safety in ProviderOnePassword methods

- deploy/charts/external-secrets/templates/cert-controller-poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/poddisruptionbudget.yaml
- deploy/charts/external-secrets/templates/webhook-poddisruptionbudget.yaml
When specifying only `maxUnavailable` for `podDisruptionBudget`, the `PodDisruptionBudget` manifest is generated with both `spec.minAvailable` and `spec.maxUnavailable` which is invalid.
Fixes #4832
Ensure that if `podDisruptionBudget.maxUnavailable` is specified, `spec.minAvailable` is not render with
```
{{- if ... ... ... }}
{{- else if ... ... ... }}
{{- end }}
```
> fix: pdb spec rendering issue

- docs/api/clusterpushsecret.md
- docs/api/pushsecret.md
- docs/snippets/full-cluster-push-secret.yaml
- docs/snippets/full-pushsecret.yaml
This PR fixes a couple of issues related to the docs of [PushSecret](https://external-secrets.io/latest/api/pushsecret/) and [ClusterPushSecret](https://external-secrets.io/latest/api/clusterpushsecret/):
1. The example is unclear, as the same key is used for source, destination, and within the resource.
2. Part of the example is unfunctional. Accessing a YAML key with a dash will fail with the following error unless the `index` function is used.
3. Unify the style of `PushSecret` as it doesn't follow the same structure as the other pages under the same section.
Maybe not directly related, but Google sends people to this issue https://github.com/external-secrets/external-secrets/issues/3443, and with the unfunctional example, the users could think it's related to that bug. 
Make it easier …
> docs: enhance the example of PushSecret/ClusterPushSecret

- pkg/generator/acr/acr.go
Fixes https://github.com/external-secrets/external-secrets/issues/4889
> fix: leaving out managed id is not an invalid config

- apis/externalsecrets/v1/secretstore_onepassword_sdk_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- pkg/provider/onepasswordsdk/client.go
- pkg/provider/onepasswordsdk/client_test.go
SecretStore in onepasswordsdk only allows specifying a vault by its Title, and does not support specifying it by UUID.
For example, the following manifest will result in an error:
https://github.com/external-secrets/external-secrets/blob/cb0d91ed2b124513e62e367efcdd61c41a32f159/pkg/provider/onepasswordsdk/provider.go#L83
```yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata: ...
spec:
provider:
onepasswordSDK:
vault: "aaaaaaaaaaaaa1111111111111" # <- uuid is NG
auth:
serviceAccountSecretRef: ...
```
N/A (No issue created)
- Modified the GetVault function to check for a match against both the Title and UUID of the vault. This allows users to specify the vault using either identifier.
- Added a TestGetVault function to verify that the vault is retrieved correctly …
> [OnePasswordSDKProvider] Enable specifying the vault by UUID

- pkg/provider/gitlab/gitlab.go
Gitlab Group Variables call was not taking environment filtering.
Fixes #3379
Implements environment filtering on gitlab group call
> fix: group variables not taking account of environments

- deploy/charts/external-secrets/Chart.lock
- deploy/charts/external-secrets/Chart.yaml
- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
- deploy/charts/external-secrets/values.schema.json
- deploy/charts/external-secrets/values.yaml
Allows setting the namespace of bitwarden-sdk-server subchart manifests, following release.namespace or overriding with helm value. (see [related PR](https://github.com/external-secrets/bitwarden-sdk-server/pull/44))
No related Issues.
Use last release of subchart that allows setting namespace, add value to values.yaml and values schema.
> feat: allow setting namespace on bitwarden-sdk-server subchart

- deploy/charts/external-secrets/templates/rbac.yaml
today uuid generator API resource is not present in edit or view cluster roles and therefore people with edit or view role can't use them (in contrary to all other generators)
Fixes #5016
I've added uuid in the helm chart role
> fix: add uuid in edit and view clusterroles

- ADOPTERS.md
Add Red Hat OpenShift in Adopters
https://www.redhat.com/en/technologies/cloud-computing/openshift
> Add Red Hat OpenShift in Adopters

- deploy/charts/external-secrets/files/monitoring/grafana-dashboard.json
Improving grafana experience to debug external-secrets status
-
A new widget: 
Note: I am not sure what is the direction you want for the dashboard, do not hesitate to ask me something else! I want to share what we do for ESO operations.
> fix(helm): grafana dashboard: add widget for sum of not ready secrets

- e2e/Dockerfile
This PR bumps the e2e test image digest to the latest version.
the one on main fails to build, [see here](https://github.com/external-secrets/external-secrets/actions/runs/16890686139/job/47852912829): 
```
#9 [builder 5/9] COPY go.mod go.sum ./
#9 DONE 0.0s
#8 [builder 6/9] RUN go mod download && go mod verify
#8 0.057 go: go.mod requires go >= 1.24.6 (running go 1.24.5; GOTOOLCHAIN=local)
#8 ERROR: process "/bin/sh -c go mod download && go mod verify" did not complete successfully: exit code: 1
------
> [builder 6/9] RUN go mod download && go mod verify:
------
failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c go mod download && go mod verify" did not complete successfully: exit code: 1
make[1]: *** [Makefile:65: e2e-image] Error 1
```
> fix: bump image digest to fix e2e tests

- docs/provider/oracle-vault.md
I noticed that the `SecretStore` yaml block in the docs is not properly formatted, so i added the missing yaml tag.
> Fix yaml codeblock for oracle-vault provider docs

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/NOTES.txt
- deploy/charts/external-secrets/templates/_helpers.tpl
- deploy/charts/external-secrets/templates/cert-controller-service.yaml
- deploy/charts/external-secrets/templates/service.yaml
- deploy/charts/external-secrets/templates/servicemonitor.yaml
- deploy/charts/external-secrets/templates/webhook-service.yaml
- deploy/charts/external-secrets/tests/cert_controller_test.yaml
- deploy/charts/external-secrets/tests/service_monitor_test.yaml
- deploy/charts/external-secrets/tests/service_test.yaml
- deploy/charts/external-secrets/tests/webhook_test.yaml
- deploy/charts/external-secrets/values.schema.json
- deploy/charts/external-secrets/values.yaml
Currently the `ServiceMonitor` resources are only rendered if (a) `.serviceMonitor.enabled` is `true` and (b) the Prometheus Operator CRDs are detected.
If either condition is `false` then they are not. When doing an offline render to review the diff (`kluctl`) or deploying as one big server side apply, a user can request the `ServiceMonitor` resources, but not get them.  Furthermore, this behavior is silent.
Fixes #...
This PR adds a ternary option which allows the user to decide how to respond.  A user can select from `skipIfMissing`, `failIfMissing`, or `alwaysRender`.  The default is `skipIfMissing` currently as that is the existing behavior.
> feat(helm): Add control of response to missing prometheus CRDs

- pkg/common/webhook/webhook.go
- pkg/provider/webhook/webhook_test.go
Update the possibility of using the namespace where the external secret was deployed is being added to the webhook provider template: `{{ .remoteRef.namespace }}`.
Fixes #4207
Add the proposed externalsecret namespace field
> feat: add externalsecret namespace for webhook provider

- hack/api-docs/mkdocs.yml
> fix: the api docs are not referencing sshkey generator

- .github/workflows/helm.yml
SonarQube analysis has been failing on main for a while with a low priority warning under security hotspots.
https://sonarcloud.io/project/security_hotspots?id=external-secrets_external-secrets
N/A
It's a pretty straightforward fix as proposed by both SonarQube and as reference in the documentation of how to use secrets in Github Actions, it explicitly mentions to to pass them directly to command line arguments.
https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets
> chore(ci): fix sonarqube security warnings in helm.yml

- Tiltfile
tilt build was failing to rebuild because after server-side apply the image targets weren't re-written. So now, we server-side apply the CRDs and THEN we normal apply the rest of the controllers which correctly updates the images being used.
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
> fix: tilt build was failing to rebuild

- .github/workflows/e2e.yml
- .github/workflows/ok-to-test-managed.yml
- .github/workflows/ok-to-test.yml
- .github/workflows/update-deps.yml
Issue [5271](https://github.com/external-secrets/external-secrets/issues/5271)
This pull request updates the GitHub Actions workflows to use the official `actions/create-github-app-token` action instead of the previously used `tibdex/github-app-token`. The change improves supportability and future compatibility by switching to the recommended action, and also updates input parameter names to match the new action's requirements. The update is applied consistently across all relevant workflow files.
**GitHub Actions migration and input updates:**
* Replaced `tibdex/github-app-token` with `actions/create-github-app-token@v2.1.1` in `.github/workflows/e2e.yml`, `.github/workflows/ok-to-test-managed.yml`, `.github/workflows/ok-to-test.yml`, and `.github/workflows/update-deps.yml`. …
> feat: migrate from tibdex to actions/create-github-app-token

- .github/actions/sign/action.yml
The sbom contains only the libs from the container image, this PR adds all libs (go, python etc).
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
> feat: add missing go sbom

- deploy/charts/external-secrets/README.md
- deploy/charts/external-secrets/templates/deployment.yaml
- deploy/charts/external-secrets/tests/controller_test.yaml
- deploy/charts/external-secrets/values.schema.json
- deploy/charts/external-secrets/values.yaml
Since it's including the entire body `enabled` would have been part of the rendered thing in Kubernetes manifest leading to a potential failure:
```yaml
enabled: true
initialDelaySeconds: 10
periodSeconds: 10
timeoutSeconds: 10
failureThreshold: 10
successThreshold: 10
httpGet:
path: /healthz
port: "8080"
scheme: HTTP
```
`enabled: true` here is invalid. We need an internal field that can be used for entire field parsing here:
```yaml
{{- if .Values.livenessProbe.enabled }}
livenessProbe:
{{- toYaml .Values.livenessProbe.spec | nindent 12 }}
{{- end }}
```
Note that `spec.template.spec.containers[0].livenessProbe.httpGet.port` should still be the path and not `spec.template.spec.containers[0].livenessProbe.spec.httpGet.port`. Because that would mean it includes `spec`.
Fixes #...
How do …
> fix: liveness probe would include invalid value `enable`

- apis/externalsecrets/v1/secretstore_gcpsm_types.go
- config/crds/bases/external-secrets.io_clustersecretstores.yaml
- config/crds/bases/external-secrets.io_secretstores.yaml
- deploy/crds/bundle.yaml
- docs/api/spec.md
- docs/provider/google-secrets-manager.md
- docs/snippets/full-secret-store.yaml
- pkg/provider/gcp/secretmanager/client.go
- pkg/provider/gcp/secretmanager/client_test.go
- pkg/provider/gcp/secretmanager/fake/fake.go
When using External Secrets Operator (ESO) with Google Secret Manager (GSM), fetching a secret fails if the secret has multiple versions where the latest version is destroyed but an older version is still enabled.
Example: a secret has versions 1 (enabled) and 2 (destroyed). ESO appears to check both versions/latest and the latest active version; the call against versions/latest fails because that points to the destroyed v2, causing the whole fetch to fail even though v1 is valid.
Fixes #5129 
Implement [`GetSecret`](https://github.com/itaispiegel/external-secrets/blob/a2f3ac985192bc9795f7cd709368d26f2b1118e7/pkg/provider/gcp/secretmanager/client.go#L481) to fetch latest enabled secret, if the latest is destroyed or disabled.
> feat(gcp): get latest enabled secret

- deploy/charts/external-secrets/templates/deployment.yaml
`address` is not part of the allowed fields of the livenessProbe section (`kubectl explain Pod.spec.containers.livenessProbe`)
We now exclude the `address` field from the dict.
Another option if you prefer would be to move the `address` key one level above (`.livenessProbe` instead of `.livenessProbe.spec`) so we can keep templating the full `.livenessProbe.spec`.
> fix(charts): exclude 'address' key from livenessProbe definition

- pkg/provider/gcp/secretmanager/workload_identity_federation.go
GCP Workload Identity Federation authentication fails when `serviceAccountRef` is specified.
Fixes #5388 
The issue is caused due to the incorrect initialization of the WIF audience.
> fix: issue-5388: Fixes GCP Workload Identity Federation auth issue

- docs/examples/bitwarden.md
- docs/snippets/bitwarden-secret-store.yaml
- docs/snippets/bitwarden-secret.yaml
Extending documentation
I created a SSH Key in Bitwarden Password Manager.
Then, I failed to be able to deploy my ssh private key with the 4 example (Cluster)SecretStore on this [guide](https://external-secrets.io/latest/examples/bitwarden/).
The values for the ssh key generated are under `$.data.sshKey.privateKey`, `$.data.sshKey.publicKey` and `$.data.sshKey.keyFingerprint`
None.
This PR proposes to add a new (Cluster)SecretStore named `bitwarden-ssh` in the documentation guide related to Bitwarden Password Manager, and includes a secret example as well.
git commit is `docs: extend bitwarden example and integration to accomodate the ssh key feature`
> docs: extend bitwarden example and integration to accomodate the ssh key feature
