external-secrets/external-secrets

.github/PAUL.yaml
Just adding paul config file to start using it for managing the project.
=> Add paul config file

.github/workflows/ci.yml, hack/api-docs/mkdocs.yml
Fixes small typo and uses cache setup by CI job over cache from golangci action.
=> Cleanup lint stage

.github/workflows/docs.yml
=> Add cname to docs action

.github/workflows/ci.yml, SECURITY.md, dependabot.yml
This PR adds a dependabot config and a security policy
=> security policy & dependabot

deploy/charts/external-secrets/Chart.yaml, deploy/charts/external-secrets/templates/rbac.yaml
=> Add RBAC for leader election in the helm chart

pkg/controllers/externalsecret/externalsecret_controller.go
Fixes #118. I tested the code locally, and the implementation seems straightforward. However, it was unclear to me if the tests should be expanded to add explicit tests for the cluster secret store resource kind.
=> Add support for cluster secret store with the vault provider

pkg/template/template.go, pkg/template/template_test.go
fixes #126
TIL from [text/template](https://golang.org/pkg/text/template/)
> [...] a method [or func] must have one [...] or two return values, the second of which is an error.
If it has two and the returned error is non-nil, execution terminates
and an error is returned to the caller as the value of Execute.
I changed signatures of the template functions and return all errors back to the controller. I.e. if an template error occurs it will be logged and any further processing of the secret is stopped immediately (and the error is applied to the status condition).
=> fix(tpl): fail on parse/execute error

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/util.go, pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/aws/secretsmanager/secretsmanager.go, pkg/provider/aws/util/errors.go
=> fix: update condition when error message changes

.github/PAUL.yaml
Gabi will be more active here and I want to add her to the maintainers, so she can also use the bot :)
=> chore: Add Gabi to maintainers

docs/contributing-devguide.md
- fix make commands to match existing makefile
- add additional description for Python users
=> docs: fix developer guide commands

deploy/charts/external-secrets/Chart.yaml
I wanna check out release workflow triggering and also release a chart with the [153](https://github.com/external-secrets/external-secrets/pull/153) fix
=> chore: Bump chart and app versions

docs/api-overview.md, docs/guides-multi-tenancy.md, docs/snippets/namespace-permitted-annotation.yaml, docs/snippets/provider-aws-access.md, docs/spec.md
#163: remove permitted annotation from the docs.
=> fix(docs): remove permitted annotation from docs

pkg/provider/aws/secretsmanager/secretsmanager_test.go
When I refactor `parameterstore_test.go`, I found that one of the fields was `rr`, so I changed it to `remoteRef` for better readability. I also just changed the naming of this file for consistency, and the design docs specify this field as `remoteRef`.
[1] https://github.com/external-secrets/external-secrets/blob/main/design/design-crd-spec.md#external-secret
=> Rename remoteRef field name

deploy/charts/external-secrets/Chart.yaml
Bumping version to include template fix
=> chore: bumping version for release

design/design-crd-spec.md, docs/snippets/full-secret-store.yaml, docs/snippets/vault-approle-store.yaml, docs/snippets/vault-jwt-store.yaml, docs/snippets/vault-kubernetes-store.yaml, docs/snippets/vault-ldap-store.yaml, docs/snippets/vault-token-store.yaml
=> docs: Fix typo apiVerson

docs/provider-azure-key-vault.md, docs/snippets/azkv-credentials-secret.yaml, docs/snippets/azkv-external-secret.yaml, docs/snippets/azkv-secret-store.yaml
As an amendment for[ this PR](https://github.com/external-secrets/external-secrets/pull/22/) , few examples and README docs are added for the azure KV provider
=> add README docs and yaml snippets for azure keyvault provider

README.md
Removing 'being implemented notice' and updating docs
=> Update Azure kv link

.github/workflows/ci.yml, .github/workflows/e2e.yml, e2e/run.sh, e2e/suite/aws/secretsmanager.go, e2e/suite/gcp/gcp.go, e2e/suite/gcp/util.go, e2e/suite/import.go, go.sum, pkg/provider/gcp/secretmanager/secretsmanager.go
Exported CloudPlatformRole to also use it in the tests. Also added a simple e2e test for GCP already using real infra. Added GCP_SM_SA_JSON as env var coming from the CI secrets.
=> tests: additional e2e tests

.github/workflows/e2e.yml
=> fix: no need to export secret

e2e/suite/aws/secretsmanager.go
Adding one more e2e test to aws and testing ok-to-test workflow
=> Add inner key e2e test to aws

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/metrics.go, pkg/controllers/externalsecret/util.go, pkg/controllers/secretstore/secretstore_controller.go
https://github.com/ContainerSolutions/externalsecret-operator/issues/136
I found this issue in a previous version of the repo and I thought it would be a good way to learn about the project
=> Added doc strings and comments for the controllers package

README.md
Add mention to slack on readme.
=> Add mention to slack on readme

.github/codecov.yml, docs/provider-google-secrets-manager.md, e2e/suite/aws/secretsmanager.go, e2e/suite/gcp/gcp.go, pkg/controllers/externalsecret/externalsecret_controller.go, pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/aws/secretsmanager/secretsmanager.go, pkg/provider/azure/keyvault/keyvault.go, pkg/provider/fake/fake.go, pkg/provider/gcp/secretmanager/secretsmanager.go, pkg/provider/gcp/secretmanager/secretsmanager_test.go, pkg/provider/provider.go, pkg/provider/schema/schema_test.go, pkg/provider/vault/vault.go
Fixes #210 and Fixes #211
I am also reducing codecov precision so it does not mark every PR as red. Fixes #168
=> feat: add property feature to gcp

docs/api-clustersecretstore.md, docs/snippets/full-cluster-secret-store.yaml
This updates the docs referencing wrong file in issue #226
=> docs: update api-clusterSecretstore example

docs/deprecation-policy.md, hack/api-docs/mkdocs.yml
This PR adds the deprecation policy docs.
Let's discuss the details in the next sync.
Closes #188
=> docs: add deprecation policy

.github/workflows/e2e.yml, e2e/run.sh, e2e/suite/azure/azure.go, e2e/suite/azure/util.go, e2e/suite/import.go, go.mod
Initial e2e test setup for azure
=> test: e2e setup for azure

.github/PAUL.yaml
Adding ricardo as maintainer since he is pairing with me and helping with tasks and also helping with getting more people involved in the project :)
=> chore: add ricardo as maintainer

go.mod, main.go
This PR lets users set a loglevel from the command line.
I am a little hesitant in adding this option as environment variable, too as it increases the api surface. For now i think it's enough to have just the cli flags.
=> feat: allow setting loglevel

Makefile
Corrected command for installing lint
=> minor correction in lint warning

docs/snippets/azkv-secret-store.yaml
=> fix: missing key in store snippet

pkg/controllers/externalsecret/externalsecret_controller.go
fixes #288
This PR ensures that the provider is properly `.Close()`d
=> fix: resource leak

main.go, pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_test.go, pkg/controllers/externalsecret/suite_test.go
fixes #299
The metav1.Duration is actually not `nil` but contains a `Duration=0`.
=> fix: zero refreshInterval shouldn't sync

e2e/Makefile, e2e/e2e_test.go, e2e/framework/addon/chart.go, e2e/framework/addon/eso.go, e2e/framework/addon/vault.go, e2e/framework/framework.go, e2e/framework/testcase.go, e2e/framework/util/util.go, e2e/k8s/vault-config/configure-vault.sh, e2e/k8s/vault-config/vault-policy-es.hcl, e2e/k8s/vault.values.yaml, e2e/kind.yaml, e2e/suite/vault/provider.go, e2e/suite/vault/vault.go, go.mod, go.sum
fixes #208 
add e2e tests to test vauth authentication with:
Also setup vault with TLS.
=> feat: add vault e2e tests

deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/deployment.yaml, deploy/charts/external-secrets/values.yaml
Updated helm chart so that it allows setting priorityClassName
=> Allow setting priorityClassName

docs/provider-google-secrets-manager.md, docs/spec.md
Adding docs for GCP Workload Identity
=> docs: gcp workload identity

apis/externalsecrets/v1alpha1/secretstore_gitlab_types.go, deploy/crds/external-secrets.io_clustersecretstores.yaml, deploy/crds/external-secrets.io_secretstores.yaml, docs/provider-gitlab-project-variables.md, docs/snippets/gitlab-secret-store.yaml, docs/spec.md, pkg/provider/gitlab/gitlab.go
=> feat: specify GitLab url to connect to

docs/contributing-devguide.md
Add more steps to the dev guide. Specially envtest that is a constant point of support given.
=> docs: add more steps to dev guide

pkg/controllers/externalsecret/externalsecret_controller_test.go
This PR just adds an test to verify `spec.dataFrom` and `template` works as expected.
relates to #370
=> fix: add explicit test for using dataFrom + template

.github/workflows/ok-to-test.yml
I am a bit short on time, and need this just to check some PRs
Gonna open a issue to re upgrade and figure out stuff
=> rolling back slash command action version for now

.github/workflows/e2e.yml
A bit hard to test. Maybe the event names changed. Trying this to see.
=> fix: e2e dispatch

.github/workflows/e2e.yml
Stop checking events at all to see if it works
=> fix: e2e test, stop checking event

.github/workflows/e2e.yml
Still trying to see what is causing the steps to be skipped
=> fix: e2e tests, keep event check, remove contains

.github/workflows/e2e.yml
=> fix: e2e typo

.github/workflows/e2e.yml
Leaving only event check in the if
=> fix: e2e, leave only event check

e2e/framework/testcase.go, e2e/suite/alibaba/alibaba.go, e2e/suite/aws/secretsmanager.go, e2e/suite/azure/azure.go, e2e/suite/common/common.go, e2e/suite/gcp/gcp.go, e2e/suite/gitlab/gitlab.go, e2e/suite/oracle/oracle.go, e2e/suite/vault/vault.go, pkg/controllers/externalsecret/externalsecret_controller_test.go
Tests to check if use external secret name if target secret name isn't defined
Close #350
=> No target name unit and e2e tests

.github/workflows/ok-to-test.yml
Working on upgrading slash-command-dispatch to v2.3.0
Issue: [#378](https://github.com/external-secrets/external-secrets/issues/378)
=> WIP upgrading slash-command-dispatch 

.github/workflows/ok-to-test.yml
Only maintainers can trigger e2e
=> fix: maintainers can trigger e2e

.github/workflows/ci.yml
=> fix: expose sonar token

sonar-project.properties
Exclude more files from coverage
=> exclude more files from coverage

.github/workflows/ci.yml
Cant run sonar on forks for now
=> fix: cant run sonar on forks for now

sonar-project.properties
Watch tests in pkg instead of .
=> watch tests in pkg instead of .

.github/workflows/ci.yml
=> fix: gh actions syntax

.github/workflows/ci.yml
=> fix: use sonar token as env var

sonar-project.properties
=> fix: exclude ./e2e/**,./apis/**

sonar-project.properties
=> fix: exclusion paths

sonar-project.properties
Exclude fake mocks from sonar scan
=> fix: exclude fake client mocks

.github/PAUL.yaml
Update paul.yaml with more maintainers
=> update paul.yaml with more maintainers

deploy/charts/external-secrets/Chart.yaml
=> Bumping chart version v0.3.6

e2e/Makefile
Add --load to docker build so kind is able to get it for e2e tests
=> Add --load to docker build

.github/workflows/e2e.yml
Fix obj name in ok-to-test PR report 
fixes #426
=> Fix obj name in ok-to-test PR report

.github/workflows/e2e.yml
Rollback actions/github-script to v1 until we figure it out.
=> Rollback actions/github-script until we figure it out

.github/workflows/e2e.yml
Assume check is not array in report back script
=> Assume check is not array

docs/snippets/template-from-secret.yaml
=> fixes "template" spelling

docs/guides-using-latest-image.md, hack/api-docs/mkdocs.yml
Adds guide to use upstream main image
=> Adds guide to use upstream main image

pkg/provider/aws/secretsmanager/secretsmanager.go, pkg/provider/aws/secretsmanager/secretsmanager_test.go
When using `dataFrom` nested json values caused an error.
fixes #510
=> fix: supported nested json with dataFrom

deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/deployment.yaml, deploy/charts/external-secrets/values.yaml, main.go, pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/suite_test.go
addresses #330 - enables the operator to deal with more than 1 reconcile concurrently at a time
=> add concurrent flag to allow more reconciles at the same time

.github/PAUL.yaml
Add rodrmartinez as maintainer
=> Add rodrmartinez as maintainer

go.mod
=> mod: Upgrade to golang 1.17

.github/workflows/e2e-managed.yml, .github/workflows/e2e.yml, .github/workflows/ok-to-test-managed.yml, .gitignore, Makefile, docs/provider-google-secrets-manager.md, e2e/Makefile, e2e/e2e_test.go, e2e/framework/addon/eso.go, e2e/framework/eso.go, e2e/framework/framework.go, e2e/framework/testcase.go, e2e/framework/util/util.go, e2e/run.sh, e2e/suite/gcp/gcp.go, e2e/suite/gcp/provider.go, e2e/suite/gcpmanaged/gcpmanaged.go, e2e/suite/import.go, e2e/suite/vault/vault.go, terraform/gcp/eso_gcp_modules/gke/main.tf, terraform/gcp/eso_gcp_modules/gke/variable.tf, terraform/gcp/eso_gcp_modules/network/main.tf, terraform/gcp/eso_gcp_modules/network/variable.tf, terraform/gcp/main.tf, terraform/gcp/provider.tf, terraform/gcp/provider_variables.tf, terraform/gcp/variable.tf
=> Initial setup for wi gcp testing

apis/externalsecrets/v1alpha1/secretstore_vault_types.go, apis/externalsecrets/v1alpha1/zz_generated.deepcopy.go, deploy/crds/external-secrets.io_clustersecretstores.yaml, deploy/crds/external-secrets.io_secretstores.yaml, e2e/suite/vault/provider.go, pkg/provider/vault/vault.go, pkg/provider/vault/vault_test.go
* Backwards compatible change
* Added tests to check for a range of possible combinations for paths
(Closes: #513)
=> Optional path for Vault SecretStore

e2e/suite/vault/vault.go
The same auth composition was used several times
=> fix(e2e): use correct auth compsition

README.md, docs/provider-webhook.md, docs/spec.md, hack/api-docs/mkdocs.yml
webook docs were missing in the sidebar
=> fix(docs): webhook docs weren't linked properly

README.md
Add EladGabay to Oracle Vault community maintained table
=> Add EladGabay to Oracle Vault community maintained table

README.md
Promoting GCP to stable and trying new commands on the PR
=> chore: promote gcp to stable

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_test.go
=> Optimise patching so as changes only happen with something changes

.github/workflows/e2e-managed.yml
testing e2e managed workflow..
=> chore: test e2e

e2e/framework/addon/eso.go, terraform/aws/variables.tf
=> chore: test e2e-managed

.github/workflows/e2e-managed.yml
=> chore: test e2e managed

.github/workflows/e2e-managed.yml
=> chore: test e2e / dynamic checks

.github/workflows/e2e-managed.yml
=> chore: test e2e dynamic check

docs/contributing-process.md
=> add e2e test workflow docs

e2e/suite/azure/azure_cert.go, e2e/suite/azure/azure_key.go, e2e/suite/azure/azure_secret.go, e2e/suite/azure/provider.go
Fixes #207
This PR adds tests for keyvault type=cert and type=key secret types.
=> [azure] add e2e tests for type=cert and type=key

deploy/charts/external-secrets/Chart.yaml
=> chore: bump chart to v0.4.0

.github/workflows/release.yml
=> Now really fix docs versioning

docs/provider-akeyless.md, docs/provider-aws-parameter-store.md, docs/provider-aws-secrets-manager.md, docs/provider-azure-key-vault.md, docs/provider-gitlab-project-variables.md, docs/provider-google-secrets-manager.md, docs/provider-hashicorp-vault.md, docs/provider-ibm-secrets-manager.md, docs/provider-oracle-vault.md, docs/provider-webhook.md, docs/provider-yandex-lockbox.md, docs/snippets/provider-aws-access.md, docs/snippets/vault-approle-store.yaml, docs/snippets/vault-jwt-store.yaml, docs/snippets/vault-kubernetes-store.yaml, docs/snippets/vault-ldap-store.yaml, docs/snippets/vault-token-store.yaml
Improving provider documentation with Notes on what to do if using ClusterSecretStore
=> Adding notes on configuring ClusterSecretStores for every provider

.github/workflows/e2e-managed.yml
another attempt - need to merge this in order to be able to test.
=> fix: github-script

ADOPTERS.md
\*edit\* by @moolen 
paul is very rude sometimes, sorry for that :/
=> add company to Adopters

docs/guides-templating.md, docs/spec.md
quick fix for documentation to render.
We need to allow the missing file later on.
=> Fixing documentation render for template v2

docs/api-overview.md
=> Fix typo in api-overview

docs/guides-controller-class.md
Typo correction: replace `workloard` by `workload`
=> controller documentation correction

docs/eso-blogs.md, docs/eso-demos.md, docs/eso-talks.md, docs/spec.md, hack/api-docs/mkdocs.yml
Add links to external resources like talks, blogs, demos, etc.
As discussed @gusfcarvalho.
Good for SEO, crossposting, and for incentivizing people to talk about the project.
=> docs: add links to external resources

.github/PAUL.yaml
Fixes #801 
At least for a while.
=> Updating PAUL.yaml to allow 30 PRs

pkg/provider/yandex/lockbox/client/grpc/grpc.go
Fixes the issue: https://github.com/external-secrets/external-secrets/issues/833
=> Yandex Lockbox Connection Leaks

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile
- sign images using cosign
It signs the image when it builds the main branch and when doing a release
Fixes: #731 
cc @moolen
=> sign images using cosign

config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml, deploy/crds/bundle.yaml
seems that #542 was missing `conversionStrategy`
=> fix: update CRDs

.github/workflows/ci.yml, .github/workflows/release.yml
follow up of #845 which was missing to install cosign 
My apologies for breaking the pipeline.
cc @moolen @knelasevero
=> add missing install of cosign in the CIs pipelines

docs/eso-blogs.md
How to manage secrets in OpenShift using Vault and External Secrets Operator blog reference
=> How to manage secrets in OpenShift using Vault and External Secrets Operator blog reference

docs/eso-demos.md
Add Balkrishna Pandey demo to external resources
=> Add Balkrishna Pandey demo

.github/workflows/e2e-managed.yml
=> Fixing setup-gcloud version

.github/workflows/e2e-managed.yml
=> Setting version to v0 as main is not yet available

docs/provider-ibm-secrets-manager.md, docs/snippets/ibm-es-types.yaml, pkg/provider/ibm/provider.go, pkg/provider/ibm/provider_test.go
https://github.com/external-secrets/external-secrets/issues/847
=> Add public_cert support

.github/workflows/helm.yml, deploy/charts/external-secrets/templates/cert-controller-service.yaml, deploy/charts/external-secrets/templates/cert-controller-serviceaccount.yaml, deploy/charts/external-secrets/templates/validatingwebhook.yaml, deploy/charts/external-secrets/templates/webhook-secret.yaml, deploy/charts/external-secrets/templates/webhook-service.yaml, deploy/charts/external-secrets/templates/webhook-serviceaccount.yaml, e2e/framework/addon/eso.go, e2e/suite/aws/parameterstore/parameterstore_managed.go, e2e/suite/aws/secretsmanager/secretsmanager_managed.go, e2e/suite/gcp/gcp_managed.go, pkg/controllers/secretstore/common.go, pkg/provider/gcp/secretmanager/secretsmanager.go
Reimplementation of #842 only for GCP Provider
Fixes #818 
Fixes #834
=> Adding mutexes only for GCP provider

docs/provider-aws-secrets-manager.md
=> Fix invalid json in documentation

Makefile, e2e/framework/testcase.go, e2e/suite/akeyless/provider.go, e2e/suite/alibaba/provider.go, e2e/suite/aws/parameterstore/find_by_name.go, e2e/suite/aws/parameterstore/find_by_tags.go, e2e/suite/aws/parameterstore/parameterstore.go, e2e/suite/aws/parameterstore/parameterstore_managed.go, e2e/suite/aws/parameterstore/provider.go, e2e/suite/aws/secretsmanager/provider.go, e2e/suite/aws/secretsmanager/secretsmanager.go, e2e/suite/aws/secretsmanager/secretsmanager_managed.go, e2e/suite/azure/provider.go, e2e/suite/common/common.go, e2e/suite/common/find_by_name.go, e2e/suite/common/find_by_tags.go, e2e/suite/gcp/gcp.go, e2e/suite/gcp/provider.go, e2e/suite/gitlab/provider.go, e2e/suite/oracle/provider.go, e2e/suite/template/provider.go, e2e/suite/vault/provider.go, e2e/suite/vault/vault.go, pkg/find/find.go, pkg/provider/aws/parameterstore/fake/fake.go, pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/aws/secretsmanager/secretsmanager.go, pkg/provider/vault/vault.go, pkg/utils/utils.go, pkg/utils/utils_test.go
GetAllSecrets implementation for aws providers.
TODO:
=> feature: aws getallsecrets

docs/snippets/full-secret-store.yaml
=> Removing namespace references from full-secret-store.yaml

docs/provider-kubernetes.md
=> Improves kubernetes provider examples documentation

.github/workflows/release.yml
=> adding setup go to release CI

README.md
=> Updates README.md links to point to latest version.

pkg/provider/vault/vault.go, pkg/provider/vault/vault_test.go
=> Removing Path trimming from hashicorp Vault

pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/aws/parameterstore/parameterstore_test.go, pkg/provider/aws/secretsmanager/secretsmanager.go, pkg/provider/aws/secretsmanager/secretsmanager_test.go
=> Fixes gjson behavior for aws SecretsManager and ParameterStore

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_test.go
=> Adding owner reference to the external secret name.

cmd/root.go, cmd/webhook.go, deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/validatingwebhook.yaml, deploy/charts/external-secrets/templates/webhook-deployment.yaml, deploy/charts/external-secrets/templates/webhook-service.yaml, deploy/charts/external-secrets/values.yaml, e2e/framework/addon/eso.go
* hostNetwork for webhook pod
* FailurePolicy for validatingwebhook definition
* Changed webhook port to 443
Fixes #944
=> Adding some options for webhook deployment

pkg/controllers/externalsecret/externalsecret_controller.go
=> Checking if condition is not nil before using it.

docs/eso-blogs.md
Add a link to a blog article I wrote about ESO and IBM Secrets Manager.
=> Propose a blog post about ESO and IBM Secrets Manager

.github/workflows/dlc.yml, Makefile, deploy/charts/external-secrets/README.md
=> Adding dependency license checks in CI

Makefile, deploy/charts/external-secrets/templates/validatingwebhook.yaml, deploy/crds/bundle.yaml
fixes #997
Relatively naive sed replace to 'helmify' the CRDs, feel free to suggest an alternative
approach.
=> fix(helm-chart): remove caBundle and set name/namespace

apis/externalsecrets/v1beta1/externalsecret_types.go, config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml, config/crds/bases/external-secrets.io_externalsecrets.yaml, deploy/crds/bundle.yaml
=> Making spec.target Optional

README.md
=> chore: update main doc links

pkg/controllers/externalsecret/externalsecret_controller.go
Secret client is created only if we are going to refresh. This skip an unnecessary check/request in the case we are not going to do anything.
(hello guys, it's me again 👋 :P )
=> chore: improve external secret reconciliation sequence

pkg/provider/vault/vault.go, pkg/provider/vault/vault_test.go
I noticed that a panic could be caused if a secret was configured with a path that didn't exist in vault. This was due to the vault client returning a nil secret on a 404. This PR traps that condition and returns an error.
=> vault provider: avoid a panic if secret not found in vault

docs/stability-support.md
=> chore: missing k8s provider

pkg/controllers/externalsecret/suite_test.go, pkg/provider/gitlab/gitlab.go, pkg/provider/gitlab/gitlab_test.go, pkg/provider/oracle/oracle.go, pkg/provider/oracle/oracle_test.go
Simple validation for Gitlab and Oracle
Fixes #865
Fixes #862
=> Implement ValidateStore for Gitlab and Oracle providers

go.mod, go.sum
chore: bump crypt
Fixes  CVE-2022-27191
=> chore: bump crypt

docs/eso-demos.md, docs/spec.md
Adding demo about Secret Store CSI Driver and ESO made by DO folks
=> docs: eso-csi-talk-DO

docs/eso-blogs.md
Add a link to a blog article I wrote about getting started using ESO with AWS Secrets Manager.
=> Propose a blog post about ESO and AWS Secrets Manager

pkg/provider/akeyless/akeyless_test.go, pkg/provider/alibaba/kms.go, pkg/provider/alibaba/kms_test.go
=> Implemented ValidateStore function for Alibaba Provider

apis/externalsecrets/v1beta1/externalsecret_types.go, config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml, config/crds/bases/external-secrets.io_externalsecrets.yaml, deploy/crds/bundle.yaml, docs/provider-azure-key-vault.md, docs/snippets/azkv-datafrom-external-secret.yaml, docs/snippets/azkv-external-secret.yaml, pkg/provider/azure/keyvault/keyvault.go, pkg/provider/azure/keyvault/keyvault_test.go
New feature to retrieve either a single tag or all tags from a secret in the Azure Keyvault.
=> azkv tag feature

Makefile
=> Use gsed on macos.

Makefile, docs/provider-ibm-secrets-manager.md, docs/snippets/ibm-es-types.yaml, pkg/provider/ibm/provider.go, pkg/provider/ibm/provider_test.go
https://github.com/external-secrets/external-secrets/issues/1159
=> Add support for IBM Secrets Manager's Private Certificate 

pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go, pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
Fixed by converting with `LabelSelectorAsSelector` instead of `LabelSelectorAsMap`.
The added test covers the case of the issue described in #1155: matchExpressions + In + multiple values.
Fixes #1155
=> fix: correctly convert matchExpressions to labelSelector

ADOPTERS.md
Update adopters.md: add openclassrooms
=> Update adopters.md: add openclassrooms

ADOPTERS.md
=> Epidemic Sound

ADOPTERS.md
We are using External Secrets at Petco. It'd be nice to feature in the adopters list.
=> add Petco as adopter

deploy/charts/external-secrets/Chart.yaml
=> release 0.5.4

pkg/provider/vault/vault.go
=> fixing panic if using JWT with KubernetesServiceAccountToken

deploy/charts/external-secrets/Chart.yaml
=> fix: bump 0.5.5

pkg/provider/vault/vault.go
=> make sure we check if it is referent during NewClient

ADOPTERS.md
Add Radio France as ES adopter
=> docs: Add radiofrance as adopter

pkg/provider/azure/keyvault/keyvault_test.go
Unit Tests added to have more coverage in the azure Keyvault
Specifically testing to validate the store
=> azkv more unittest coverage

e2e/suites/provider/cases/azure/azure_managed.go, e2e/suites/provider/cases/azure/provider.go, terraform/azure/aks/main.tf, terraform/azure/aks/output.tf, terraform/azure/aks/providers.tf, terraform/azure/aks/variables.tf, terraform/azure/key-vault/main.tf, terraform/azure/key-vault/output.tf, terraform/azure/key-vault/providers.tf, terraform/azure/key-vault/variables.tf, terraform/azure/main.tf, terraform/azure/providers.tf, terraform/azure/resource-group/main.tf, terraform/azure/resource-group/providers.tf, terraform/azure/resource-group/variables.tf, terraform/azure/service-principal/main.tf, terraform/azure/service-principal/output.tf, terraform/azure/service-principal/providers.tf, terraform/azure/service-principal/variables.tf, terraform/azure/variables.tf, terraform/azure/workload-identity/main.tf, terraform/azure/workload-identity/provider.tf, terraform/azure/workload-identity/variables.tf
- Adds terraform module for workload identity e2e tests
- Adds CreateSecretStoreWithWI to azure test suite provider
- Adds azure managed auth test
=> Azure keyvault e2e test

docs/provider-hashicorp-vault.md
Adds a brief note on the `namespace` attribute in the `SecretStore` object.
=> Add a Note for Vault Namespaces

docs/index.md
I've added ESO Twitter Account to How to get involved part of the documentation.
=> Add ESO Twitter Account

docs/eso-demos.md
docs: add devops toolkit video to the docs
=> docs: add devops toolkit video to the docs

deploy/charts/external-secrets/README.md
a small change which corrects helm command.
=> corrected helm install command

docs/guides-templating.md
Remove empty line to keep table in form
=> Fix guides-templating.md typo

.github/PAUL.yaml
Closes #1347 
Temp solution to at least make pauls comments clickable.
=> hardcode version for paul

docs/api-overview.md
Fix a typo in the documentation
=> Fix a typo in the documentation

.github/workflows/e2e.yml, e2e/run.sh
=> Test: e2e env vars

.github/workflows/e2e.yml
=> Fixing: github.actor instead of github.author

deploy/charts/external-secrets/Chart.yaml
This PR bumps the chart version
=> chore: bump helm release

apis/externalsecrets/v1alpha1/secretstore_azurekv_types.go, apis/externalsecrets/v1beta1/secretstore_azurekv_types.go, docs/spec.md
A typo correction. Awesome project anyway :100:
=> typo: (clister) in azurekv_types

docs/snippets/multiline-template-v1-external-secret.yaml
Fix erroneous comment in docs.
=> Fix comment specifying the default engineVersion.

pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/aws/secretsmanager/secretsmanager.go
Fixes https://github.com/external-secrets/external-secrets/issues/1448.
=> Fix AWS attr. dot check off-by-one error

docs/guides-datafrom-rewrite.md
Adding an `a` to `conditional` and changing the choice of preposition to the docs
This is an amazing feature, by the way! Waited for it patiently 😄
=> Update guides-datafrom-rewrite.md for typo

docs/guides-multi-tenancy.md
Fixes a minor typo in the docs.
=> Small typo fix guides-multi-tenancy.md

deploy/charts/external-secrets/templates/webhook-secret.yaml, deploy/charts/external-secrets/templates/webhook-service.yaml
Remove unnecessary spaces in helm chart.
=> Remove unnecessary space before a colon

docs/eso-blogs.md
I've added my blog post about ESO and integration with AWS Secrets Manager to this page.
Signed-off-by: Emin Alemdar <77338109+eminalemdar@users.noreply.github.com>
=> Adding my published blog post

README.md
Updated Readme with warnings and workaround
Signed-off-by: Gustavo Fernandes de Carvalho <gusfcarvalho@gmail.com>
=> Add warning due to DNS transfer

deploy/charts/external-secrets/Chart.yaml
prep release `0.6.0-rc1`
fixes #1511
=> chore: bump 0.6.0-rc1

README.md
Signed-off-by: Lucas Severo Alves <lucassalves65@gmail.com>
=> DNS transfer to CNCF went ✅, we can remove notice

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_test.go, pkg/controllers/externalsecret/metrics.go
New metric to monitor the duration time to reconcile an External Secret
=> New Duration Metric

README.md
this change fixes some broken links in the README document
=> fix:broken links in README

docs/guides/ownership-deletion-policy.md
Signed-off-by: Sebastián Gómez <sebastiangomezcorrea@gmail.com>
=> Updated the right path to the field

ADOPTERS.md
We use External Secrets Operator in our clusters at Voiceflow!
Signed-off-by: Xavientois <34867186+Xavientois@users.noreply.github.com>
=> Add Voiceflow to ADPOTERS file

docs/index.md
Signed-off-by: Jason Field <Jason@avon-lea.co.uk>
Note: While I know hacktoberfest is going on please feel free to ignore this from it as I don't want you to think this is spammy (it just took me 1 more click than I would have liked to find the day of the meeting) 
Also Odd week is interesting, is that odd week of the month or odd week of the year? ;)
=> Include the day of the week for the meeting

docs/eso-blogs.md
I have added my new published blog post about ESO.
Signed-off-by: Emin Alemdar <77338109+eminalemdar@users.noreply.github.com>
=> Updated with a new blog post

docs/guides/ownership-deletion-policy.md
Signed-off-by: Chris B <chris@banks.cx>
=> docs: fix typo in ownership-deletion-policy

pkg/provider/oracle/oracle.go
addresses https://github.com/external-secrets/external-secrets/issues/893
=> Implement oracle validator

ADOPTERS.md
Signed-off-by: Byungjin Park (Claud) <posquit0.bj@gmail.com>
=> Add DaangnPay to ADOPTERS.md

docs/eso-blogs.md, docs/eso-demos.md
Signed-off-by: Sebastián Gómez <sebastiangomezcorrea@gmail.com>
=> Link to video was broken

e2e/go.mod, e2e/go.sum, go.mod, go.sum
Bump dependencies
#1734 #1735 #1736 #1737 #1738
=> chore: bump dependencies

docs/introduction/stability-support.md, docs/provider/gitlab-variables.md, hack/api-docs/mkdocs.yml, pkg/provider/gitlab/gitlab.go
Small documentation updates/fixes related to the gitlab provider.
Signed-off-by: Dominik Zeiger <dominik@zeiger.biz>
=> gitlab: small documentation updates

Makefile
=> fix boringssl release

docs/api/secretstore.md
Signed-off-by: czomo <tomaszjdul@gmail.com>
=> fix: Docs SecretStore link do guides

docs/eso-talks.md
I've added the talk we have delivered with Ben Gurney at Kubernetes Community Days UK 2022 conference.
Signed-off-by: Emin Alemdar <77338109+eminalemdar@users.noreply.github.com>
=> Added KCD UK 2022 talk

e2e/go.mod, e2e/go.sum, go.mod, go.sum
=> chore:bumps

.github/workflows/release.yml
=> fixing docs release

e2e/go.mod, e2e/go.sum, go.mod, go.sum
=> chore: bump golang-jwt

README.md, docs/introduction/stability-support.md
=> Fixing links and adding stability support for 0.7.x

docs/provider/hashicorp-vault.md, docs/snippets/vault-pushsecret.yaml, pkg/provider/vault/vault.go, pkg/provider/vault/vault_test.go
=> :bug: Fixes vault PushSecret logic

pkg/provider/vault/fake/vault.go, pkg/provider/vault/vault.go, pkg/provider/vault/vault_test.go
=> :sparkles: Implements Deletion policy for Hashicorp vault.

docs/eso-blogs.md
I've added my new blog post about Push Secret feature.
Signed-off-by: Emin Alemdar <77338109+eminalemdar@users.noreply.github.com>
=> Added my new blog post

docs/introduction/stability-support.md, e2e/suites/provider/cases/azure/azure_secret.go, e2e/suites/provider/cases/azure/provider.go, pkg/provider/azure/keyvault/keyvault.go
This PR allows using referent auth with the azure provider. Towards #961 
TODO:
=> feat: implement azure referent auth

e2e/go.mod, e2e/go.sum, go.mod, go.sum
=> chore: bumps

.github/workflows/rebuild-image.yml
=> fixing image rebuild pipeline

e2e/framework/addon/eso.go, hack/helm.generate.sh, pkg/provider/vault/vault.go
=> Fixing PushSecret CRD generation

docs/snippets/full-cluster-secret-store.yaml
Add Oracle provider
Signed-off-by: Evert Ramos <evert.ramos@gmail.com>
=> Add Oracle provider to full-cluster-secret-store.yaml

pkg/provider/akeyless/akeyless_api.go
=> :bug: fix panic when using jwt without secretRef/saRef

pkg/provider/vault/fake/vault.go, pkg/provider/vault/vault.go, pkg/provider/vault/vault_test.go
=> Included metadataPolicy: Fetch in Hashicorp Vault

docs/eso-talks.md
I've added my recent live session about ESO from the AWS Container from the Couch YouTube channel
Fixes #...
=> Added AWS Containers from the Couch Session

docs/provider/hashicorp-vault.md, docs/snippets/full-cluster-secret-store.yaml, docs/snippets/full-secret-store.yaml
- Update documentation
Fixes #...
=> Fix ExternalSecret key in documentation

docs/provider/aws-parameter-store.md, docs/provider/hashicorp-vault.md, docs/snippets/aws-sm-external-secret.yaml
In the previous PR I had not updated the doc, so here it is.
=> Update docs for metadataPolicy: Fetch 

docs/contributing/roadmap.md, docs/introduction/stability-support.md, hack/api-docs/mkdocs.yml, pkg/provider/azure/keyvault/keyvault.go
=> chore: update docs for release

docs/introduction/stability-support.md
add keeper security provider and promote Kubernetes provider to beta.
=> Add keeper provider to support docs

docs/examples/bitwarden.md, docs/snippets/bitwarden-cli-deployment.yaml, docs/snippets/bitwarden-cli-secrets.yaml, docs/snippets/bitwarden-secret-store.yaml, docs/snippets/bitwarden-secret.yaml, hack/api-docs/mkdocs.yml
I'm just adding a new example in the documentation that show how to use external-secret with bitwarden
=> Add bitwarden example

pkg/provider/gcp/secretmanager/client.go, pkg/provider/gcp/secretmanager/client_test.go
Support MetadataPolicy=Fetch for GCP Secrets Manager
Fixes https://github.com/external-secrets/external-secrets/issues/1874
=> Support MetadataPolicy=Fetch for GCP Secrets Manager

docs/eso-talks.md
Added my talk about External Secrets at FOSDEM '23
None
=> Add FOSDEM23 talk

README.md, docs/index.md
fix: update community meeting time.
=> fix: change meeting time

pkg/provider/vault/vault.go
Fixes #2179 
This should be backported to 0.7 as well if needed. Waiting for #2155 to have a issue template so we can track this.
=> fix: vault logging structure

hack/api-docs/mkdocs.yml
See [issue](https://github.com/external-secrets/external-secrets/issues/2195)
Fixes #2195
=> Fix Google Cloud Secret Manager typo #2195

ADOPTERS.md
Added Mercedes-Benz Tech Innovation to the list of adopters, as we use the project in at least one of our projects.
Benjamin Bertow benjamin.bertow@mercedes-benz.com, Mercedes-Benz Tech Innovation GmbH. https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md
=> Add MBTI as adopter

ADOPTERS.md
PITS Global Data Recovery Services
Fixes #...
=> chore: new adopter

deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
Helm tests are broken on main.
Bumps helm test snapshots
=> bumping helm test snapshots

pkg/generator/vault/vault.go, pkg/generator/vault/vault_test.go
Working towards: https://github.com/external-secrets/external-secrets/pull/2074#issuecomment-1548185300
This PR fixes a simple `nil pointer dereference` error.
=> fix: nil check parameters

ADOPTERS.md
Thanks for this great project, happy to use it!
=> added PHOENIX MEDIA to the list of adopters

docs/provider/azure-key-vault.md
I'm enhancing documentation for Azure Workload Identity configuration.
Fixes #2436
- ~[ ] My changes have reasonable test coverage~
=> enhance azure workload identity documentation

docs/contributing/roadmap.md, docs/introduction/stability-support.md
This PR is the preparation for the 0.9 release in #2440.
=> chore: update roadmap status and version support

docs/guides/ownership-deletion-policy.md
:book: refer to support table for `deletionPolicy` support.
=> docs: refer to support table for deletionPolicy support

GOVERNANCE.md, README.md, docs/index.md
Update README.md to add support CyberArk Conjur provider
README.md update
=> Update documentation to add CyberArk Conjur provider

docs/provider/conjur.md
small typo on documentation
[Fixes #...](https://github.com/external-secrets/external-secrets/pull/2473)
=> docs: adjust conjur documentation

pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
I've updated the ClusterExternalSecret controller to start the reconciliation when a namespace is updated to improve usability.  Thank you for your review 🙂 
Fixes https://github.com/external-secrets/external-secrets/issues/2351
Watch Namespaces and kick reconciliations if necessary.
=> Kick ClusterExternalSecret reconciliation when a Namespace is updated

pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
Currently, even though [we specify builder.OnlyMetadata](https://github.com/external-secrets/external-secrets/blob/c08ef00c79a6a5753addeb57b99c3e29408afbff/pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go#L273), we get [a full ExternalSecret](https://github.com/external-secrets/external-secrets/blob/c08ef00c79a6a5753addeb57b99c3e29408afbff/pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go#L115-L119). As [the comment kindly points out](https://github.com/kubernetes-sigs/controller-runtime/blob/56a973c46efe463ef7b5fbecd8495e8378b50d20/pkg/builder/options.go#L103-L133), we should not use `esv1beta1.ExternalSecret` when we cache only metadata, or it may end up consuming more memory and cause race conditions.
I personally think caching only …
=> Use PartialObjectMetadata to get ExternalSecret

pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go, pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
The more detailed context is in [the previous PR](https://github.com/external-secrets/external-secrets/pull/2490), and it fixes ClusterExternalSecret status's failedNamespaces and provisionedNamespaces filed. Thank you for your review!
N/A
Update the two fields regardless of the size of the array.
=> Fix ClusterExternalSecret FailedNamespaces and ProvisionedNamespaces

docs/contributing/release.md
This PR adds some remarks around the release process.
=> docs: update release process

pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller.go
In https://github.com/external-secrets/external-secrets/pull/2486, I've used pagination to list namespaces to "Avoid consuming too much memory".  However, it turned out that when we use the cache client, pagination does not work and we always get the first page (more specifically, `clusterExternalSecrets.Continue` will always be `""`). 
I noticed this behavior while working on another Operator, so I'd like to fix it here as well 🙇 When we access the namespaces through the cache client, we actually access them via the cache the client maintains background, so we don't have to use pagination as long as we access them through pointers in the first place 🤦‍♂️ 
Ref: https://github.com/kubernetes-sigs/controller-runtime/pull/2439
N/A
Stop using pagination
=> Remove paginating namespaces

pkg/provider/ibm/provider.go
Reverts external-secrets/external-secrets#2597
=> Revert "IBM Provider: convert the fetched secret to map to access the properties"

pkg/provider/ibm/provider.go
Fix nil pointer exceptions when fetching a property not available in the secret.
Way of accessing the properties has changed in the latest Secrets Manager provider sdk v2, and ESO has been updated accordingly: https://github.com/external-secrets/external-secrets/pull/2254.
However, customer reported nil pointer exceptions and ESO crashing when accessing properties not available in the secret.
This PR converts the fetched secret to a map and then handles accessing the properties. This is similar to that of how it was accessed prior to the sdk update (https://github.com/external-secrets/external-secrets/blob/1cf7c3a6e31d699c78d0034810a5db21a871e249/pkg/provider/ibm/provider.go#L214-L217)
Based on the current changes in PR, when a non-existing `private_key` property is provided in the …
=>  IBM Provider: convert the fetched secret to map to access the properties

docs/contributing/devguide.md
Reflect recent changes I made and fix a minor problem on the devguide.
N/A
Update the doc.
=> Update the devguide

e2e/framework/eso.go, pkg/controllers/externalsecret/externalsecret_controller.go
=> Fixing  when orphaned secret deletion when target.Name is not set

pkg/provider/ibm/provider.go, pkg/provider/ibm/provider_test.go
Handle cases where secret is destroyed and the property value is nil.
This is an extension of https://github.com/external-secrets/external-secrets/pull/2629
Fixes https://github.com/external-secrets/external-secrets/issues/2632
The changes are made to return an error without crashing the ESO pods when the fetched secret's property is empty.
With this PR, for below externalSecret definition to fetch an arbitrary secret whose status is `Destroyed`:
```
metadata:
name: ibmcloud-secrets-manager-example
spec:
secretStoreRef:
name: ibmcloud-secrets-manager-example
target:
name: test-app-secret
data:
- secretKey: token
remoteRef:
key: arbitrary/87b416b9-efc0-b9c8-d730-4d7c1115fd4b
refreshInterval: 60s
```
results in …
=> IBM Provider: handle case where secret is destroyed

docs/introduction/faq.md
Updating refreshTime and adding lastTransitionTime in doc FAQ, resolving #2555
Fixes #...
=> Update docs FAQ regarding refreshTime and lastTransitionTime

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_test.go
Setting LabelOwner by using namespace/name caused label limits to be reached.
Fixes #2616
Uses hash instead of namespace/name
=> fixing label limits

pkg/controllers/clusterexternalsecret/clusterexternalsecret_controller_test.go
I've found another flaky test in ClusterExternalSecret, so I fixed it 🙇 This should be the last one.
https://github.com/external-secrets/external-secrets/actions/runs/5944791782/job/16122709571
N/A
Deflake it!
=> Fix a ClusterExternalSecret flaky test

docs/provider/aws-pushsecret.md, docs/provider/aws-secrets-manager.md
Enhance documentation on how to use PushSecrets with AWS Secret Manager.
=> docs: add AWS IAM policy for usage with PushSecret

pkg/controllers/externalsecret/externalsecret_controller.go
towards: #2690
This PR fixes a bug where the assignment of `createOrUpdate()` could cause the ExternalSecret to "successfully" reconcile.
=> fix: do not swallow errors when create or update fails

pkg/provider/kubernetes/client.go, pkg/provider/kubernetes/client_test.go
=> fix: ensure to correctly encode binary data as base64

pkg/provider/kubernetes/client.go
=> fix: assign default value to prevent nil panic

ADOPTERS.md
Pets at home is using ESO.
Pets was not on the adopters list
Fixes #...
These changes do not touch code, just a single `md` file
=> [adopters] Adding Pets at home

docs/provider/ibm-secrets-manager.md, docs/snippets/ibm-external-secret-by-name-deprecated.yaml, pkg/constants/constants.go, pkg/provider/ibm/fake/fake.go, pkg/provider/ibm/provider.go, pkg/provider/ibm/provider_test.go
Addresses https://github.com/external-secrets/external-secrets/issues/2717 and note https://github.com/external-secrets/external-secrets/issues/2717#issuecomment-1738429152
=> leverage IBM provider's latest API to get the secret by name

pkg/constants/constants.go, pkg/provider/azure/keyvault/keyvault.go
Towards #2779
This PR fixes an iteration bug in the `GetAllSecrets()` implementation, see comments below.
=> fix: do not iterate on the raw response value

.github/workflows/ci.yml
Fix the linter version for the CI lint job.
Fixes #...
=> fix: also fix the ci jobs linter version

.github/workflows/e2e-managed.yml, docs/contributing/process.md
This PR fixes up small docs issues and tests e2e-managed jobs
=> chore: test e2e-managed & fixup docs

.github/PAUL.yaml
Let's welcome @Skarlso to the Team :tada: :partying_face: :dancers: 
This changes gives you permissions to approve PRs with  `/approve` as well as [to run e2e tests](https://external-secrets.io/latest/contributing/process/#triggering-e2e-tests).
With great power comes great responsibility :smirk: :smile:
=> feat: give @Skarlso maintainer permissions

docs/guides/templating.md
Minor updates to templating docs to assist future readers, caught me out today.
None
Minor documentation update
=> Docs - Minor Note to assist future readers

ADOPTERS.md
* Add Codefresh to list of adopters
N/A
N/A
=> docs: Add Codefresh to list of adopters

apis/externalsecrets/v1alpha1/pushsecret_types.go, apis/externalsecrets/v1alpha1/secretstore_akeyless_types.go, apis/externalsecrets/v1alpha1/secretstore_aws_types.go, apis/externalsecrets/v1alpha1/secretstore_kubernetes_types.go, apis/externalsecrets/v1alpha1/secretstore_types.go, apis/externalsecrets/v1alpha1/secretstore_vault_types.go, apis/externalsecrets/v1beta1/clusterexternalsecret_types.go, apis/externalsecrets/v1beta1/externalsecret_types.go, apis/externalsecrets/v1beta1/secretstore_akeyless_types.go, apis/externalsecrets/v1beta1/secretstore_aws_types.go, apis/externalsecrets/v1beta1/secretstore_conjur_types.go, apis/externalsecrets/v1beta1/secretstore_kubernetes_types.go, apis/externalsecrets/v1beta1/secretstore_types.go, apis/externalsecrets/v1beta1/secretstore_vault_types.go, apis/generators/v1alpha1/generator_ecr.go, apis/generators/v1alpha1/generator_fake.go, apis/generators/v1alpha1/generator_vault.go
The missing tags can confuse some tools.
Fixes: #2853
Add missing omitempty json tags for optional fields
=> fix: add missing omitempty json tags for optional fields

.github/PAUL.yaml
Update PAUL.yaml to include roger
=> Update PAUL.yaml to include roger

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_template.go, pkg/controllers/externalsecret/externalsecret_controller_test.go
The labels and annotations on a Secret are removed if creationPolicy = Owner. The details are described in https://github.com/external-secrets/external-secrets/issues/2864
Closes https://github.com/external-secrets/external-secrets/issues/2864
As I commented [here](https://github.com/external-secrets/external-secrets/issues/2864#issuecomment-1806594681), at first I tried introducing SSA but soon realized it complicated the logic too much without much to gain. So instead of going down the path, I updated the setMetadata function to modify the metadata managed by the operator. With this approach, we can avoid reintroducing https://github.com/external-secrets/external-secrets/pull/2705 as well.
=> Stop deleting all the Secret metadata

deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/NOTES.txt, deploy/charts/external-secrets/templates/cert-controller-deployment.yaml, deploy/charts/external-secrets/templates/cert-controller-service.yaml, deploy/charts/external-secrets/templates/deployment.yaml, deploy/charts/external-secrets/templates/service.yaml, deploy/charts/external-secrets/templates/servicemonitor.yaml, deploy/charts/external-secrets/templates/webhook-deployment.yaml, deploy/charts/external-secrets/templates/webhook-service.yaml, deploy/charts/external-secrets/tests/__snapshot__/controller_test.yaml.snap, deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap, deploy/charts/external-secrets/tests/cert_controller_test.yaml, deploy/charts/external-secrets/tests/controller_test.yaml, deploy/charts/external-secrets/tests/webhook_test.yaml, deploy/charts/external-secrets/values.yaml
=> Remove references to Prometheus in Helm chart

deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
When running 'make helm.test' on the main branch, a test isn't passing. This makes some PRs fail the CI pipeline.
It's a simple fix, no need for an issue.
Just update the snapshot by executing the command "make helm.test.update".
=> Update Helm snapshot

README.md, SECURITY.md, docs/contributing/coc.md
The contact email is outdated.
Fixes #2948 
Update it to new email cncf-ExternalSecretsOp-maintainers@lists.cncf.io
=> Update contact email (#2948)

Makefile, Tiltfile, docs/contributing/devguide.md, tilt.debug.dockerfile, tilt.dockerfile
=> feat: introduce tilt into the development process

docs/introduction/stability-support.md
Update version support docs
relates to #2980
=> fix: bump kubernetes version support

docs/guides/pushsecrets.md
=> Fix typo in pushsecrets docs

docs/guides/getallsecrets.md
Documentation grammar 
added "'s"
- [x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ x] All commits are signed with `git commit --signoff`
- [x ] My changes have reasonable test coverage
- [x ] All tests pass with `make test`
- [x ] I ensured my PR is ready for review with `make reviewable`
=> grammar - it is

docs/provider/1password-automation.md
intuitive not intuative
Fixes #...
- [x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [x ] All commits are signed with `git commit --signoff`
- [ x] My changes have reasonable test coverage
- [ x] All tests pass with `make test`
- [ x] I ensured my PR is ready for review with `make reviewable`
=> gramar2 - intuitive not intuative

docs/guides/security-best-practices.md
The snippet[1] was not aligning with the schema defined in CRD.
[1] https://external-secrets.io/latest/guides/security-best-practices/
fix the document.
(This change is only for document)
=> Fix wrong namespaceSelector configuration in snippet in document

.github/workflows/helm.yml
=> temporarily removing ossf checks for helm release

pkg/provider/gitlab/gitlab.go
Just a small PR to fix a typo in an error message.
fixed a typo in an error message
fixed the typo because the typo bothered me when i'm already bothered troubleshooting :)
- [x ] I have read the [contribution guidelines](https://external-secrets.io/latest/contributing/process/#submitting-a-pull-request)
- [ x] All commits are signed with `git commit --signoff`
=> fixed gitlab error typo: gilabClient -> gitlabClient

docs/snippets/oracle-secret-store.yaml
`principalType: UserPrincipal` at wrong level
Fixes #3152
=> adjust position of principalType

docs/provider/conjur.md, docs/snippets/conjur-ca-bundle.yaml, docs/snippets/conjur-secret-store-jwt-secret-ref.yaml, docs/snippets/conjur-secret-store-jwt-service-account-ref.yaml
Improve the CyberArk doc
NA
Update this doc page: https://external-secrets.io/latest/provider/conjur/
~- [ ] My changes have reasonable test coverage~ - NA
~- [ ] All tests pass with `make test`~- NA
=> Update the CyberArk Provider docs

docs/provider/pulumi.md
This PR is updating the default refreshInterval to 5m
-
-
=> docs: Change default refreshInterval to 5m

pkg/provider/vault/client_push.go, pkg/provider/vault/client_push_test.go
This PR is adding support to pushing the whole secret to the Hashicorp Vault provider.
Fixes #3287
Proper treating when the `secretKey` is missing and therefore making the whole secret available for pushing.
=> fix: allow pushing the whole secret to Vault

.github/actions/sign/action.yml
=> bump cosign

deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/cert-controller-service.yaml, deploy/charts/external-secrets/templates/service.yaml, deploy/charts/external-secrets/templates/servicemonitor.yaml, deploy/charts/external-secrets/templates/webhook-service.yaml, deploy/charts/external-secrets/values.yaml
Support dual stack clusters
Fixes #3340
=> feat: add support for dual stack clusters

deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/_helpers.tpl, deploy/charts/external-secrets/templates/extra-manifests.yaml, deploy/charts/external-secrets/tests/extra_manifests_test.yaml, deploy/charts/external-secrets/values.yaml
Fixes: https://github.com/external-secrets/external-secrets/issues/2961
Closes: #3417
How do you like to solve the issue and why? Explained in the issue.
=> Add support for specifying extra manifests via helm

apis/externalsecrets/v1beta1/clusterexternalsecret_types.go, config/crds/bases/external-secrets.io_clusterexternalsecrets.yaml, deploy/crds/bundle.yaml, docs/api/spec.md, pkg/controllers/secretstore/client_manager.go
While reading client_manager.go, I noticed a few problems there, so I fixed them.
N/A
=> Refactor the SecretStore client manager

docs/guides/common-k8s-secret-types.md
What is the problem you're trying to solve? fix typo in documentation
Fixes #...
=> Update common-k8s-secret-types.md to fix get secret jsonpath

deploy/charts/external-secrets/templates/_helpers.tpl
The Helm function helper file contains a couple of merge pointers from #3420.
=> fix(helm): remove git merge pointers

docs/snippets/generator-github-example-basicauth.yaml
There's a typo in the example.
n/a
n/a
=> Fix typo: temaplate --> template

docs/provider/oracle-vault.md, docs/snippets/oracle-external-secret-plaintext.yaml, docs/snippets/oracle-instance-principal.yaml, docs/snippets/oracle-principal-type.yaml, docs/snippets/oracle-secret-store.yaml, docs/snippets/oracle-workload-identity.yaml
Oracle provider documentation was incomplete and missing examples.
Fixes #3521 
Update the Oracle Provider documentation with additional links, examples to facilitate users.
=> Oracle Vault Provider Documentation

MAINTAINERS.md
=> feat: kick github actions on main

.github/PAUL.yaml
I've decided to step down from a maintainer, so I'd like to remove myself from the list. It has been an incredible journey with all of you, and I wish you nothing but the best!
Fixes #...
=> Remove shuheiktgw from maintainers

e2e/framework/addon/chart.go
=> fix: e2e installation of ESO needs to update dependencies first

pkg/provider/gcp/secretmanager/client.go, pkg/provider/gcp/secretmanager/client_test.go
This PR is adding support to pushing the whole secret to the GCPSM provider.
Fixes #3643 
Proper treating when the secretKey is missing and therefore making the whole secret available for pushing.
Note, there was one e2e failure on webhook secret because it looks like a local server wasn't launched properly. I don't think it's possible that this was caused by my changes
```
=== RUN   TestWebhookGetSecret
webhook_test.go:407: error timeout: unexpected error: 'failed to call endpoint: Get "http://127.0.0.1:62292/api/getsecret?id=testkey&version=1": dial tcp 127.0.0.1:62292: i/o timeout (Client.Timeout exceeded while awaiting headers)' (expected 'context deadline exceeded')
--- FAIL: TestWebhookGetSecret (0.05s)
FAIL
coverage: 49.8% of statements
FAIL …
```
=> fix: implement handling for pushing whole k8s secret to gcsm

.github/workflows/e2e.yml
=> fix e2e permissions

docs/contributing/process.md
=> bump docs with e2e commands

.github/workflows/e2e.yml
=> also needs pull-requests

.github/workflows/e2e.yml
=> use github token to allow comment

.github/workflows/e2e.yml
=> fix github credentials

.github/workflows/e2e.yml
=> sets eso-service-account for creating e2e comments

pkg/common/webhook/webhook.go, pkg/provider/webhook/webhook.go, pkg/provider/webhook/webhook_test.go
Fixes [#3652](https://github.com/external-secrets/external-secrets/issues/3652)
=> Fix: Only URL encode data being passed to URLs (#3652)

pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/aws/parameterstore/parameterstore_test.go
This PR fixes a `PushSecret` being updated remotely in every ESO cycle in case of a parameter with type `SecureString`.
Fixes #3697
Ensure that `WithDecryption` is enabled when fetching a remote parameter value for type `SecureString`.
=> fix: decrypt remote parameter for SecureString type

ADOPTERS.md
Grafana Labs is using ESO :heart:
=> Add Grafana Labs to ADOPTERS.md

deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
=> fix: run helm.test.update on main branch

pkg/controllers/crds/crds_controller.go, pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_template.go, pkg/controllers/pushsecret/pushsecret_controller.go, pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/kubernetes/validate.go, pkg/provider/vault/client_push.go
Demonstrate how it's possible to simplify some code with Go 1.23
None.
Make use of the new slices and maps packages.
=> Demonstrate new slices/maps packages

deploy/charts/external-secrets/templates/cert-controller-rbac.yaml
=> fix: add watch to validatingwebhookconfigs

docs/eso-blogs.md
I've added my new blog post about using ESO with IBM Secrets Manager
=> Add blog post about ESO and IBM Secrets Manager

overrides/main.html
towards #3872 
Adds pixel to documentation.
=> feat: adds scarf to docs

apis/generators/v1alpha1/generator_uuid.go, config/crds/bases/generators.external-secrets.io_uuids.yaml, deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap, deploy/crds/bundle.yaml
Fixes https://github.com/external-secrets/external-secrets/issues/3882
=> fix: update uuids.generator shortname

cmd/webhook.go
=> fix: remove unnecessary err check

docs/api/generator/uuid.md
Fixes https://github.com/external-secrets/external-secrets/issues/3953
=> fix: uuid generator doc example links

docs/eso-blogs.md
I added our new blog post about Pulumi ESC and ESO
=> docs: add blog post about Pulumi ESC and ESO

apis/externalsecrets/v1beta1/secretsstore_infisical_types.go, config/crds/bases/external-secrets.io_clustersecretstores.yaml, config/crds/bases/external-secrets.io_secretstores.yaml, deploy/crds/bundle.yaml, docs/api/spec.md, docs/snippets/infisical-generic-secret-store.yaml, pkg/provider/infisical/api/api.go, pkg/provider/infisical/api/api_models.go, pkg/provider/infisical/client.go, pkg/provider/infisical/provider.go
Greetings!
After few time spent to read a password from a folder, I saw that there is no way to configure the recursive option with Infisical and this option is required when you want to read secrets from folders. I did the necessary changes. 
Fixes #3938
=> feat: edit all required changes for recursive option

docs/snippets/beyondtrust-secret-store.yaml, go.mod, go.sum
Upgrade beyondtrust go client library.
=> chore: upgrade beyondtrust go client library

ADOPTERS.md
=> chore: Add Hostinger to ADOPTERS.md

MAINTAINERS.md
=> chore: move inactive maintainers to emeritus

.github/workflows/helm.yml, deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/values.yaml
=> fix: permissions on steps is not a thing

docs/eso-blogs.md
Adds blog post on secrets replication on kubernetes.
=> chore: add blog

pkg/provider/gitlab/gitlab.go
Fixes https://github.com/external-secrets/external-secrets/issues/3474
=> fix: gitlab empty response

.github/workflows/e2e.yml
Related to https://github.com/external-secrets/external-secrets/pull/4104.
=> fix: e2e test for AWS not setting name and namespace

design/011-deprecate-olm.md
This Proposal deprecates OLM builds as a part of our build cycle.
=> chore: deprecate olm proposal

pkg/provider/gitlab/gitlab.go
Related discussion: https://github.com/external-secrets/external-secrets/issues/4167#issuecomment-2519394111
=> fix: error handling for gitlab variable fetch

.github/workflows/helm.yml, apis/generators/v1alpha1/types_ecr.go, config/crds/bases/generators.external-secrets.io_clustergenerators.yaml, config/crds/bases/generators.external-secrets.io_ecrauthorizationtokens.yaml, deploy/crds/bundle.yaml, pkg/generator/ecr/ecr.go, pkg/generator/ecr/ecr_test.go
Add support for AWS ECR Public authorization tokens
Fixes #4228
Added an initial implementation which  ECR Public authorization tokens
=> Add AWS ECR Public authorization token support

docs/snippets/gitops/repositories.yaml, e2e/Dockerfile
=> fix: SonarCloud security hotspot

.github/workflows/release.yml
=> revert: softprops update failing the release process

config/crds/bases/generators.external-secrets.io_quayaccesstokens.yaml, deploy/crds/bundle.yaml
=> fix: run make check-diff on main

deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
=> fix: helm chart test was not updated

.github/workflows/release_esoctl.yml
=> fix: rename render to esoctl in release action

.gitignore, cmd/esoctl/README.md, docs/guides/using-esoctl-tool.md, docs/snippets/esoctl-tool-push-secret-snippet.yaml, hack/api-docs/mkdocs.yml
Fixes https://github.com/external-secrets/external-secrets/issues/4323
=> fix: documentation and naming for render tool

apis/externalsecrets/v1alpha1/externalsecret_types.go, apis/externalsecrets/v1beta1/externalsecret_types.go, config/crds/bases/external-secrets.io_externalsecrets.yaml, deploy/crds/bundle.yaml
Co-authored-by: Frans6  jefferson.frds@gmail.com
Fixes #3809
=> feat: column storeType

docs/snippets/passbolt-external-secret-example.yaml, docs/snippets/passbolt-external-secret-findbyname.yaml
The refresh interval is too aggressive, misaligned with others, and generates excessive unnecessary traffic.
Align the refresh interval with others and avoid unnecessary server requests.
=> Fix passbolt refreshInterval

GOVERNANCE.md
=> doc: link to the CNCF code of conduct

docs/guides/using-esoctl-tool.md, docs/snippets/esoctl-tool-push-secret-snippet.yaml
=> fix: the esoctl tooling website was not working

.github/actions/e2e-managed/action.yml, .github/workflows/e2e-managed.yml, .github/workflows/e2e.yml, .github/workflows/update-deps.yml, e2e/go.mod, go.mod
=> chore: update go version to 1.23.6

docs/contributing/calendar.md, hack/api-docs/mkdocs.yml
=> docs: add a link to the cncf calendar for the community meeting

deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap
=> chore: update helm test for github

pkg/provider/onepassword/fake/fake.go, pkg/provider/onepassword/onepassword.go, pkg/provider/onepassword/onepassword_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/4473
=> fix: allow using UUID as vault and item name

pkg/provider/aws/secretsmanager/secretsmanager.go, pkg/provider/aws/secretsmanager/secretsmanager_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/4211
=> feat: enable pushing the entire secret with aws secrets manager

pkg/provider/akeyless/akeyless_test.go, pkg/provider/aws/parameterstore/parameterstore.go, pkg/provider/oracle/oracle_test.go
=> fix: remove fmt.Println from code and test code

docs/api/generator/acr.md, docs/snippets/generator-acr.yaml, hack/api-docs/mkdocs.yml, pkg/generator/acr/acr.go, terraform/azure/key-vault/variables.tf
Following along with documentation and noticed outdated references to AAD as well as some dates.
- Updates AAD to Microsoft Entra ID
- 2024 to 2025
=> Updates to AAD and date update

.github/workflows/codeql.yml, .github/workflows/e2e.yml
=> fix: define top level permissions and fix token scope

apis/externalsecrets/v1beta1/secretstore_conjur_types.go, config/crds/bases/external-secrets.io_clustersecretstores.yaml, config/crds/bases/external-secrets.io_secretstores.yaml, deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap, deploy/crds/bundle.yaml, docs/api/externalsecret.md, docs/api/spec.md
Improve Conjur authentication field descriptions in SecretStore CRD
https://github.com/external-secrets/external-secrets/issues/4542 
Improves documentation
=> adding conjur description

docs/contributing/release.md, docs/introduction/getting-started.md
=> docs: remove OLM installation and release docs

.github/workflows/dependabot-approve.yml, .github/workflows/update-deps.yml
=> feat: check-diff on update deps

.github/workflows/dependabot-approve.yml
=> fix: enhancing security for new workflow

deploy/crds/bundle.yaml, hack/crd.generate.sh, hack/helm.generate.sh
Fixes https://github.com/external-secrets/external-secrets/pull/4673
=> fix: remove the conversion hook completely

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/crds.yml, .github/workflows/dependabot-approve.yml, .github/workflows/dlc.yml, .github/workflows/docs.yml, .github/workflows/e2e-managed.yml, .github/workflows/e2e.yml, .github/workflows/helm.yml, .github/workflows/ok-to-test-managed.yml, .github/workflows/ok-to-test.yml, .github/workflows/publish.yml, .github/workflows/rebuild-image.yml, .github/workflows/release.yml, .github/workflows/release_esoctl.yml, .github/workflows/scorecard.yml, .github/workflows/stale.yml, .github/workflows/update-deps.yml
As part of `1.0.0` - improving pipeline security posture
Fixes #4677
=> feat: adds harden-runner to pipelines

ADOPTERS.md
Skeeled is using External Secrets Operator 🚀 ❤️
=> chore: Add skeeled to ADOPTERS.md

.github/actions/e2e-managed/action.yml, .github/actions/sign/action.yml, .github/workflows/ci.yml, .github/workflows/e2e-managed.yml, .github/workflows/publish.yml, .github/workflows/rebuild-image.yml, .github/workflows/release.yml
We're not able to push artefacts on `main` builds.
=> fix: ci artefact push

pkg/provider/aws/secretsmanager/secretsmanager.go
Fixes https://github.com/external-secrets/external-secrets/issues/1817#issuecomment-2845266217
=> fix: add kmskeyid to secret creation

docs/provider/openbao.md, hack/api-docs/mkdocs.yml
Documentation addition
Relates #3664
Add a minimal documentation about OpenBao being supported with the HashiCorp Vault Provider
=> doc(openbao): add information about it working with vault provider

cmd/controller/root.go, pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_secret.go, pkg/controllers/externalsecret/externalsecret_controller_template.go
I want to use some cool eso features internally without needing to start a whole new reconciler for it.
Expose publicly the methods I want :)
=> feat: improve code integration api

.github/workflows/helm.yml
=> fix: fix (again) helm release)

docs/snippets/generator-ecr-example.yaml
Fix the document for AWS ECR Generator.
Fixes #4826 
Add `{% raw %}` action.
=> docs: fix: AWS ECR Generator

pkg/provider/onepasswordsdk/client.go, pkg/provider/onepasswordsdk/client_test.go
Fixes https://github.com/external-secrets/external-secrets/issues/4893
=> feat: have parity with 1Password connect service for GetSecretMap

pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/util.go, pkg/controllers/templating/parser.go
=> fix: fqdn to allow secret names bigger than 92 characters

docs/guides/ownership-deletion-policy.md, pkg/controllers/externalsecret/externalsecret_controller.go, pkg/controllers/externalsecret/externalsecret_controller_test.go
=> fix: creation policy orphan now does not react to secret updates

pkg/template/v2/template.go
Fixes https://github.com/external-secrets/external-secrets/issues/5010
=> fix: do not turn original value into string on value scope

e2e/framework/addon/eso_argocd_application.go, e2e/suites/argocd/install.go, e2e/suites/provider/cases/vault/vault.go
=> fix: update the e2e test with the new store status value

deploy/charts/external-secrets/templates/cert-controller-rbac.yaml, pkg/controllers/crds/crds_controller.go, pkg/controllers/webhookconfig/webhookconfig.go, pkg/controllers/webhookconfig/webhookconfig_test.go, pkg/utils/utils.go
Migrate from endpoints to endpointslices
Fixes #4992
=> feat: migration from endpoint to endpointslice

docs/contributing/roadmap.md, docs/introduction/stability-support.md
Update version/support table 
towards: https://github.com/external-secrets/external-secrets/issues/5134
=> fix: bump support table

Makefile, cmd/controller/root.go, deploy/charts/external-secrets/README.md, deploy/charts/external-secrets/templates/deployment.yaml, deploy/charts/external-secrets/tests/controller_test.yaml, deploy/charts/external-secrets/values.schema.json, deploy/charts/external-secrets/values.yaml, docs/api/controller-options.md, tests/__snapshot__/clustersecretstore-v1.yaml, tests/__snapshot__/secretstore-v1.yaml
Fixes https://github.com/external-secrets/external-secrets/issues/3012
=> feat: add liveness probe to eso controller

ADOPTERS.md
- Add Cisco.com to the ADOPTERS.md
N/A
N/A
=> chore: add Cisco to ADOPTERS.md

ADOPTERS.md
chore(docs): update `ADOPTERS.md` to include SAP
SAP is an active and collaborating company in the ESO ecosystem, and uses ESO productively across the entire product range for our cloud offerings.
I have the admission of the company to admit us as Adopter.
_Disclaimer: I work at SAP and received admission rights from the SAP OSPO_
_Company Disclaimer: SAP reserves all intellectual property rights in and to its trademarks. Company’s use of the SAP trademarks in violation of this consent letter may be subject to legal action under applicable law. SAP’s consent and the logos and/or trademarks to which the consent applies are provided to Company as-is with no warranties of any type_
=> chore(docs): update `ADOPTERS.md` to include SAP

hack/api-docs/add_eso_version.sh
The script failed silently.
Updated and testing with:
```
make -C ./hack/api-docs stability-support.update DOCS_VERSION=v0.20.2-21.g5d41103ef.dirty
```
Resulting in:
```md
| ESO Version | Kubernetes Version | Release Date   | End of Life     |
| ----------- | ------------------ | -------------- | --------------- |
| 0.20.x      | 1.33               | August 22, 2025  | Release of 0.21 |
| 0.19.x     | 1.33               | August 2, 2025 | August 22, 2025 |
```
Fixes https://github.com/external-secrets/external-secrets/issues/4961
=> fix: stability update document did not update the stability table correctly

SECURITY.md, docs/guides/security-best-practices.md, docs/introduction/stability-support.md
=> chore(docs): update helm charts

.github/workflows/e2e.yml, apis/externalsecrets/v1/externalsecret_types.go, config/crds/bases/external-secrets.io_externalsecrets.yaml, deploy/charts/external-secrets/tests/__snapshot__/crds_test.yaml.snap, deploy/crds/bundle.yaml, docs/api/selectable-fields.md, e2e/Makefile, hack/api-docs/mkdocs.yml
Fixes https://github.com/external-secrets/external-secrets/issues/4810
```
```
- charts
- release
- testing
- security
- templating
=> feat: add selectable fields to the CRDs

tests/__snapshot__/clusterexternalsecret-v1.yaml, tests/__snapshot__/externalsecret-v1.yaml, tests/__snapshot__/pushsecret-v1alpha1.yaml
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
=> chore: just updating the crd conformance tests

docs/contributing/burnout-mitigation.md, hack/api-docs/mkdocs.yml
Fixes https://github.com/external-secrets/external-secrets/issues/5293
```
```
- charts
- release
- testing
- security
- templating
=> docs: add burnout prevention strategies and mitigation policy document

pkg/controllers/secretstore/common_test.go
We saw a flaking test. I couldn't reproduce it so added some more information https://github.com/external-secrets/external-secrets/actions/runs/17791135096/job/50568277415#step:9:596.
```
```
- charts
- release
- testing
- security
- templating
=> test: add more information to potentially flaky test

.github/workflows/lgtm.yml
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
=> feat(ci): use separate github app for lgtm workflow.

.github/workflows/lgtm-remove-on-update.yml
[What is the problem you're trying to solve?](https://kubernetes.slack.com/archives/C047LA9MUPJ/p1758724942795459?thread_ts=1758107126.395629&cid=C047LA9MUPJ)
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
=> fix(ci): run lgtm label remover in pull_request_target context instead

README.md
There are some outdated links referring to how the meetings used to be run. The times were also incorrect (still referncing alternating timezones) but I've left that untouched as it is likely to change again soon.
N/A
update the links...
```
```
- charts
- release
- testing
- security
- templating
=> docs: update community meeting section

.github/workflows/zizmor.yml
Adding Zizmor to scan github actions workflows
#4676 
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
=> feat(ci): zizmor github actions vuln scanner

docs/contributing/process.md
Fixes #...
```
```
- charts
- release
- testing
- security
- templating
=> chore(docs): update pull request approval process

.github/actions/e2e-managed/action.yml, .github/workflows/e2e-managed.yml
This PR removes a unused secret from a github action.
=> fix: remove unused secret
